<?php 
    $title= "Frequently Asked Questions - Texas Medical Disclosure Panel" ; 
    include '..//home/codio/workspace/includes/header.html'; 
    include '..//home/codio/workspace/includes/menus/tmdp_menu.html'; 
?>
<p>The Texas Medical Disclosure Panel (Panel) was established in 1977 to provide physicians and other health care providers with guidelines for informed consent, both as to the risks and hazards that should be disclosed to the patient and the form of the disclosure.  <a href="http://www.statutes.legis.state.tx.us/Docs/CP/htm/CP.74.htm" title="Chapter 74, Subchapter C">Chapter 74, Subchapter C</a>, Sections 74.101-74.107, of the Texas Civil Practices and Remedies Code (Consent Statute) set out the specific requirements as to the Panel and the duty of disclosure for informed consent.  The regulations promulgated by the Panel in implementing the statute are set out at <a href="http://texreg.sos.state.tx.us/public/readtac$ext.ViewTAC?tac_view=4&ti=25&pt=7&ch=601&rl=Y" title="25 Texas Administrative Code, Sections 601.1-601.8">25 Texas Administrative Code, Sections 601.1-601.8</a>.</p>
<p>The following is intended to explain the duties of the Panel, the purpose of the guidelines, and use of the consent forms, and to address some of the frequently asked questions.  Unless otherwise provided, the term “provider” refers to a physician or other health care provider identified in the Consent Statute.  This information is not intended as legal advice or to supercede the Consent Statute and regulations promulgated by the Panel, but as general guidance only.  Please note that the Panel does not provide expert testimony in litigation or opinions on the adequacy of consent to medical treatment or surgical procedures other than as provided in the Consent Statute and implementing regulations.</p>
<h2><a name="TopQues"></a>List of Frequently Asked Questions </h2>
<ol>
	<li><a title="What is informed consent?" href="#faq1">What is informed consent?</a> </li>
	<li><a title="What is the Informed Consent Statute?" href="#faq2">What is the Informed Consent Statute?</a> </li>
	<li><a title="What is the purpose of the Panel?" href="#faq3">What is the purpose of the Panel?</a> </li>
	<li><a title="Who serves on the Panel and how are the members appointed?" href="#faq4">Who serves on the Panel and how are the members appointed?</a> </li>
	<li><a title="What is a List A procedure? " href="#faq5">What is a List A procedure?</a></li>
	<li><a title="What is a List B procedure?" href="#faq6">What is a List B procedure?</a> </li>
	<li><a title="How does the Panel obtain information about medical treatments and surgical procedures and the associated risks?" href="#faq7">How does the Panel obtain information about medical treatments and surgical procedures and the associated risks?</a> </li>
	<li><a title="If a provider discloses the risks and hazards identified by the Panel for a List A medical treatment or surgical procedure and uses the Panel’s consent form, can the provider be liable for negligence in obtaining informed consent?&amp;nbsp;" href="#faq8">If a provider discloses the risks and hazards identified by the Panel for a List A medical treatment or surgical procedure and uses the Panel’s consent form, can the provider be liable for negligence in obtaining informed consent? </a> </li>
	<li><a title="Is a provider required to disclose the risks identified by the Panel for a List A procedure or to use the Panel’s consent forms?&amp;nbsp;" href="#faq9">Is a provider required to disclose the risks identified by the Panel for a List A procedure or to use the Panel’s consent forms? </a> </li>
	<li><a title="Are there any exceptions to the rebuttable presumption if the provider fails to disclose the List A risks or use the Panel’s form?" href="#faq10">Are there any exceptions to the rebuttable presumption if the provider fails to disclose the List A risks or use the Panel’s form?</a> </li>
	<li><a title="What are the provider’s responsibilities if the proposed medical treatment or surgical procedure is not on List A or List B?" href="#faq11">What are the provider’s responsibilities if the proposed medical treatment or surgical procedure is not on List A or List B?</a> </li>
	<li><a title="Does the Panel publish a consent form to be used for the medical treatments and surgical procedures on List A?" href="#faq12">Does the Panel publish a consent form to be used for the medical treatments and surgical procedures on List A?</a> </li>
	<li><a title="What consent forms have been established by the Panel?" href="#faq13">What consent forms have been established by the Panel?</a> </li>
	<li><a title="Is the provider required to use the consent forms promulgated by the Panel?" href="#faq14">Is the provider required to use the consent forms promulgated by the Panel?</a> </li>
	<li><a title="Can a provider use the Panel’s Disclosure and Consent---Medical and Surgical Procedures form to obtain consent to perform a hysterectomy? " href="#faq15">Can a provider use the Panel’s Disclosure and Consent---Medical and Surgical Procedures form to obtain consent to perform a hysterectomy?</a></li>
	<li><a title="Since the statutory consent form includes consent to the administration of blood, which is a List A procedure with identified risks, can the provider preprint those risks on the Panel’s form under the section dealing with consent to blood?" href="#faq16">Since the statutory consent form includes consent to the administration of blood, which is a List A procedure with identified risks, can the provider preprint those risks on the Panel’s form under the section dealing with consent to blood?</a> </li>
	<li><a title="Does a provider need to use the Panel’s consent form when obtaining consent to a medical treatment or surgical procedure that is on List B (meaning the Panel has determined that disclosure of specific risks and hazards is not required)?" href="#faq17">Does a provider need to use the Panel’s consent form when obtaining consent to a medical treatment or surgical procedure that is on List B (meaning the Panel has determined that disclosure of specific risks and hazards is not required)?</a></li>
	<li><a title="If the provider uses the Panel’s Disclosure and Consent---Medical and Surgical Procedures form to obtain consent for a List B procedure, what would the provider put on the form under the section for the listing of risks since the Panel has determined there are no specific risks that need to be disclosed?" href="#faq18">If the provider uses the Panel’s Disclosure and Consent---Medical and Surgical Procedures form to obtain consent for a List B procedure, what would the provider put on the form under the section for the listing of risks since the Panel has determined there are no specific risks that need to be disclosed?</a> </li>
	<li><a title="What if the provider believes there are risks that should be disclosed for a List B procedure?" href="#faq19">What if the provider believes there are risks that should be disclosed for a List B procedure?</a> </li>
	<li><a title="What if a provider believes that there are additional risks and hazards associated with a List A procedure that should be disclosed beyond those identified by the Panel?  Can the provider add those risks to the risks identified by the Panel?" href="#faq20">What if a provider believes that there are additional risks and hazards associated with a List A procedure that should be disclosed beyond those identified by the Panel? Can the provider add those risks to the risks identified by the Panel?</a></li>
	<li><a title="May a provider add information or text to the Panel’s consent forms other than risks and hazards, such as consent to photographs?" href="#faq21">May a provider add information or text to the Panel’s consent forms other than risks and hazards, such as consent to photographs?</a> </li>
	<li><a title="Can the provider delete information or text from the Panel’s consent forms?" href="#faq22">Can the provider delete information or text from the Panel’s consent forms?</a> </li>
	<li><a title="Can the information in the Panel’s consent form be incorporated into the provider’s own consent form?" href="#faq23">Can the information in the Panel’s consent form be incorporated into the provider’s own consent form?</a> </li>
	<li><a title="Can more than one List A procedure be included on a single Disclosure and Consent – Medical and Surgical Procedures form or does the provider need to use a separate form for each List A procedure?" href="#faq24">Can more than one List A procedure be included on a single Disclosure and Consent – Medical and Surgical Procedures form or does the provider need to use a separate form for each List A procedure?</a> </li>
	<li><a title="What does the Panel require for consent to electroconvulsive therapy or ECT?" href="#faq25">What does the Panel require for consent to electroconvulsive therapy or ECT?</a></li>
	<li><a title="How long is the consent form valid after having been signed?" href="#faq26">How long is the consent form valid after having been signed?</a> </li>
	<li><a title="Is the provider performing the medical treatment or surgical procedure required to obtain the consent or can the provider assign the responsibility to another individual?" href="#faq27">Is the provider performing the medical treatment or surgical procedure required to obtain the consent or can the provider assign the responsibility to another individual?</a></li>
	<li><a title="Who is responsible to complete the consent form, i.e., fill in the blanks on the form?" href="#faq28">Who is responsible to complete the consent form, i.e., fill in the blanks on the form?</a></li>
	<li><a title="Whose address information is intended to be inserted at the end of the consent forms?" href="#faq29">Whose address information is intended to be inserted at the end of the consent forms?</a></li>
	<li><a title="How do providers obtain the lists and consent forms?" href="#faq30">How do providers obtain the lists and consent forms?</a></li>
	<li><a title="How do providers learn of changes by the Panel or procedures that are added to the lists?" href="#faq31">How do providers learn of changes by the Panel or procedures that are added to the lists?</a></li>
	<li><a title="What is the relationship between the Panel and the Texas Department of State Health Services?" href="#faq32">What is the relationship between the Panel and the Texas Department of State Health Services?</a></li>
	<li><a title="Under List A procedures, (b) Cardiovascular system, several procedures include the following as a risk:  “All associated risks as listed under paragraph (2)(B) of this subsection.”  What is the provider supposed to put on the consent form for these procedures?" href="#faq33">Under List A procedures, (b) Cardiovascular system, several procedures include the following as a risk:  “All associated risks as listed under paragraph (2)(B) of this subsection.”  What is the provider supposed to put on the consent form for these procedures?</a></li>
	<li><a title="List A, (n) Radiology, includes “Procedures utilizing prolonged fluoroscopy” as a List A procedure.  What constitutes “prolonged fluoroscopy”?" href="#faq34">List A, (n) Radiology, includes “Procedures utilizing prolonged fluoroscopy” as a List A procedure.  What constitutes “prolonged fluoroscopy”?</a></li>
	<li><a title="Why did the Panel develop a separate consent form for anesthesia and/or perioperative pain management (anesthesia)?" href="#faq35">Why did the Panel develop a separate consent form for anesthesia and/or perioperative pain management (anesthesia)?</a></li>
	<li><a title="How is the separate anesthesia consent form intended to be used?" href="#faq36">How is the separate anesthesia consent form intended to be used?</a></li>
	<li><a title="What form should the provider use if the provider is administering anesthesia or analgesia solely for purposes of pain management, and not in conjunction with another procedure?" href="#faq37">What form should the provider use if the provider is administering anesthesia or analgesia solely for purposes of pain management, and not in conjunction with another procedure?</a></li>
	<li><a title="If the same provider is performing a List A procedure and administering List A anesthesia or analgesia, can the provider use only the Disclosure and Consent – Medical and Surgical Procedures form to obtain consent for both the procedure and the anesthesia or analgesia?" href="#faq38">If the same provider is performing a List A procedure and administering List A anesthesia or analgesia, can the provider use only the Disclosure and Consent – Medical and Surgical Procedures form to obtain consent for both the procedure and the anesthesia or analgesia?</a></li>
	<li><a title="Can dentists use the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) when administering nitrous oxide?" href="#faq39">Can dentists use the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) when administering nitrous oxide?</a></li>
	<li><a title="The Disclosure and Consent – Medical and Surgical Procedures form, and the Disclosure and Consent for Hysterectomy form (procedure consent forms), each contain information on anesthesia.  Won’t patients be confused by the references to anesthesia on these procedure consent forms when also presented with the separate Anesthesia and/or Perioperative Pain Management (Analgesia) consent form for anesthesia (anesthesia consent form)?" href="#faq40">The Disclosure and Consent – Medical and Surgical Procedures form, and the Disclosure and Consent for Hysterectomy form (procedure consent forms), each contain information on anesthesia.  Won’t patients be confused by the references to anesthesia on these procedure consent forms when also presented with the separate Anesthesia and/or Perioperative Pain Management (Analgesia) consent form for anesthesia (anesthesia consent form)?</a></li>
	<li><a title="Can more than one type of anesthesia or analgesia be checked on the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia)?" href="#faq41">Can more than one type of anesthesia or analgesia be checked on the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia)?</a></li>
	<li><a title="If the provider already has an anesthesia consent form, can the provider modify that form to include the information from the Panel’s anesthesia consent form and keep using its existing form?" href="#faq42">If the provider already has an anesthesia consent form, can the provider modify that form to include the information from the Panel’s anesthesia consent form and keep using its existing form?</a></li>
	<li><a title="The Disclosure and Consent – Medical and Surgical Procedures form only references a “physician,” but a health care professional who is not a physician may be using the consent form to obtain consent.  Can the health care professional performing the medical or surgical procedure change the term “physician” to the correct discipline?" href="#faq43">The Disclosure and Consent – Medical and Surgical Procedures form only references a “physician,” but a health care professional who is not a physician may be using the consent form to obtain consent.  Can the health care professional performing the medical or surgical procedure change the term “physician” to the correct discipline?</a></li>
</ol>
<h2>Answers to Frequently Asked Questions </h2>
<hr/>
<h3>General </h3>
<p><strong><em><a id="tmdpfaq1" name="tmdpfaq1"></a></em></strong></p>
<p id="faq1"> <strong><em>1. What is informed consent?</em></strong>  Informed consent is the permission given by a patient to perform a medical treatment or surgical procedure after the patient has been advised of the risks or hazards that could influence a reasonable person in deciding whether or not to give permission.  In order for the patient to make an informed decision about whether to give his or her permission, the patient needs information about the treatment or procedure and the risks associated with it.  Informed consent deals with the information provided to the patient and how it is provided when obtaining the patient’s permission to perform the treatment or procedure.</p>
<p id="faq2"> <strong><em>2. What is the Informed Consent Statute?</em></strong> The Informed Consent Statute is Subchapter C of Chapter 74 of the Texas Civil Practice and Remedies Code, Sections 74.101-74.107.  The Informed Consent Statute provides that, for a patient to recover against a provider for lack of informed consent, the patient must show that the provider was negligent in failing to disclose the risks or hazards that could have influenced a reasonable person in making a decision to give or withhold consent.  Informed Consent Statute, Sec. 74.101 of the Texas Civil Practice and Remedies Code. </p>
<hr/>
<h3>About the Panel</h3>
<p id="faq3"> <strong><em>3. What is the purpose of the Panel? </em></strong> The purpose of the Panel is to determine what risks and hazards related to medical treatments and surgical procedures must be disclosed by a provider to the patient in obtaining informed consent, the substance of the disclosure, and the form in which disclosure should be made.  Informed Consent Statute, Sec. 74.102(a) of the Texas Civil Practice and Remedies Code.</p>
<p id="faq4"> <strong><em>4. Who serves on the Panel and how are the members appointed?</em></strong> The Panel is composed of six physicians and three attorneys, appointed for six-year terms by the Commissioner of the Texas Department of State Health Services.  Informed Consent Statute, Sec. 74.102(c) of the Texas Civil Practice and Remedies Code.</p>
<hr/>
<h3>The Work of the Panel</h3>
<p id="faq5"> <strong><em>5. What is a List A procedure?  </em></strong> The Panel is required to prepare separate lists of medical treatments and surgical procedures that require disclosure of specific risks and hazards and those treatments and procedures that do not.  Informed Consent Statute, Sec. 74.103(b) of the Texas Civil Practice and Remedies Code.  <a href="/hfp/tmdp-rules.aspx">List A</a> sets out the treatments and procedures that the Panel has determined require a disclosure of specific risks and hazards when obtaining informed consent.  For each List A treatment or procedure, the Panel has identified the specific risks and hazards that should be disclosed in obtaining informed consent for that treatment or procedure.  The List A procedures are set out in the Panel’s regulations at 25 Texas Administrative Code Section 601.2.</p>
<p id="faq6"> <strong><em>6. What is a List B procedure? </em></strong><a href="/hfp/tmdp-rules.aspx">List B</a> treatments and procedures are those that the Panel has determined do not require any disclosure of specific risks or hazards associated with the treatment or procedure.  The List B treatments and procedures are set out in the Panel’s regulations at 25 Texas Administrative Code Section 601.3.</p>
<p><a href="/hfp/tmdpFAQ.shtm#TopQues">To Questions</a></p>
<p id="faq7"> <strong><em>7. How does the Panel obtain information about medical treatments and surgical procedures and the associated risks?</em></strong> The Panel relies on the expertise of its physician members as well as input from professional medical societies and associations in determining whether there should be a disclosure of risks and hazards in connection with a particular medical treatment or surgical procedure.  Any additions or changes to either List A or List B that are being proposed by the Panel are published in draft form in the Texas Register and anyone may provide comments to the Panel on the proposed addition or change during the 30 days following publication of the proposal.  The Panel then reviews the comments and publishes the final addition or change in the Texas Register with the date that the addition or change is effective.</p>
<hr/>
<h3>Legal Protections Afforded by Statute </h3>
<p id="faq8"> <strong><em>8. If a provider discloses the risks and hazards identified by the Panel for a List A medical treatment or surgical procedure and uses the Panel’s consent form, can the provider be liable for negligence in obtaining informed consent?  </em></strong> If the provider complies with the procedures established by the Panel, the Informed Consent Statute provides a “rebuttable presumption” that the provider was not negligent in obtaining informed consent.  In a health care liability claim by a patient against a provider alleging negligent failure to disclose the risks and hazards of a medical treatment or surgical procedure, if the provider disclosed the risks identified by the Panel for a List A procedure, there is a rebuttable presumption that the provider was not negligent and the jury will be so informed.  The patient must then present evidence to overcome or “rebut” the presumption that the provider fulfilled his or her duty to disclose risks and hazards to recover on the claim.  If the Panel has determined that a disclosure of specific risks and hazards is not required for a certain treatment or procedure (or a List B procedure) and the provider does not disclose any risks or hazards to the patient, there is the same rebuttable presumption that the provider met the requirements of the statute and was not negligent.  Informed Consent Statute, Sec. 74.106 of the Texas Civil Practice and Remedies Code.</p>
<p id="faq9"> <strong><em>9. If a provider required to disclose the risks identified by the Panel for a List A procedure or to use the Panel’s consent forms?</em></strong>  No (except in the case of a hysterectomy---see discussion below), but if the provider fails to disclose the specific risks and hazards identified by the Panel for a List A procedure or to use the Panel’s form, in the event of a health care liability claim on the issue of informed consent there will be a rebuttable presumption that the provider was negligent and failed to fulfill the duty of disclosure.  The jury will be so informed and the provider must then present evidence to rebut the presumption of negligence.  Informed Consent Statute, Sec. 74.106 of the Texas Civil Practice and Remedies Code.</p>
<p><a href="/hfp/tmdpFAQ.shtm#TopQues">To Questions</a></p>
<p id="faq10"> <strong><em>10. Are there any exceptions to the rebuttable presumption if the provider fails to disclose the List A risks or use the Panel’s form?</em></strong><strong><em>  </em></strong> The Informed Consent Statute provides that the provider may not be found negligent for failure to disclose if there was an emergency or a reason it was not medically feasible to make the disclosure. Informed Consent Statute, Sec. 74.106 of the Texas Civil Practice and Remedies Code.</p>
<p id="faq11"> <strong><em>11. What are the provider’s responsibilities if the proposed medical treatment or surgical procedure is not on List A or List B?</em></strong> The Informed Consent Statute provides that if a medical treatment or surgical procedure is performed for which the Panel has not make a determination as to the duty of disclosure of risks and hazards, the provider is “under the duty otherwise imposed by law.” Informed Consent Statute, Sec. 74.106(b) of the Texas Civil Practice and Remedies Code.  The Texas Supreme Court has held that the duty is as stated in Section 74.101 of the Informed Consent Statute:  the provider must disclose the risks and hazards that could influence a reasonable person in making a decision to give or withhold consent.  <i>Barclay v. Campbell</i>, 704 S.W.2d 8 (Tex. 1986); <i>Petersen v. Shields</i>, 652 S.W.2d 929 (Tex. 1983).</p>
<hr/>
<h3>The Panel’s Consent Forms</h3>
<p id="faq12"> <strong><em>12. Does the Panel publish a consent form to be used for the medical treatments and surgical procedures on List A?</em></strong>  The statute requires the Panel to establish the “form” in which the disclosure of risks and hazards for treatments and procedures identified by the Panel must be made.  Informed Consent Statute, Sec. 74.103(b) of the Texas Civil Practice and Remedies Code.  The consent forms established by the Panel are set out in the Panel’s regulations at 25 Texas Administrative Code Sections 601.4, 601.5, 601.8, and 601.9.</p>
<p><a href="/hfp/tmdpFAQ.shtm#TopQues">To Questions</a></p>
<p id="faq13"> <strong><em>13. What consent forms have been established by the Panel?  </em></strong> There are four separate consent forms:<br />Sec. 601.4     Disclosure and Consent - Medical and Surgical Procedures<br />Sec. 601.5     Disclosure and Consent for Radiation Therapy<a href="http://info.sos.state.tx.us/fids/200504268-3.html"><br /></a>Sec. 601.8     Disclosure and Consent for Hysterectomy<br />Sec. 601.9     Disclosure and Consent for Anesthesia and/or Perioperative Pain   Management (Analgesia)<br />Each form is listed on our <a href="http://www.dshs.state.tx.us/hfp/apps.shtm#disclosureandconsent">Applications/Forms</a> page.   The consent forms also are available in Spanish.</p>
<hr/>
<h3>Uses or Changes to the Panel’s Consent Form</h3>
<p id="faq14"> <strong><em>14. Is the provider required to use the consent forms promulgated by the Panel?</em></strong> If a provider wants to be able to assert the rebuttable presumption that he or she has complied with the duty of disclosure of risks and hazards established by the Informed Consent Statute (see discussion above under “Legal Protections”), the provider must make the disclosure “in the form and to the degree required by the disclosure panel under Section 74.103.”  Informed Consent Statute, Sec. 74.105 of the Texas Civil Practice and Remedies Code.  Therefore, in obtaining consent for a List A procedure, the provider should disclose the risks and hazards identified by the Panel for that List A procedure and use the Panel’s consent form. </p>
<p id="faq15"> <strong><em>15. Can a provider use the Panel’s Disclosure and Consent---Medical and Surgical Procedures form to obtain consent to perform a hysterectomy?</em></strong> The Informed Consent Statute provides that the form specifically established for hysterectomy (25 Texas Administrative Code Sec. 601.8) is to be used for that procedure, unless the hysterectomy must be performed in a life-threatening situation in which the physician determines obtaining informed consent is not reasonably possible.  Informed Consent Statute, Sec. 74.107 of the Texas Civil Practice and Remedies Code.</p>
<p id="faq16"> <strong><em>16. Since the statutory consent form includes consent to the administration of blood, which is a List A procedure with identified risks, can the provider preprint those risks on the Panel’s form under the section dealing with consent to blood?</em></strong> Yes.  As long as the risks listed for the administration of blood include those identified by the Panel, their inclusion should not jeopardize the availability of the legal protections afforded by the Informed Consent Statute.</p>
<p><a href="/hfp/tmdpFAQ.shtm#TopQues">To Questions</a></p>
<p id="faq17"> <strong><em>17. Does a provider need to use the Panel’s consent form when obtaining consent to a medical treatment or surgical procedure that is on List B (meaning the Panel has determined that disclosure of specific risks and hazards is not required)?  </em></strong> No, the provider does not need to use the Panel’s consent form in this instance because there is no specific disclosure required.  In obtaining consent for the treatment or procedure, however, the Panel recommends that the provider use its consent form.</p>
<p id="faq18"> <strong><em>18. If the provider uses the Panel’s Disclosure and Consent---Medical and Surgical Procedures form to obtain consent for a List B procedure, what would the provider put on the form under the section for the listing of risks since the Panel has determined there are no specific risks that need to be disclosed?</em></strong> Neither the Informed Consent Statute nor the Panel requires that any specific information be placed on the consent form when used for a List B procedure (or even that the Panel’s form be used).  The provider is responsible for deciding what information to put on the consent form, but may want to provide under the section for listing of risks a statement to the effect that “no disclosure of specific risks is required by the Texas Medical Disclosure Panel,” rather than leaving blank spaces on the form.</p>
<p id="faq19"> <strong><em>19. What if the provider believes there are risks that should be disclosed for a List B procedure?</em></strong>  This is not addressed by the Informed Consent Statute and the provider may list those risks on the Panel’s consent form in the appropriate space.  This information could be listed by itself or along with a statement to the effect that no disclosure of specific risks is required by the Panel.</p>
<p id="faq20"> <strong><em>20. What if a provider believes that there are additional risks and hazards associated with a List A procedure that should be disclosed beyond those identified by the Panel?Can the provider add those risks to the risks identified by the Panel?  </em></strong> Nothing in the Informed Consent Statute prohibits a provider from listing additional risks that he or she has identified along with the Panel’s listing of specific risks and hazards for the List A procedure.  Those additional risks may be listed in the appropriate space on the Panel’s consent form after the listing of the risks identified by the Panel and should not conflict with the information already on the Panel’s form.</p>
<p id="faq21"> <strong><em>21. May a provider add information or text to the Panel’s consent forms other than risks and hazards, such as consent to photographs?  </em></strong> The Informed Consent Statute does not prohibit the inclusion of additional information on the consent form.  There is always the possibility that an alteration of the form, depending on the nature and extent of the alteration, may jeopardize the legal protections that are afforded by the Informed Consent Statute for using the Panel’s form.  Any addition should be consistent with the existing text of the Panel’s form.</p>
<p id="faq22"> <strong><em>22. Can the provider delete information or text from the Panel’s consent forms?  </em></strong> Deleting information or text from the Panel’s consent form may jeopardize the legal protections available under the statute.  Rather than deleting information from the Panel’s consent form, if there is information that is not applicable to a particular patient or treatment or procedure, the provider and patient may want to consider lining through that information and initialing the line through.</p>
<p><a href="/hfp/tmdpFAQ.shtm#TopQues"><strong>To Questions</strong></a></p>
<p id="faq23"> <strong><em>23. Can the information in the Panel’s consent form be incorporated into the provider’s own consent form?  </em></strong> This is not addressed by the Informed Consent Statute or the Panel.  Although it may be acceptable to a court if challenged, modification of the Panel’s consent forms or of the recommended disclosures may jeopardize the legal protections under the Informed Consent Statute.  The provider should consult with legal counsel in this regard. </p>
<p id="faq24"> <strong><em>24. Can more than one List A procedure be included on a single Disclosure and Consent – Medical and Surgical Procedures form or does the provider need to use a separate form for each List A procedure?  </em></strong> As long as the names of each List A procedure and the risks for each of those procedures are included on the form, one Disclosure and Consent – Medical and Surgical Procedures form can be used to obtain consent for more than one procedure.  However, procedures should not be added to the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) form.</p>
<hr/>
<h3>ECT</h3>
<p id="faq25"> <strong><em>25. What does the Panel require for consent to electroconvulsive therapy or ECT?</em></strong> The Panel has determined that electroconvulsive therapy or ECT is a List A procedure and identified those risks and hazards that should be disclosed using the Panel’s Disclosure and Consent---Medical and Surgical Procedures form. The anesthesia used in conjunction with administration of the ECT also may be a List A procedure, depending on the type of anesthesia. The Texas Department of State Health Services has published a standard consent form for ECT (see, 25 Texas Administrative Code Sec. 601.7). A provider may use both the DSHS consent form for the ECT and the Panel’s Disclosure and Consent---Medical and Surgical Procedures form and Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) form. The Panel also has provided by regulation that the provider may use the DSHS form as long as that form contains the specific risks and hazards for ECT as the Panel has identified. In this case, the provider would still need to use the Panel’s Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) form if anesthesia is being administered.</p>
<hr/>
<h3>Other</h3>
<p id="faq26"> <strong><em>26. How long is the consent form valid after having been signed?  </em></strong> This is not addressed by the Informed Consent Statute.</p>
<p id="faq27"> <strong><em>27. Is the provider performing the medical treatment or surgical procedure required to obtain the consent or can the provider assign the responsibility to another individual?  </em></strong> The Informed Consent Statute does not address this issue.</p>
<p id="faq28"> <strong><em>28. Who is responsible to complete the consent form, i.e., fill in the blanks on the form?  </em></strong> The Informed Consent Statute addresses disclosure involved in “medical care or surgical procedures <em>rendered</em> by the physician or health care provider” (emphasis added).  Case law places the responsibility for obtaining informed consent with the physician or health care providerrenderingthe medical care or surgical procedure.  The Informed Consent Statute does not address who is responsible to insert the information on the Panel’s consent forms.</p>
<p id="faq29"> <strong><em>29. Whose address information is intended to be inserted at the end of the consent forms?  </em></strong> The name and address of the witness.</p>
<p id="faq30"> <strong><em>30. How do providers obtain the lists and consent forms?  </em></strong> The List A and List B medical treatments and surgical procedures are located on our <a href="/hfp/tmdp-rules.aspx">Rules/Regulations</a> page and the consent forms may be obtained from our <a href="http://www.dshs.state.tx.us/hfp/apps.shtm#disclosureandconsent">Applications/Forms</a> page. </p>
<p id="faq31"> <strong><em>31. How do providers learn of changes by the Panel or procedures that are added to the lists?  </em></strong> These are published in the Texas Register, which can be accessed at the Secretary of State website under <a href="http://texreg.sos.state.tx.us/public/readtac$ext.ViewTAC?tac_view=4&amp;ti=25&amp;pt=7&amp;ch=601&amp;rl=Y">25 Texas Administrative Code Part 7 Sections 601.1 to 601.9</a>. Once enacted, the changes are incorporated to the documents available on the Texas Department of State Health Services’ web site. </p>
<p id="faq32"> <strong><em>32. What is the relationship between the Panel and the Texas Department of State Health Services?  </em></strong> The Panel is entirely separate from the Texas Department of State Health Services, but the staff of the Texas Department of State Health Services’, Facility Licensing Group provides administrative support for the Panel.</p>
<p><strong><a href="/hfp/tmdpFAQ.shtm#TopQues">To Questions</a></strong></p>
<hr/>
<h3>Recent Specific Questions</h3>
<p id="faq33"> <strong><em>33. Under List A procedures, (b) Cardiovascular system, several procedures include the following as a risk:  “All associated risks as listed under paragraph (2)(B) of this subsection.”  What is the provider supposed to put on the consent form for these procedures?</em> </strong> Paragraph (2)(B) refers to the procedure “Angiography (inclusive of aortography, arteriography, venography) – Injection of contrast material into blood vessels.”  For procedures with the cross reference to paragraph (2)(B), the provider should list the risks under “Angiography (inclusive of aortography, arteriography, venography) – Injection of contrast material into blood vessels” as well as those risks under the procedure being performed.  The exception would be the three risks under paragraph (2)(B) that are limited to certain types of procedures:  </p>
<p>(v)  Stroke and/or seizure (for procedures involving blood vessels supplying the spine, arm, neck or head).<br />(vi)  Contrast –related, temporary blindness or memory loss (for studies of the blood vessels of the brain).<br />(vii) Paralysis (inability to move) and inflammation of nerves (for procedures involving blood vessels supplying the spine).</p>
<p>If the procedure being performed is not of the type described in the parentheses after each of the three risks (v), (vi), and (vii), those risks would not be listed.</p>
<p id="faq34"> <strong><em>34. <a class="bookmark" title="faq35" name="faq35"></a>List A, (n) Radiology, includes “Procedures utilizing prolonged fluoroscopy” as a List A procedure.  What constitutes “prolonged fluoroscopy”?</em></strong>  What constitutes prolonged fluoroscopy must be determined by the provider since there are several variables to consider and the determination may vary by patient.</p>
<hr/>
<h3>Separate Anesthesia and/or Perioperative Pain Management (Analgesia) Consent Form</h3>
<p id="faq35"> <strong><em>35. Why did the Panel develop a separate consent form for anesthesia and/or perioperative pain management (anesthesia)?</em>   </strong> The Panel consulted with several sources on the benefits and limitations of a separate consent form, including the Texas Society of Anesthesiologists.  The prior method of addressing anesthesia in the Disclosure and Consent – Medical and Surgical Procedures and Disclosure and Consent for Hysterectomy did not allow for designation of the identity of the anesthesia provider, information which the Panel determined would be in the patient’s interests.  A separate consent form also emphasizes the separate responsibilities of the anesthesia provider as compared to the operating practitioner.</p>
<p id="faq36"> <strong><em>36. How is the separate anesthesia consent form intended to be used?</em> </strong> The anesthesia consent form is intended for use when anesthesia or analgesia is administered in conjunction with other procedures.  If anesthesia or perioperative pain management is being provided in conjunction with another List A procedure, then the patient would be presented with both the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) form for the anesthesia and the Disclosure and Consent – Medical and Surgical Procedures for the operative procedure (or the Disclosure and Consent for Hysterectomy form in the case of a hysterectomy).</p>
<p id="faq37"> <strong><em>37. What form should the provider use if the provider is administering anesthesia or analgesia solely for purposes of pain management, and not in conjunction with another procedure?</em> </strong> If the pain management procedure is a List A procedure, such as one listed under Section 601.2(t), the provider would use the Panel’s Disclosure and Consent – Medical and Surgical Procedures consent form.  </p>
<p id="faq38"> <strong><em>38. If the same provider is performing a List A procedure and administering List A anesthesia or analgesia, can the provider use only the Disclosure and Consent – Medical and Surgical Procedures form to obtain consent for both the procedure and the anesthesia or analgesia?</em>  </strong> If the provider wants to be able to assert the rebuttable presumption that he or she has complied with the duty of disclosure of risks and hazards established by the Informed Consent Statute (see discussion above under “Legal Protections”), then both forms should be used.  The only exception would be if the List A anesthesia or analgesia is going to be administered solely for purposes of a List A pain management procedure, then only the Disclosure and Consent – Medical and Surgical Procedures form should be used. <i>See FAQ #37 above.</i></p>
<p id="faq39"> <strong><em>39. Can dentists use the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia) when administering nitrous oxide?</em>  </strong> Any provider administering List A anesthesia (unless it is being performed solely for purposes of pain management – see FAQ#37 above) should use the anesthesia form if the provider wants the benefit of the rebuttable presumption of having complied with the duty of disclosure of risks and hazards established by the Informed Consent Statute (see discussion above under “Legal Protections”).  Nitrous oxide is considered Monitored Anesthesia Care (MAC) and is a List A anesthesia covered by the Anesthesia and/or Perioperative Pain Management (Analgesia) form.</p>
<p><strong><a href="/hfp/tmdpFAQ.shtm#TopQues">To Questions</a></strong></p>
<p id="faq40"> <strong><em>40. The Disclosure and Consent – Medical and Surgical Procedures form, and the Disclosure and Consent for Hysterectomy form (procedure consent forms), each contain information on anesthesia.  Won’t patients be confused by the references to anesthesia on these procedure consent forms when also presented with the separate Anesthesia and/or Perioperative Pain Management (Analgesia) consent form for anesthesia (anesthesia consent form)?</em> </strong> The Panel is going to review whether revisions are needed to the two procedure consent forms with regard to references to anesthesia.  In the interim, the Panel suggests that when using either of these two procedure consent forms along with the anesthesia consent form, the provider and patient may want to line through and initial the information that deals with anesthesia in the procedure consent form being used so that anesthesia is addressed only on the anesthesia consent form.  </p>
<p id="faq41"> <strong><em>41. Can more than one type of anesthesia or analgesia be checked on the Disclosure and Consent for Anesthesia and/or Perioperative Pain Management (Analgesia)?</em> </strong> Yes.</p>
<p id="faq42"> <strong><em>42. If the provider already has an anesthesia consent form, can the provider modify that form to include the information from the Panel’s anesthesia consent form and keep using its existing form?</em></strong>  If a provider wants to be able to assert the rebuttable presumption that he or she has complied with the duty of disclosure of risks and hazards established by the Informed Consent Statute, the provider must make the disclosure “in the form and to the degree required by the disclosure panel under Section 74.103.”  Informed Consent Statute, Sec. 74.105.  Therefore, in obtaining consent for a List A procedure (of which anesthesia is one), the provider should disclose the risks and hazards identified by the Panel for that List A procedure and use the Panel’s consent form (in this case the Panel’s anesthesia consent form).  The Informed Consent Statute does not prohibit the inclusion of additional information on the consent form.  There is always the possibility that an alteration of the form, depending on the nature and extent of the alteration, may jeopardize the legal protections that are afforded by the Informed Consent Statute for using the Panel’s form.  <i>See FAQs #14 and 21 above.</i></p>
<p id="faq43"> <strong><em>43. The Disclosure and Consent – Medical and Surgical Procedures form only references a “physician,” but a health care professional who is not a physician may be using the consent form to obtain consent.  Can the health care professional performing the medical or surgical procedure change the term “physician” to the correct discipline?</strong>  As discussed under FAQ #21, the Informed Consent Statute does not prohibit the inclusion of additional information on the consent form.  There is always the possibility that an alteration of the form, depending on the nature and extent of the alteration, may jeopardize the legal protections that are afforded by the Informed Consent Statute for using the Panel’s form; therefore, any addition should be consistent with the existing text of the Panel’s form.  When the health care professional performing the medical or surgical procedure is not a physician, the Panel believes it is appropriate to change the reference to “physician” on the consent form to the correct discipline (e.g., dentist, oral and maxillofacial surgeon).</em></p>
<p><a href="/hfp/tmdpFAQ.shtm#TopQues"><strong>To Questions</strong></a></p>
<?php include '../../includes/footer.html' ?>					