<?php
	$array_seafood_pdf2_fishconsumptionadvisorybannews = array(
	"20230"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-11_PR_CaddoL.pdf",
	"20231"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-12_PR_TBR_SRR_BAS_CDL_BCC.pdf",
	"20232"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-13_PR_NechesR.pdf",
	"20233"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-14_PR_Gulf.pdf",
	"20234"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-15_PR_BrazosR.pdf",
	"20235"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-16_PR_PruittL.pdf",
	"20236"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-18_PR_WorthL.pdf",
	"20237"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-19_PR_Arroyo.pdf",
	"20238"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-20_PR_HSC.pdf",
	"20239"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-22_PR_DaingerfieldL.pdf",
	"20240"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-23_PR_RatcliffL.pdf",
	"20241"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-24_PR_MeredithL.pdf",
	"20242"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-3_PR_HSCUGB.pdf",
	"20243"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-35_signed.pdf",
	"20244"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-36_signed.pdf",
	"51744"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-38_LakeIsabell_signed.pdf",
	"59312"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-38_LakeIsabell_signed(2).pdf",
	"20245"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-4_PR_MCR_BBR_WEL.pdf",
	"59313"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-40AlanHenry.pdf",
	"59314"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-41_NechesR.pdf",
	"8589936145"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-45_signed.pdf.pdf",
	"20246"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-5_PR_DonnaR_Arroyo.pdf",
	"8589985025"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-51_signed.pdf",
	"8589986955"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-52-signed.pdf",
	"20247"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-6_PR_DonnaR_Arroyo.pdf",
	"20248"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/ADV-7_PR_ClearCr.pdf",
	"20249"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-1_PR_LavacaB.pdf",
	"20250"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-10_PR_ComoL-FosdicL.pdf",
	"20251"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-11_PR_EchoL.pdf",
	"20252"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-12_PR_MountainCRL.pdf",
	"20253"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-13_PR_LavacaB.pdf",
	"20254"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-14_PR_TrinityR.pdf",
	"20255"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-2_PR_TrinityR.pdf",
	"20256"	=>	"http://www.dshs.state.tx.us/seafood/PDF2/FishConsumptionAdvisoryBaNNews/AL-9_PR_DonnaR.pdf"
	);
?>