<?php
	$array_elp = array(
		"8589990804"	=>	"http://www.dshs.state.tx.us/elp/pdf/2014-15_ExamCalendar.pdf",
		"61763"	=>	"http://www.dshs.state.tx.us/elp/pdf/AnabolicSteroidAmendment_signed.pdf",
		"8589968256"	=>	"http://www.dshs.state.tx.us/elp/pdf/CertCredRepl.pdf",
		"17243"	=>	"http://www.dshs.state.tx.us/elp/pdf/certreq.pdf",
		"54944"	=>	"http://www.dshs.state.tx.us/elp/pdf/CurrentLeadEnforcementActions.pdf",
		"61761"	=>	"http://www.dshs.state.tx.us/elp/pdf/DMDEnfActs.pdf",
		"61762"	=>	"http://www.dshs.state.tx.us/elp/pdf/DrugManfEnfActs.pdf",
		"17246"	=>	"http://www.dshs.state.tx.us/elp/pdf/DSHSregphilosophy.pdf",
		"8589968261"	=>	"http://www.dshs.state.tx.us/elp/pdf/Firm.pdf",
		"17248"	=>	"http://www.dshs.state.tx.us/elp/pdf/HUDRehabProjects.pdf",
		"17253"	=>	"http://www.dshs.state.tx.us/elp/pdf/LeadAbatementSupervisorApp.pdf",
		"17255"	=>	"http://www.dshs.state.tx.us/elp/pdf/LeadAbatementWorkerApp.pdf",
		"8589951118"	=>	"http://www.dshs.state.tx.us/elp/pdf/LeadExamReg.pdf",
		"17259"	=>	"http://www.dshs.state.tx.us/elp/pdf/LeadInspectorApp.pdf",
		"17262"	=>	"http://www.dshs.state.tx.us/elp/pdf/leadrules.pdf",
		"8589968392"	=>	"http://www.dshs.state.tx.us/elp/pdf/LeadTrainingProvider.pdf",
		"17264"	=>	"http://www.dshs.state.tx.us/elp/pdf/LeadTrainingProviderApp.pdf",
		"17265"	=>	"http://www.dshs.state.tx.us/elp/pdf/notification.pdf",
		"8589968262"	=>	"http://www.dshs.state.tx.us/elp/pdf/ProjectDesigner.pdf",
		"8589968259"	=>	"http://www.dshs.state.tx.us/elp/pdf/ProjectDesignerReciprocal.pdf",
		"61759"	=>	"http://www.dshs.state.tx.us/elp/pdf/RenovationRRP.pdf",
		"8589968260"	=>	"http://www.dshs.state.tx.us/elp/pdf/RiskAssessor.pdf",
		"8589968258"	=>	"http://www.dshs.state.tx.us/elp/pdf/RiskAssessorReciprocal.pdf",
		"61765"	=>	"http://www.dshs.state.tx.us/elp/pdf/SCHEDULES_2010.pdf",
		"17269"	=>	"http://www.dshs.state.tx.us/elp/pdf/studyguide.pdf",
		"8589968257"	=>	"http://www.dshs.state.tx.us/elp/pdf/SupervisorReciprocal.pdf",
		"61764"	=>	"http://www.dshs.state.tx.us/elp/pdf/TanningClientHistory.pdf",
		"61767"	=>	"http://www.dshs.state.tx.us/elp/pdf/TanningSanitizerTestLog.pdf",
		"17271"	=>	"http://www.dshs.state.tx.us/elp/pdf/TELRRSUM.pdf",
		"61766"	=>	"http://www.dshs.state.tx.us/elp/pdf/TMB-ADVISORY-STATEMENT.pdf",
		"17272"	=>	"http://www.dshs.state.tx.us/elp/pdf/Trncredrepl.pdf",
		"8589968255"	=>	"http://www.dshs.state.tx.us/elp/pdf/WorkerReciprocal.pdf"
	);
?>