<?php
	$array_ems_conference = array(
		"8589986160"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/AwardsNominationForm.pdf",
		"54449"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/BJ-CoorCourse-EvaDoc-Rev.pdf",
		"17503"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/CALSCourseContent.pdf",
		"17515"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/ccrequir.pdf",
		"8589971935"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/CoordCourseAgenda.pdf",
		"8589993500"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/CoordinatorCourseApplication.pdf",
		"8589982493"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/DC_CoorCourse_Evaluation.pdf",
		"8589936478"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/DC-Equivalency.pdf",
		"54451"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/DC-ImprovingYourExams.pdf",
		"54511"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/DocumentingInfoRequiredforCoorCourse.pdf",
		"8589936435"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Education_Rules_2010.pdf",
		"8589972360"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/EMSCoordinatorWorkshop.pdf",
		"17727"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/EMSCourseCoordinatorSurvey-9-19-08.pdf",
		"54514"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Example-Affiliation-D4.pdf",
		"54515"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Example-ClinIntern-D5.pdf",
		"54517"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Example-CoordApp2010.pdf",
		"54518"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Example-Eval-D3.pdf",
		"54519"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Example-InstHrs-D2.pdf",
		"54520"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Example-SelfLtr-Sec4.pdf",
		"8589959964"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Hart_ApplyingForAProgram.pdf",
		"8589959866"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Hart_EducationRules2011.pdf",
		"8589959965"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Hart_SettingUpYourPrg.pdf",
		"8589982149"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/JM_CoordinatorAdvisoryCommittee.pdf",
		"8589982150"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/JM_EthicsEMSEduc.pdf",
		"8589971573"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/MDAgreement.pdf",
		"8589971574"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/MDJobDescription.pdf",
		"8589971575"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/MedicalDirection.pdf",
		"8589982339"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/http://wwwstage.dshs.state.tx.us/assetmanagement/images/WinZip.pngPolicies.pdf",
		"8589982497"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/PoorProgIndicators.pdf",
		"8589971434"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/RoleOfEMSCoordinator.pdf",
		"8589959978"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/Rutherford_SelAndDevInstructors.pdf",
		"8589981665"	=>	"http://www.dshs.state.tx.us/emstraumasystems/conference/pdf/SelfStudyandSiteVisit.pdf"
	);
?>