<?php
	$array_seafood_mapspdf_advisorymaps = array(
	"20174"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-30CanyonLakeMap.pdf",
	"20175"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-36MadisonvilleLakeMap.pdf",
	"51739"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-37_ClearCreekMap.pdf",
	"51743"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-38_LakeIsabell_Map.pdf",
	"59262"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-43-Trinity-River-map.pdf",
	"8589935669"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-44MountainCreekLakeMap.pdf",
	"8589961761"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-46-Sabine-Lake-Map.pdf",
	"8589976915"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-48_NWGOM_Map.pdf",
	"8589985026"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-51-BA-Steinhagen-Reservoir-Map.pdf",
	"8589985021"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-51-Neches-River-Map.pdf",
	"8589985022"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-51-Sam-Rayburn-Reservoir-Map.pdf",
	"8589986954"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ADV-52-GalvestonBay-Map.pdf",
	"8589946768"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/AlanHenryReservoirADV-40map.pdf",
	"20176"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/BASteinhagenReservior.pdf",
	"20177"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/BigCypressCaddoLK.pdf",
	"20178"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/EllisonCrkRes.pdf",
	"51742"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/GalvestonBayHSC1_28_2009.pdf",
	"8589978703"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/GalvestonBay-EstuaryMap-1.pdf",
	"8589978704"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/GalvestonBay-EstuaryMap-2.pdf",
	"20179"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/LakeDaingerfield.pdf",
	"20180"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/LakeKimball.pdf",
	"20181"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/LakeMeredith.pdf",
	"20182"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/LakeWorth.pdf",
	"8589946769"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/LakeWorthADV-45.pdf",
	"20183"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/LeonCreek.pdf",
	"59263"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/Leon-Creek-ADV-42-map.pdf",
	"8589946771"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/NechesRiverADV-41map.pdf",
	"20184"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/PruittBlk.pdf",
	"20185"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/Ratcliff.pdf",
	"20186"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/SamRayburn.pdf",
	"20187"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/ToledoBend.pdf",
	"20188"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/TrinityRiver_Advise.pdf",
	"51745"	=>	"http://www.dshs.state.tx.us/seafood/MapsPDF/AdvisoryMaps/VillageCreek.pdf"
	);
?>