<?php
	$title= "Harmful Algal Blooms - Seafood and Aquatic Life" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/seafood_menu.html'; 
?>

<p>Harmful algal blooms (HAB's) are naturally occurring concentrations of microscopic algae that are found in waters worldwide. Of the 5000+ species of marine plankton that exist worldwide, about 2% are known to be harmful or toxic. Blooms of harmful algae can have large and varied impacts on marine ecosystems, depending on the species involved, the environment where they are found, and the mode of transport by which they exert harmful effects. Harmful algal blooms have been observed to cause adverse effects to a wide variety of aquatic organisms, most notably marine mammals, sea turtles, seabirds and finfish. The impacts of HAB toxins on these groups can include harmful changes to their developmental, immunological, neurological, or reproductive capacities.</p>

<hr/>
<h2>Karenia brevis (red tide)</h2>

<p><em>Karenia brevis</em> is a planktonic marine dinoflagellate. When K. brevis experiences explosive growth the water takes on a reddish discoloration; thus the name, <strong>red tide</strong>, is often used to describe these blooms. This HAB produces a group of toxins called brevetoxins. These toxins are lethal to fish and can cause respiratory problems for persons in the area of the bloom and neurotoxic shellfish poisoning (NSP) in persons who consume molluscan shellfish (oysters, clams and mussels) that have been feeding on this algal species. Because molluscan shellfish filter algae as they feed, they can become toxic when K. brevis is present at concentrations below those that cause discoloration of the water. </p>

<h3>Which Seafood Are Safe to Eat When K. brevis is Present </h3>
<p>Since brevetoxins are not concentrated by fish, shrimp, or crabs, these forms of seafood are safe to eat as long as they are caught alive and act normally when caught. <strong>No form of fish or shellfish that has washed ashore sick or dead (or was found floating "belly up" in the water) should ever be eaten.</strong> Also, any molluscan shellfish (oysters, clams, mussels and scallops) legally available in markets and restaurants also should be safe to eat since they would have been harvested from areas that were not affected by the bloom. </p>

<h3>Neurotoxic Shellfish Poisoning (NSP) </h3>
<p><em>K. brevis</em> produces at least two major heat-stable, lipid-soluble toxins known as brevetoxins A and B. These toxins appear to affect sodium transport in the autonomic nervous system and cause inhibition of neuromuscular transmission in skeletal muscle. Many species of fish are sensitive to brevetoxins and effectively "drown" in red tide water’s when the toxin causes paralysis of the gills. While fish are easily killed by high brevetoxin levels, oysters, clams, and mussels are not susceptible to these toxins and they may appear perfectly healthy. However, when these shellfish feed for a time in waters with high concentrations of K. brevis, they accumulate brevetoxins in their body tissues, making them toxic to humans who ingest them. The toxin is only slowly cleared from shellfish after the red tide disappears. Consequently, consumption of oysters, clams, or mussels caught during (or even months after) a red tide can cause neurotoxic shellfish poisoning (NSP) in humans. Any bays in Texas affected by a K. brevis bloom would be closed to harvesting by the Texas Department of State Health Services (DSHS). <strong>Cooking will not eliminate the toxin; therefore cooking will not make contaminated seafood safe</strong>.</p>

<h3>Characteristic Symptoms of NSP: Gastrointestinal and Neurologic </h3>
<p>There is currently no specific diagnostic laboratory test to identify NSP, so the diagnosis is based on clinical evaluation of cases with relevant exposures. Onset of NSP symptoms usually occurs within three hours of ingestion of contaminated shellfish (range 15 minutes to 18 hours after exposure). Initial complaints typically include abdominal pain, nausea, vomiting, and diarrhea accompanied by progressive paresthesia, which first affect the area around the mouth and later the pharynx, trunk, and limbs. Other common symptoms include vertigo, malaise, generalized muscle weakness, ataxia, incoordination, chills, headache, and myalgia. A reversal of hot and cold temperature sensation (similar to that seen in ciguatera poisoning) has also been reported. In cases of severe poisoning, dilated pupils, bradycardia, and (rarely) convulsions requiring respiratory support may also be seen. </p>

<h3>Differential Diagnosis </h3>
<p>To some extent, the geographical origin of the affected shellfish can help identify the probable toxigenic dinoflagellate. <em>Alexandrium catenella</em> (formerly <em>Gonyaulax catenella</em>) is the leading toxigenic dinoflagellate found along the Pacific coast of North America, while <em>Alexandrium tamarense-excavatum</em> (formerly <em>Gonyaulax tamarensis</em>) primarily affects the northern Atlantic coast of North America. K. brevis is the dinoflagellate most often responsible for red tides in the Gulf of Mexico and along the southern Atlantic coast of North America. NSP is a relatively mild illness and should not be confused with the much more serious condition known as paralytic shellfish poisoning (PSP). PSP is caused by a saxitoxin elaborated by one of the <em>Alexandrium</em> species of dinoflagellates. The symptoms of PSP are very similar to those of NSP, but the neurotoxic effects of PSP can progress rapidly to respiratory paralysis and death if the patient is not placed on a respirator.</p>

<h3>Treatment for NSP </h3>
<p>Since NSP is a relatively innocuous form of shellfish poisoning, and since no specific antitoxin is available, treatment is supportive in nature. Patients should be monitored closely for hydration status, particularly if the signs and symptoms include a significant amount of vomiting or diarrhea. Patients who have ingested large quantities of the affected shellfish and who are experiencing more severe symptoms may require brief hospitalization for observation. In general, the illness is self-limiting; symptoms usually subside in less than 24 hours with supportive therapy.</p>

<h3>Other Symptoms Associated with <em>K. brevis</em> Blooms </h3>
<p>Classically, NSP produces gastrointestinal and neurologic symptoms associated with ingestion of shellfish containing high levels of brevetoxins. However, some individuals have experienced respiratory, mucous membrane, and skin irritation simply by walking on the beach during this and other <em>K. brevis</em> red tides. On disruption, <em>Karenia</em> organisms release cellular endotoxins into the surrounding water. Wind and surf action produce a fine aerosol that generally travels only a short distance from the beach. Thus, in areas with a great deal of surf action, airborne exposure to the toxins can be a problem for some individuals</p>

<p>Exposed individuals frequently report an acute but rapidly reversible syndrome consisting of conjunctival irritation, rhinorrhea, sneezing, cough, and (rarely) respiratory distress similar to an asthma attack. Persons swimming or wading in <em>K. brevis</em> red tides may experience eye and skin irritation accompanied by redness and itching. Following short-term exposures, the symptoms usually subside when the individual leaves the immediate vicinity of the beach. Prolonged exposure, however, can cause symptoms that linger for hours or days after the person leaves the affected area. <strong>Consequently, DSHS recommends that visitors to the affected areas avoid swimming or wading in red tide waters</strong>.</p>

<hr/>
<h2>Dinophysis</h2>
<p><em>Dinophysis ovum</em> is a marine dinoflagellate that produces okadaic acid (OA) and causes diarrhetic shellfish poisoning (DSP) when concentrated in the intestinal cavity of molluscan shellfish. DSP toxins are heat stable. <strong>Cooking will not eliminate the toxin; therefore cooking will not make contaminated seafood safe</strong>.</p>

<p>DSP is a self-limiting diarrheal disease with no evidence of neurotoxicity. There have been no fatal cases of DSP reported. Although, diarrhea is the most common symptom, nausea and vomiting are also reported. Onset can occur between 30 minutes to 12 hours of consumption and complete recovery is seen within 3 days. Approved laboratory methods for identification and quantification of OA or <em>Dinophysis</em> toxins are mouse bioassay or direct detection using high performance liquid chromatography, electrospray ionization, multiple reactions monitoring, and mass spectrometry (HPLC/ESI/MRM/MS). </p>

<p>Most cases of DSP have been reported from the consumption of mussels, but oysters have also been implicated.  Recently, DSP has been reported from oysters harvested from the State of Washington and British Columbia.</p>

<hr/>
<h2>Ciguatera </h2>
<p>Ciguatera fish poisoning is caused by ciguatoxins produced by the dinoflagellate <em>Gambierdiscus toxicus</em>. During blooms of <em>G. toxicus</em>, this single-celled organism attaches to marine algae which are eaten by various herbivorous fish. These fish are then eaten by carnivorous fish, and the ciguatoxin is thereby passed up the food chain into a variety of larger tropical reef fish such as red snapper, barracuda, amberjack, and grouper. Humans can be affected if they catch and eat any fish that have accumulated large amounts of the toxin. </p>

<h3>Ciguatera Advisory Issued for Fish Taken Near Flower Gardens (Coral Reef)</h3>
<p>The U.S. Food and Drug Administration in conjunction with the Texas Department of State Health Services is advising recreational fishermen and other consumers not to eat the fish from the Flower Garden Coral reef system located in Federal waters off the northern coast of Texas. The <strong>ciguatera toxin</strong> is produced by algae that grow on some coral. The Flower Garden is a coral reef system. The toxin accumulates in fish tissue along the natural food chain as smaller fish eat the algae and larger fish eat smaller fish. <strong>Cooking will not eliminate the toxin; therefore cooking will not make contaminated seafood safe</strong>.</p>

<p>The fish species covered in this advisory are marbled, gag, scamp and yellowfin grouper; blackfin and dog snapper; and hogfish caught within 10 miles of the Flower Garden. Also included are yellow, horse-eye and black jack; king mackerel; amberjack; and barracuda from within 50 miles of the sanctuary.</p>

<p>For more information about ciguatera please see the following article:<br/> <a title="FDA Advises Seafood Processors About Ciguatera Fish Poisoning in the Northern Gulf of Mexico" href="http://www.fda.gov/NewsEvents/Newsroom/PressAnnouncements/2008/ucm116851.htm">FDA Advises Seafood Processors About Ciguatera Fish Poisoning in the Northern Gulf of Mexico</a></p>



<?php include '/home/codio/workspace/includes/footer.html' ?>