<?php
	$title= "General Information on the Risk of Eating Fish - Seafood and Aquatic Life" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/seafood_menu.html'; 
?>

<hr/>
<h2>Table of Contents</h2>
<ul>
	<li><a title="Benefits and Risks of Consuming Fish and Crabs" href="#benefits">Benefits and Risks of Consuming Fish and Crabs</a></li>
	<li><a title="Fish Consumption by Children and Pregnant Women" href="#women-children">Fish Consumption by Children and Pregnant Women</a></li>
	<li><a title="Fish Consumption Guides and Documents" href="#guides">Fish Consumption Guides and Documents</a></li>
	<li><a title="Contaminants of Concern" href="#contaminants">Contaminants of Concern</a></li>
	<li><a title="Sources of Information" href="#sources">Sources of Information</a></li>
</ul>

<hr/>
<a class="bookmark" title="benefits" name="benefits"></a>
<h2>Benefits and Risks of Consuming Fish and Crabs</h2>
<p>Fish and shellfish are healthful foods that provide a diet high in protein and low in saturated fat and contain nutrients that are important for proper growth and development. Studies have shown that omega-3 fatty acids in fish may reduce the risk of heart disease and stroke and many doctors suggest that eating one to two fish meals each week is helpful in preventing heart disease. However, fish and shellfish can accumulate contaminants from the water in which they live or from the food they eat. These contaminants may accumulate to levels that can be harmful to people who eat fish or shellfish. </p>
<p><a title="Consumption advisories" href="/seafood/advisories-bans.aspx">Consumption advisories</a> are not intended to discourage people from eating fish or shellfish; they are intended to help people make informed decisions on whether they or their families should eat fish or shellfish from specific water bodies. Fish and shellfish consumption advisories recommend consumption guidelines for people based on potential human health risks. People should also use these guidelines to choose fish and shellfish species and water bodies that contain lower levels of contaminants.</p>

<hr/>
<a class="bookmark" title="women-children" name="women-children"></a>
<h2>Fish Consumption by Children and Pregnant Women</h2>
<p>The US Food and Drug Administration (FDA) recommends that young children and women who are pregnant or breastfeeding should eat 2-3 servings each week of fish from choices that are lower in mercury. Recent reports show that the nutritional value of fish is highly beneficial for the growth and development of infants and children. </p>
<p>Most fish commonly eaten, which include salmon, tuna (light canned), tilapia, cod, pollock, and catfish are lower in mercury. Fish types to avoid include tilefish from the Gulf of Mexico, shark, swordfish, and king mackerel.</p>
<p>For more information, please see the FDA page entitled: <a title="Fish: What Pregnant Women and Parents Should Know" href="http://www.fda.gov/Food/FoodborneIllnessContaminants/Metals/ucm393070.htm">Fish: What Pregnant Women and Parents Should Know</a></p>

<hr/>
<a class="bookmark" title="guides" name="guides"></a>
<h2>DSHS Fish Consumption Guides and Documents</h2>
<ul>
	<li><a title="Guide to Eating Texas Fish and Crabs 2009 Edition" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=51708">Guide to Eating Texas Fish and Crabs 2009 Edition</a> <span class="small">(PDF, 11.65MB)</span></li>
	<li><a title="Clean and Cook Fish Properly to Reduce Exposure" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=20226">Clean and Cook Fish Properly to Reduce Exposure</a> <span class="small">(PDF, 85KB)</span></li>
	<li><a title="Consumption Guidance for Purchased Fish" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=20228">Consumption Guidance for Purchased Fish</a> <span class="small">(PDF, 49KB)</span></li>
	<li><a title="Fish and Shellfish Nutrition Facts" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=20267">Fish and Shellfish Nutrition Facts</a> <span class="small">(PDF, 11KB)</span> </li>
	<li><a title="Mercury in Fish You Catch from Texas Waters" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=20265">Mercury in Fish You Catch from Texas Waters</a> <span class="small">(PDF, 136KB)</span> </li>
	<li><a title="Parasites in Fish" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=20269">Parasites in Fish</a> <span class="small">(PDF, 98KB)</span> </li>
</ul>

<hr/>
<a class="bookmark" title="contaminants" name="contaminants"></a>
<h2>Contaminants of Concern </h2>
<h3>Mercury </h3>
<p>Mercury is a naturally occurring element distributed throughout the environment by natural processes and human activities. Mercury is released into the air when rocks erode, soils decompose, and volcanoes erupt. However, 70% of the total annual mercury releases to the environment are from human activities. Most mercury releases to the air occur when people burn fossil fuels or incinerate solid waste. Other sources of environmental mercury include mining, smelting, chlor-alkali and cement production, and other industrial processes that use mercury. Mercury is also released to surface waters from pulp and paper mills, leather tanning, electroplating, chemical manufacturing, and wastewater treatment facilities. Airborne mercury is an indirect source of mercury, reaching surface waters and soils through precipitation. Mercury also enters surface waters through disturbed lake or river sediments (e.g. flooding, dredging). Sources of mercury in soil include fertilizers, fungicides, solid waste (e.g. batteries, electrical switches, thermometers, fluorescent light bulbs), municipal incinerator ash placed in landfills, and from application of sewage sludge to cropland. Microorganisms in the aquatic environment convert inorganic mercury to methyl mercury. This chemical change occurs more readily in acidic waters with high levels of organic matter. Methyl mercury accumulates in fish and is passed up the food chain: small fish eat methyl mercury in insects and microscopic animals; larger fish then eat methyl mercury in the smaller fish, and finally people consume methyl mercury when they eat larger fish. Fish at the top of the aquatic food chain (e.g. freshwater fishes largemouth bass, freshwater drum, gar, pike, and walleye and marine fishes such as king mackerel, shark, and swordfish) may contain methyl mercury levels 1 to 10 million times greater than those found in the surrounding water. Eating fish that contain methyl mercury can damage the brain and other parts of the nervous system. The greatest health risk from methyl mercury may be to the unborn baby. The unborn baby may be at particular risk of irreversible nervous system damage from mercury. Unborn babies, infants, and children are more sensitive to methyl mercury than adults because the brain and other parts of the nervous system are not completely developed. Symptoms of prolonged exposure to high levels of methyl mercury may include tingling of the skin, loss of coordination, visual and hearing impairment, and slurred speech. Infants and children exposed to very high levels of methyl mercury may exhibit neurological symptoms similar to those of cerebral palsy, but most of the neurological developmental effects of low level exposure to methyl mercury are, in all likelihood, subtle effects. </p>
<h3>Polychlorinated Biphenyls (PCBs) </h3>
<p>PCBs are synthetic (man-made) substances once used commercially in electrical transformers, carbonless copy papers, cutting oils, and hydraulic fluids. PCBs may also enter the environment through many other industrial and commercial uses. In 1979, The United States Environmental Protection Agency (EPA) banned the manufacture of PCBs in the United States. However, the EPA did not require removal of PCB-containing materials still in service at the time of the ban. Therefore, some materials remain in use today. The major source of environmental PCBs in the United States today is from ongoing use, storage, and disposal of products in landfills or improper disposal of products that contain PCBs. PCBs also may be released from sediments disturbed by flooding, dredging, and other activities. PCBs have been found in soil, ground and surface water, air, sediment, plants, and animals in all regions of the world. PCBs break down very slowly in the environment and accumulate in fatty tissue, skin, and internal organs of fish and other animals. Levels of PCBs in fish may be 2,000 to 1,000,000 times greater than levels in the surrounding water. The amount of PCBs found in fish varies with species, age, size, fat content, diet, and surface water concentrations. Larger, older fish will generally contain higher levels of PCBs than smaller, younger fish; fatty fish such as carp, buffalo, catfish, and spotted seatrout may contain higher levels of PCBs than lean fish such as largemouth bass, walleye, crappie, and red drum. Eating fish that contain PCBs may cause infants of women who have eaten many contaminated fish to have lower birth weights, delayed physical development, and learning difficulties. PCBs may affect the immune system, reproductive organs, skin, stomach, thyroid, kidney, and liver and may increase the risk of cancer. </p>
<h3>DDT, DDE, and DDD </h3>
<p>DDT is a chlorinated pesticide once widely used to control insects on agricultural crops and insects that carry diseases such as malaria and typhus. DDT enters the United States environment as a result of past use as an insecticide and releases from waste sites. The EPA banned the pesticide in 1972. However, DDT continues to enter the environment because many areas of the world still use this pesticide. In the environment, DDT and its break down products DDE and DDD are long-lived chemicals that accumulate in the fatty tissue, skin, and internal organs of fish and other animals. Thus, DDT, DDE, and DDD levels can be much higher in fish tissue than in water or soil. Eating fish that contain DDT or its break down products may damage the nervous system, affect reproductive and liver function, and may increase the risk of cancer. </p>
<h3>Chlordane </h3>
<p>Chlordane is a man-made pesticide used in the United States from 1948 to 1988. Before 1978, chlordane was used as a pesticide on agricultural crops, lawns, gardens, and as a fumigating agent. Between 1978 and 1983, the EPA phased out above-ground uses of chlordane. From 1983 until 1988, chlordane’s only approved use in the United States was for termite control. In 1988, because of human health concerns, the EPA banned all uses of chlordane in the United States. Chlordane breaks down very slowly in the environment and accumulates in the fatty tissue, skin, and internal organs of fish and other animals. Chlordane remains in our food supply because its widespread use on agricultural crops in the 1960s and 1970s contaminated agricultural soil. Chlordane can harm the nervous system, digestive system, endocrine system, and liver. Even at doses that cause no anatomical damage, chlordane may cause behavioral disorders in infants exposed before birth or while nursing. Chlordane may also cause cancer. </p>
<h3>Toxaphene </h3>
<p>Toxaphene, introduced in 1947, was probably the most heavily used pesticide in the United States during the 1970s. Toxaphene was primarily used in the southern United States to control insect pests on cotton and other crops. Toxaphene was also used to control insect pests on livestock and to kill unwanted fish in lakes. In the United States, the EPA banned toxaphene for most uses in 1982. From 1982 until 1990, when the EPA banned all uses of toxaphene in the United States, toxaphene was approved only for use on livestock and for insect control emergencies. Toxaphene enters surface waters through soil runoff, direct application as a pesticide, wastewater release from manufacturing facilities, and through disposal of waste pesticides. Toxaphene is a long-lived chemical in the environment that accumulates in fatty tissue, skin, and internal organs of fish and other animals. Eating fish that contain toxaphene may cause degenerative changes to the liver, kidney, and nervous system. Toxaphene may also cause cancer. </p>
<h3>Aldrin and Dieldrin </h3>
<p>Dieldrin is a pesticide that is also a break-down product of the chlorinated pesticide aldrin. Dieldrin was widely used as a pesticide on corn, cotton, and citrus crops between 1950 and 1974. Dieldrin was also used to control locusts, mosquitoes, and termites. In 1970, the Unites States Department of Agriculture canceled all agricultural uses of dieldrin in the United States. Dieldrin was used to control termites until 1987, when all uses were banned in the United States by the EPA. Aldrin and dieldrin are no longer produced in the Unites States. Dieldrin enters the environment through past uses and accidental spills or leaks from storage containers at disposal sites. Once dieldrin is in the environment, it attaches to soil and lake or river sediments and breaks down very slowly. Dieldrin is long-lived in the environment and accumulates in the fatty tissue, skin, and internal organs of fish and other animals. Eating fish containing dieldrin may decrease the effectiveness of the human immune system, increase infant mortality, reduce reproductive success, cause birth defects, damage kidneys, and may cause cancer. </p>
<h3>Chlorinated Dibenzodioxins and Dibenzofurans (Dioxin) </h3>
<p>Dioxins are formed as unintentional by-products of many industrial processes, incomplete combustion, and various chemical production processes. Dioxins are also natural products of forest fires and possibly other natural processes, but these sources are small compared to dioxins produced by human activity. Human activities that produce dioxins include combustion of fossil fuels, wood, and municipal and industrial waste. The bleaching process in pulp and paper production and the manufacture of some chlorinated chemicals produce dioxins. Dioxins have been found in soil, surface water, lake and river sediments, and plant and animal tissue in all regions of the world. Dioxins are extremely long-lived in the environment and readily accumulate in fish and other animal tissues. Levels of dioxins found in fish and other animal tissues may be hundreds to thousands of times greater than levels found in surrounding waters or sediments. Eating fish containing dioxins may cause chloracne, a severe skin disease with acne-like lesions that appear on body; dioxins may cause other skin rashes, skin discoloration, and excessive body hair. Dioxins may also cause liver damage, weight loss, reproductive damage, and birth defects. Dioxins may weaken the immune system,<strong></strong>disrupt the endocrine system, and may increase the risk of cancer in humans. </p>
<h3>Volatile Organic Compounds (VOCs) </h3>
<p>VOCs are used to make many products, especially plastics and solvents. Generally, these compounds do not accumulate in fish and animals. VOCs are usually found in fish at the same levels as those in the surrounding waters. Most VOC contamination is due to a direct discharge of these compounds to surface waters. Eating fish containing VOCs may cause cancer in animals and humans. </p>

<hr/>
<a class="bookmark" title="sources" name="sources"></a>
<h2>Sources of Information </h2>
<ul>
	<li><a href="http://www.epa.gov/waterscience/fish/chemfacts.html">United States Environmental Protection Agency (EPA) Chemical Fact Sheets</a></li>
	<li><a href="http://www.atsdr.cdc.gov/toxfaqs/index.asp">Agency for Toxic Substances and Disease Registry (ATSDR) ToxFAQs</a></li>
	<li><a href="http://www.atsdr.cdc.gov/PHS/Index.asp">Agency for Toxic Substances and Disease Registry (ATSDR) Public Health Statements</a></li>
</ul>

<hr/>
<a class="bookmark" title="guidance" name="guidance"></a>
<h2>General Fish Consumption Guidance for Texas Waters </h2>
<ul>
	<li>Eat smaller, younger fish. These fish generally contain lower levels of contaminants than larger, older fish.</li>
	<li>Remove skin, dark muscle tissue, and fat from fish. This practice reduces the risk of exposure to many organic contaminants, including PCBs, pesticides, and dioxins that readily accumulate in the fatty tissues.</li>
	<li>Fish internal organs may contain high levels of contaminants and should not be eaten.</li>
	<li>Eat fish from a variety of water bodies to reduce risk of exposure to any one contaminant or group of contaminants.</li>
	<li>Follow the DSHS safe eating guidelines for water bodies listed in this booklet. Eating a few fish meals from any area of concern probably has little or no human health risk, but eating contaminated fish frequently and regularly over a long period of time poses potential human health risks. <br/></li>
	<li>The DSHS recommends that people eat some commercially caught fish or that they substitute other sources of lean protein (i.e. chicken, venison, or soy products) for recreationally caught fish. </li>
</ul>


<?php include '/home/codio/workspace/includes/footer.html' ?>