<?php
	$title= "Archived Food Alerts for March 2015 - Food Manufacturers, Wholesalers, and Warehouses" ;
	include '/home/codio/workspace/includes/header.html';
	include '/home/codio/workspace/includes/menus/foods_menu.html'; 
?>

<hr/>
<strong>Also See:</strong> 
<ul>
	<li><a title="Current Food Alerts and Recalls" href="/foods/alerts/">Current Food Alerts and Recalls</a></li>
	<li><a title="Archived Food Alerts" href="/foods/alerts/archives/">Archived Food Alerts</a></li>
</ul>
<hr/>

<h2>March 25, 2015</h2>
<ul>
	<li><strong>Benson's Old Home Kitchens Bakery Division is recalling The Bakery Baked with Pride - Sock It to Me Cr�me Cake, Net Wt. 32oz (2lb) 907g, packed in a rigid clear plastic dome, sold in Walmart, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1416-2015&amp;amp;w=03252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1416-2015&amp;w=03252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1416-2015&amp;w=03252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Goya Foods, Inc. is recalling Kirby Black Beans Creole Seasoning (29 oz.) and Goya Black Bean Soup (29 oz.), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Twin City Bagel, Inc. is recalling several bagel products sold under different brand names, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Korean Food Co. is recalling Go Hyang Mak Kimchi, packaged in 32 oz. and half gallon cases, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1429-2015&amp;amp;w=03252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1429-2015&amp;w=03252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1429-2015&amp;w=03252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Chris A. Papas &amp; Son Co. is recalling several flavors of Marshmallow Eggs and Cream Eggs, due to undeclared Yellow #5.</strong><br/>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Aron Streit Inc. is recalling Streit�s Kids Dark Chocolate Coins, packaged in 24 ct. 15 g. mesh bags, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1428-2015&amp;amp;w=03252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1428-2015&amp;w=03252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1428-2015&amp;w=03252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Snoqualmie Gourmet Ice Cream is recalling several flavors of Snoqualmie brand ice cream products, packaged in 2.5 gallon clear flexible plastic bags, 3 gallon plastic tubs, 1.5 gallon plastic tubs, 1 gallon plastic trays, and 16 oz. paper cartons, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Superior Foods, Inc. is recalling Simply Balanced Organic Chopped Spinach (10 oz.) steam-in bag, sold in Target stores, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439761.htm" href="http://www.fda.gov/Safety/Recalls/ucm439761.htm">http://www.fda.gov/Safety/Recalls/ucm439761.htm</a><br/><br/></li>
	<li><strong>La Terra Fina is recalling Spinach Artichoke &amp; Parmesan Dip made with Greek Yogurt (31oz. tub) and Chunky Spinach Artichoke &amp; Parmesan Dip (31oz. tub), due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439940.htm" href="http://www.fda.gov/Safety/Recalls/ucm439940.htm">http://www.fda.gov/Safety/Recalls/ucm439940.htm</a><br/><br/></li>
	<li><strong>Carmel Food Group is recalling Rising Moon Organics Garlic &amp; Veggie Ravioli (6/8 oz.), Rising Moon Organics Spinach Florentine Ravioli (6/8 oz.), and Rising Moon Organics Spinach &amp; Cheese Ravioli (6/8 oz.), due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439539.htm" href="http://www.fda.gov/Safety/Recalls/ucm439539.htm">http://www.fda.gov/Safety/Recalls/ucm439539.htm</a><br/><br/></li>
	<li><strong>Blue Bell Ice Cream is recalling 3 oz. institutional/food service ice cream cups in chocolate, strawberry and vanilla flavors with tab lids, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439533.htm" href="http://www.fda.gov/Safety/Recalls/ucm439533.htm">http://www.fda.gov/Safety/Recalls/ucm439533.htm</a><br/><br/></li>
	<li><strong>Amy�s Kitchen, Inc. is recalling several different prepared pastas and entrees due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439397.htm" href="http://www.fda.gov/Safety/Recalls/ucm439397.htm">http://www.fda.gov/Safety/Recalls/ucm439397.htm</a><br/><br/></li>
	<li><strong>Texas Star Nut and Food Co. Inc.is recalling Nature�s Eats Natural Macadamia Nuts, due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439283.htm" href="http://www.fda.gov/Safety/Recalls/ucm439283.htm">http://www.fda.gov/Safety/Recalls/ucm439283.htm</a><br/><br/></li>
	<li><strong>Nutiva is recalling O'Coconut Classic and O'Coconut Hemp &amp; Chia due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439285.htm" href="http://www.fda.gov/Safety/Recalls/ucm439285.htm">http://www.fda.gov/Safety/Recalls/ucm439285.htm</a><br/><br/></li>
	<li><strong>Aurora Products, Inc. is recalling Natural Walnuts, Mixed Nuts, and Trail Mixes containing walnuts, in various packaging and sizes, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm440314.htm" href="http://www.fda.gov/Safety/Recalls/ucm440314.htm">http://www.fda.gov/Safety/Recalls/ucm440314.htm</a><br/><br/></li>
	<li><strong>StoneRidge Wholesale Division, LLC is recalling StoneRidge Roasted Garlic Pork Tenderloin packaged in 1-2 lb. vacuum sealed packages, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-048-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-048-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-048-2015-release</a><br/><br/></li>
	<li><strong>Viz Cattle is recalling Flap Meat packaged in 30 lb. cardboard boxes, due to misbranding.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-052-2015" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-052-2015">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-052-2015</a><br/><br/></li>
</ul>

<hr/>
<h2>March 19, 2015</h2>
<ul>
	<li><strong>Soyko International, Inc. is recalling Byglands Non-GMO Soybeans for Sprouting, in 25KG bags and 1MT tote bags, due to possible Listeria monocytogenes contamination.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1413-2015&amp;w=03182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1413-2015&amp;w=03182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Korean Food Co. is recalling Soybean Sprouts, packaged in 1 lb. and 2 lb. bags, due to possible Listeria monocytogenes contamination.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1406-2015&amp;w=03182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1406-2015&amp;w=03182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Julian Bakery, Inc. is recalling Paleo Protein Bar Chocolate Brownie (2.1 oz.), and Paleo Protein Bar Cookies N' Cr�me (2.1 oz.), due to undeclared allergens.<br /> </strong>Please see the FDA Enforcement Report, Week of March 18, 2015 for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Ungar's Food Products, Inc. is recalling Dr. Praeger's Sensible Foods Bombay Curry Veggie Burgers (11 oz.), due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1405-2015&amp;w=03182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1405-2015&amp;w=03182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>E. Martin &amp; Sons Co., Inc. is recalling Ground Cumin, and Chili Powder, due to undeclared allergens.<br /> </strong>Please see the FDA Enforcement Report, Week of March 18, 2015 for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Trader Joe�s Company is recalling Raw Walnuts, packaged in clear plastic bags in 16 oz. and 12 oz. sizes, due to possible Salmonella contamination</strong>.<br /> Please see the following website for more details:<br /> <a href="http://www.fda.gov/safety/recalls/ucm438472.htm">http://www.fda.gov/Safety/Recalls/ucm438472.htm</a><br/><br/></li>
	<li><strong>Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder, packaged in clear plastic bags in size ranges of 0.25 pound to 0.30 pound, due to possible Salmonella contamination.�<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/safety/recalls/ucm438935.htm">http://www.fda.gov/safety/recalls/ucm438935.htm</a><br/><br/></li>
	<li><strong>Kraft Foods Group is recalling Original flavor of Kraft Macaroni &amp; Cheese Dinner packaged in , 7.25 oz. box,3-pack box 7.25 oz. boxes, 4-pack shrink-wrap of 7.25 oz. boxes, and 5-pack shrink-wrap of 7.25 oz. boxes, due to the possibility that some boxes may contain small pieces of metal.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438700.htm">http://www.fda.gov/Safety/Recalls/ucm438700.htm</a><br/><br/></li>
	<li><strong>Frontier Co-op is recalling several of its products manufactured with organic garlic powder that were sold under its Frontier, Simply Organic brands, and Whole Foods Market brand, due to possible Salmonella contamination.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438360.htm">http://www.fda.gov/Safety/Recalls/ucm438360.htm</a><br/><br/></li>
	<li><strong>Product Removal/Foodborne Illness Outbreak Investigation Advisory: Five patients who were treated in a single hospital in Kansas were infected with one of four rare strains of Listeria monocytogenes. Three of these strains were found in samples of Blue Bell Creameries single serving Chocolate Chip Country Cookie Sandwich, the Great Divide Bar ice cream products, and single-serving ice cream product Scoops. Several Blue Bell Creameries products have been removed from the market.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438626.htm">http://www.fda.gov/Safety/Recalls/ucm438626.htm</a><br/><br/></li>
	<li><strong>Bear Creek Smokehouse is recalling Beasley�s Smokehouse Chopped Barbeque Beef with Sauce (1 lb.), and Bear Creek Smokehouse Chopped Beef Brisket (1 lb. and 5 lb.), due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-046-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-046-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 16, 2015</h2>
<ul>
	<li><strong>MegaMex Foods, LLC is recalling Herdez Chilpotle Peppers, 7oz., due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1379-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1379-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>H-E-B Corpus Christi Operations is recalling H-E-B Homestyle White Corn Tortillas 12ct. and 30 ct., due to corn stalk fragments in tortillas.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1378-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1378-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Morris J. Golombeck, Inc. is recalling Ground Cumin Seed (50 lbs. net wt.), due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1377-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1377-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Jardine Foods Inc. is recalling several seasonings, sauces, and chili kits, sold under brand names �Jardines�s�, �D.L. Jardine�s�, and �Shotgun Willie�s, due to� undeclared allergens.<br /> </strong>Please see the FDA Enforcement Report, Week of March 11, 2015 for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03112015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Hi-Tech Pharmacal Co., Inc. is recalling Ferrous Sulfate Elixir (220 mg/5ml), due to out-of-specification result for pH observed during stability testing.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1380-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1380-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Badia Spices, Inc. is recalling Badia Ground Cumin in 2 oz., 7 oz. and 16 oz. packages, due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438042.htm">http://www.fda.gov/Safety/Recalls/ucm438042.htm</a><br/><br/></li>
	<li><strong>Trader Joe�s Company is recalling Trader Joe�s Cinnamon Almonds, packaged 16 oz. clear packages, due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438079.htm">http://www.fda.gov/Safety/Recalls/ucm438079.htm</a><br/><br/></li>
	<li><strong>UltraZx, Labs, L.L.C is recalling UltraZx weight loss supplements due to undeclared ingredients.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm437517.htm">http://www.fda.gov/Safety/Recalls/ucm437517.htm</a><br/><br/></li>
	<li><strong>Gourmet Kitchen, Inc. is recalling several beef products, sold under brand names �Gourmet Kitchen�, �Gourmet Foods�, MacKenzie Limited�, and �Impromtu Petitie�, due to� undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-045-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-045-2015-release</a><br/><br/></li>
	<li><strong>Bon Appetizers, LLC is recalling Cuisine Innovations Chicken Empanada, Cuisine Innovations Chicken Quesadilla Cornucopia (Chicken and Cheese Filling in Flour Tortilla), Ridgecrest Chicken Quesadilla Cornucopia (Chicken and Cheese Filling in Flour Tortilla),and Culinary Secrets Quesadilla Cornucopia, all packaged in various weight bulk packages, due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-042-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-042-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 9, 2015</h2>
<ul>
	<li><strong>Washington Harvest Wapato is recalling The World's Finest Mixed Fruit containing Red Delicious Apples, Granny Smith Apples and Navel Oranges, packed in poly bags 6/4 lb. bags per case, and Fast &amp; Fresh Grab Mixed Apples And/or Oranges containing Fuji Apples, Granny Smith Apples and Oranges, packed in poly bags 10/4 lb. bags per case or 8/5lb. mesh bags per case, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Kabobs Inc. is recalling Frozen Shrimp Empanada 100 count, Frozen Vegetable Empanada 100 count, and Frozen Yucatan Style Roasted Corn &amp; Black Bean Tart, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Gulf Coast Blenders, Inc. is recalling several spices and seasonings sold under different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Schwan Food Company is recalling Holiday Foods Hors D'Oeuvre Vegetable Samosa Triangle, 60 1.5 oz., and Holiday Foods Hors D'Oeuvre Vegetable Samosa Potsticker, 100 0.7 oz pieces , both for institutional use only, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Harvest Food Group, Inc. is recalling Tommy's Superfoods&nbsp; Seasoned Santa Fe Rice packed in 10 oz. (284 g) plastic film bags and Tastee Western Rice packaged in 40 lb. corrugated boxes with blue poly liners, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1302-2015&amp;amp;w=03042015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1302-2015&amp;w=03042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1302-2015&amp;w=03042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Sugar Daddy LTD is recalling Caramel Apples labeled as Merbs Candies, Double Dipped individually wrapped in plastic, and Caramel and Pecan Apple labeled as Merbs Candies, Bionic Apple packaged in plastic wrappers, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Adams Extract &amp; Spice LLC is recalling several spices and seasonings sold under different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Relish Foods Inc. is recalling Pacific Fusion Frozen Tuna Steak Wild Caught net wt. 15 lb. (240 oz.) 6.80 kg, due to elevated levels of histamine.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-0801-2015&amp;amp;w=03042015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0801-2015&amp;w=03042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0801-2015&amp;w=03042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Maternal Science, Inc. is recalling healthy mama� Boost It Up! Mighty Mango with Ginger&nbsp; 12 fl oz. packaged in a bottle and healthy mama� Boost It Up! Mighty Mango 12 fl oz. packaged in a bottle, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm436491.htm" href="http://www.fda.gov/Safety/Recalls/ucm436491.htm">http://www.fda.gov/Safety/Recalls/ucm436491.htm</a><br/><br/></li>
	<li><strong>Rio Tex Wholesale Meats is recalling Hausman Foods Brand Cooked Beef Taco Filling Seasoned Cooked Beef Barbacoa, Fully Cooked Barbacoa, and Beef Carne Guisada packaged in 20-lb. boxes containing four 5-lb. packages, and Rio-Tex-Meats Barbacoa packaged in 15-lb. and 45-lb. boxes containing three 5-lb. or 15-lb. packages, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release</a><br/><br/></li>
	<li><strong>Campos Foods, LLC is recalling H-E-B Fully Cooked Thick N� Tasty Cheese Burgers Natural Smoke Flavor Added net wt. 15-oz. (425g) bag containing four 3.75-oz. burgers and net wt. 30-oz. (1.87lbs) (850g) bag containing eight 3.75-oz. burgers, and H-E-B Fully Cooked Thick N� Tasty&nbsp; Bacon Cheese Burgers Natural Smoke Flavor Added net wt. 30-oz. (1.87lbs) (850g) bag containing eight 3.75-oz. burgers, misbranding and undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 2, 2015</h2>
<ul>
	<li><strong>Hamchorom Inc. is recalling Haitai Tayo Crackers (140 g) 24 boxes/carton, in box colors: blue, yellow, and red, and Haitai Gyeran Crackers (70 g) 20 boxes/carton, in yellow box with "Angry Birds" logo, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Probar LLC is recalling Frosted Peanut Butter BASE Protein Bar, 2.46 oz., film wrapped bar packaged in 12 wrapped units per sleeve/carton, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1224-2015&amp;amp;w=02252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Talenti� Gelato &amp; Sorbetto is recalling Talenti� Gelato &amp; Sorbetto Sea Salt Caramel Gelato packaged in one pint (473 mL) clear plastic jars, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm436020.htm" href="http://www.fda.gov/Safety/Recalls/ucm436020.htm">http://www.fda.gov/Safety/Recalls/ucm436020.htm</a><br/><br/></li>
	<li><strong>Fairway �Like No Other Market� is recalling Fairway brand Raw Hazelnuts (Filberts), packaged in clear, plastic cello bags of varying weights, each weighing less than one pound, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435547.htm" href="http://www.fda.gov/Safety/Recalls/ucm435547.htm">http://www.fda.gov/Safety/Recalls/ucm435547.htm</a><br/><br/></li>
	<li><strong>Oscar�s Hickory House Inc. is recalling Oscar�s Adirondack Mountain Smokehouse Beef Jerky in 4 oz. and 8 oz. cryovac packages, due to a processing deviation.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release</a><br/><br/></li>
</ul>



<?php include '/home/codio/workspace/includes/footer.html' ?>	