<?php
	$title= "Archived Food Alerts for April 2015 - Food Manufacturers, Wholesalers, and Warehouses" ;
	include '/home/codio/workspace/includes/header.html';
	include '/home/codio/workspace/includes/menus/foods_menu.html'; 
?>

<hr/>
<strong>Also See:</strong> 
<ul>
	<li><a title="Current Food Alerts and Recalls" href="/foods/alerts/">Current Food Alerts and Recalls</a></li>
	<li><a title="Archived Food Alerts" href="/foods/alerts/archives/">Archived Food Alerts</a></li>
</ul>
<hr/>

<h2>April 30, 2015</h2>
<ul>
	<li><strong>Carmel Food Group, Inc. is recalling Rising Moon Organics Garlic and Veggie Ravioli 8 oz., Rising Moon Organics Spinach Florentine Ravioli 8 oz., and Rising Moon Organics Spinach &amp; Cheese Ravioli 8 oz., due to possible Listeria monocytogenes contamination.<br></strong>Please see the FDA Enforcement Report, Week of April 29, 2015 for more details:<br><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04292015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04292015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04292015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Badia Spices, Inc. is recalling Ground Cumin in 2 oz., 7 oz., and 16 oz. sizes, due to undeclared allergens.<br></strong>Please see the following website for more details:<br><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2023-2015&amp;amp;w=04292015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2023-2015&amp;w=04292015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2023-2015&amp;w=04292015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Waymouth Farms, Inc. is recalling Good Sense Raw Pine Nuts in various sizes, due to possible Salmonella contamination.<br></strong>Please see the following website for more details:<br><a title="http://www.fda.gov/Safety/Recalls/ucm444781.htm" href="http://www.fda.gov/Safety/Recalls/ucm444781.htm">http://www.fda.gov/Safety/Recalls/ucm444781.htm</a><br/><br/></li>
	<li><strong>Golden Krust Patties is recalling several Beef and Chicken Patty products, sold in various counts and sizes, due to misbranding and undeclared allergens.</strong> <br>Please see the following website for more details:<br><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-071-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-071-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-071-2015-release</a><br/><br/></li>
	<li><strong>Alpine Sausage Kitchen is recalling Alpine Sausage Kitchen Vienna Sausage Calcium Reduced Dried Skim Milk Added, and Alpine Sausage Kitchen Cooked Bratwurst (German Brand), due to undeclared allergens.<br></strong>Please see the following website for more details:<br><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-069-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-069-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-069-2015-release</a><br/><br/></li>
</ul>
<hr/>
<h2>April 24, 2015</h2>
<ul>
	<li><strong>Jeni�s Splendid Ice Creams is recalling all flavors of ice creams, frozen yogurts, sorbets, and ice cream sandwiches, due to possible Listeria monocytogenes contamination.<br /></strong> Please see the following website for more details:<br /><a title="http://www.foodsafetynews.com/2015/04/jenis-splendid-ice-creams-recalls-all-products-temporarily-closes-stores-due-to-listeria-risk/#.VTpn159FC00" href="http://www.foodsafetynews.com/2015/04/jenis-splendid-ice-creams-recalls-all-products-temporarily-closes-stores-due-to-listeria-risk/#.VTpn159FC00">http://www.foodsafetynews.com/2015/04/jenis-splendid-ice-creams-recalls-all-products-temporarily-closes-stores-due-to-listeria-risk/#.VTpn159FC00</a><br/><br/></li>
	<li><strong>ProThera, Inc. is recalling Klaire Labs Ther-Biotic FACTOR 6 Probiotic Supplement, and Klaire Labs Ther-Biotic Children's Chewable Probiotic, due to possibility of shards of blue glass being in bottle.<br /></strong> Please see the FDA Enforcement Report, Week of April 22, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04222015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04222015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04222015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Trader Joes Company is recalling Cinnamon Almonds (net wt. 16 oz.), due to undeclared allergens.<br /></strong> Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1943-2015&amp;amp;w=04222015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1943-2015&amp;w=04222015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1943-2015&amp;w=04222015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Cost Plus Management Services, Inc. is recalling Shanghai Ceramic Spoons, due to possibility of exceeding FDA guidance levels for leachable lead and cadmium.</strong><br />Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1948-2015&amp;amp;w=04222015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1948-2015&amp;w=04222015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1948-2015&amp;w=04222015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Sahadi Fine Foods, Inc. is recalling Ground Cumin (5 lbs.), due to undeclared allergens.<br /></strong> Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1950-2015&amp;amp;w=04222015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1950-2015&amp;w=04222015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1950-2015&amp;w=04222015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Gourmet Foods International is recalling several spices and seasoning blends, sold under Culinary Masters, Wildseason, and Joe Paatis brands, due to undeclared allergens.<br /></strong> Please see the FDA Enforcement Report, Week of April 22, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04222015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04222015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04222015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>ReNew Life Formulas, Inc. is recalling PureLife Naturals Adult Multi-Plus Multi-Vitamins &amp; Minerals Plus Herbs (60 capsules), and PureLife Naturals Multi-Action Immunity (90 capsules), due to undeclared allergens.<br /></strong> Please see the FDA Enforcement Report, Week of April 22, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04222015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04222015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04222015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Inventure Foods, Inc. is recalling several varieties of Fresh Frozen frozen vegetables, and select varieties of Jamba At Home smoothie kits, due to possible Listeria monocytogenes contamination.<br /></strong> Please see the following website for more details:<br /><a title="http://www.fda.gov/Safety/Recalls/ucm444311.htm" href="http://www.fda.gov/Safety/Recalls/ucm444311.htm">http://www.fda.gov/Safety/Recalls/ucm444311.htm</a><br/><br/></li>
	<li><strong>West Liberty Foods is recalling Subway Fully Cooked Grilled Chicken Breast Patty, packaged in 5 lb. bags, due to possible foreign matter contamination.<br /></strong> Please see the following website for more details:<br /><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-067-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-067-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-067-2015-release</a><br/><br/></li>
</ul>
<hr />
<h2>April 21, 2015</h2>
<ul>
	<li><strong>Blue Bell Creameries is recalling ALL of its products currently on the market, due to possible Listeria monocytogenes contamination. Samples taken by the FDA, �and the Texas Department of State Health Services have shown the presence of Listeria monocytogenes.<br /></strong> Please see the following website for more details:<br /><a title="http://www.fda.gov/Food/RecallsOutbreaksEmergencies/Outbreaks/ucm438104.htm" href="http://www.fda.gov/Food/RecallsOutbreaksEmergencies/Outbreaks/ucm438104.htm">http://www.fda.gov/Food/RecallsOutbreaksEmergencies/Outbreaks/ucm438104.htm</a><br/><br/></li>
	<li><strong>Nutiva is recalling Nutiva O'Coconut Lightly Sweetened Coconut Treat and Nutiva O'Coconut Lightly Sweetened Coconut Treat - Hemp &amp; Chia, due to possible Salmonella contamination.</strong><br />Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>A I Foods Corporation is recalling several foods containing egg roll skins, due to undeclared allergens.<br /></strong> Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Iberia Foods Company of New York, Inc is recalling Sazon Iberia con Culantro y Achiote (Coriander &amp; Annatto) (3.52 oz.) &amp; (6.34 oz.) and, Vitarroz Sazon con Culantro y Achiote (Corriander &amp; Annatto) (6.34 oz.),. </strong>. <strong> due to undeclared allergens.<br /></strong> Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Unilever United States, Inc. is recalling Talenti Gelato &amp; Sorbetto. Sea Salt Carmel Gelato, 1 pt. (473 mL), packaged in clear plastic jars, due to undeclared allergens.<br /></strong> Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1923-2015&amp;amp;w=04152015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1923-2015&amp;w=04152015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1923-2015&amp;w=04152015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Arcadia Trading is recalling Red Thread Fish (7 oz.), packaged in a heat-sealed plastic bag, due to incomplete processing.<br /></strong> Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1932-2015&amp;amp;w=04152015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1932-2015&amp;w=04152015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1932-2015&amp;w=04152015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Vintage Food Corp. is recalling Ground Cumin (5 lbs.), due to undeclared allergens.<br /></strong> Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1940-2011&amp;amp;w=04152015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1940-2011&amp;w=04152015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1940-2011&amp;w=04152015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Classic Cooking LLC is recalling Garden Lites Southwestern Souffle (7 oz.),. </strong>. <strong> Garden Lites Kale &amp; Quinoa Souffle (7 oz.), Garden Lites Veggie Bites Kale &amp; Brown Rice (9 oz.), and Garden Lites Veggie Chili &amp; Cornbread Melt (7 oz.), due to undeclared allergens.<br /></strong> Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>H-E-B Houston Culinary Center is recalling H-E-B Single Serving Tortilla Soup,. </strong>. <strong> H-E-B Single Serving Poblano Corn Chowder, H-E-B Single Serving Gumbo, and H-E-B Single Serving Texas Ranch Casserole, purchased from the hot soup kettle at the Deli/Prepared Foods Counter, due to undeclared allergens.<br /></strong> Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>The Santa Barbara Smokehouse, Inc. is recalling several Smoked Salmon products; vacuum packaged and sold under several brand names, due to possible Listeria monocytogenes contamination.<br /></strong> Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>California Snack Foods Inc. is recalling Karm'l Dapple (4 oz.) Carmel Apples, sold in single size and 3 pack, due to possible Listeria monocytogenes contamination.<br /></strong> Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Texamerican Food Blending, Inc. is recalling several spices and seasoning blends, sold in a variety of weights, due to undeclared allergens.</strong><br />Please see the FDA Enforcement Report, Week of April 15, 2015 for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04152015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04152015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Nutri-Dyn Midwest, Inc. is recalling Nutri-Dyn 5-HTP Extra Strength, packaged in plastic bottles containing 60 capsules, due to misbranding.<br /></strong> Please see the following website for more details:<br /><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1922-2015&amp;amp;w=04152015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1922-2015&amp;w=04152015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1922-2015&amp;w=04152015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Superior Nut &amp; Candy Co. is recalling Pine Nuts (4 oz.), due to possible Salmonella contamination.</strong><br />Please see the following website for more details:<br /><a title="http://www.fda.gov/Safety/Recalls/ucm443666.htm" href="http://www.fda.gov/Safety/Recalls/ucm443666.htm">http://www.fda.gov/Safety/Recalls/ucm443666.htm</a><br/><br/></li>
	<li><strong>Hines Nut Company is recalling Hines Nut Brand Walnut Halves &amp; Pieces (16 oz.), packaged in black foam trays, due to possible Salmonella contamination.<br /></strong> Please see the following website for more details:<br /><a title="http://www.fda.gov/Safety/Recalls/ucm443477.htm" href="http://www.fda.gov/Safety/Recalls/ucm443477.htm">http://www.fda.gov/Safety/Recalls/ucm443477.htm</a><br/><br/></li>
	<li><strong>Whole Foods Market is recalling Whole Foods Market Raw Macadamia Nuts, packaged in 11 oz. plastic tubs, due to possible Salmonella contamination.<br /></strong> Please see the following website for more details:<br /><a title="http://www.fda.gov/Safety/Recalls/ucm443476.htm" href="http://www.fda.gov/Safety/Recalls/ucm443476.htm">http://www.fda.gov/Safety/Recalls/ucm443476.htm</a><br/><br/></li>
	<li><strong>Conway Import Co., Inc. is recalling Conway Organic Sesame Ginger Dressing and Conway Citrus Organic Vinaigrette Dressing, both packaged in plastic gallon jars, due to possible Salmonella contamination.<br /></strong> Please see the following website for more details: <br /><a title="http://www.fda.gov/Safety/Recalls/ucm443463.htm" href="http://www.fda.gov/Safety/Recalls/ucm443463.htm">http://www.fda.gov/Safety/Recalls/ucm443463.htm</a><br/><br/></li>
	<li><strong>Prolainat is recalling Trader Joe�s A Dozen Sweet Bites (Chocolate &amp; Coffee �Op�ra� Cake, Raspberry �Macaron Aux Framboises� Cake, Caramel &amp; Chocolate Cake) (9.16 oz.), due to undeclared ingredients.</strong> <br />Please see the following website for more details: <br /><a title="http://www.fda.gov/Safety/Recalls/ucm443480.htm" href="http://www.fda.gov/Safety/Recalls/ucm443480.htm">http://www.fda.gov/Safety/Recalls/ucm443480.htm</a><br/><br/></li>
	<li><strong>Kayem Foods is recalling Trader Joe�s brand Sweet Apple Chicken Sausage (12 oz.), and Al Fresco brand Apple Maple Fully Cooked Breakfast Chicken Sausage (8 oz.), due to possible foreign matter contamination.<br /></strong> Please see the following website for more details: <br /><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-066-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-066-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-066-2015-release</a><br/><br/></li>
</ul>
<hr/>
<h2>April 15, 2015</h2>
<ul>
	<li><strong>Interbake Foods LLC is recalling Mrs. Fields White Chunk Macadamia Cookies 2.1 oz., due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1870-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1870-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1870-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Cheryl�s is recalling Cheryl's Buttercream Frosted Cut-Out Bunny Head Cookies Net Wt. 1.5oz (43g), due to mislabeling.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1805-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1805-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1805-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Maternal Science Inc. is recalling Healthy Mama Boost it Up Mango with Ginger Caffeine Free Protein with Energy Drink 12 fl. oz., Healthy Mama Boost it Up Pom Cherry Caffeine Free Protein with Energy Drink 12 fl. oz., and Healthy Mama Boost It Up Mighty Mango Caffeine Free Protein with Energy Drink 12 fl. oz., due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>White Wave Foods, Inc. is recalling Organic Horizon Sandwich Crackers Cheddar 7.5 oz., due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1869-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1869-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1869-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>ProSupps USA LLC is recalling Mr. Hyde Intense Energy Pre Workout 8.0 oz. (228 grams), due to containing more yohimbine hcl than declared on the label.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1783-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1783-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1783-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Michael Foods, Inc. is recalling Natural Shaped Fried Egg (patties) 1.75 oz., sold under brand names Pappetti's Table Ready and Glenview Farms, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1875-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1875-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1875-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>See's Candies Inc. is recalling See's Candies Classic Red Heart with Assorted Chocolates (8 oz., 227 g), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1788-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1788-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1788-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Creative Foodworks, Inc. is recalling several different salsas, sold under several different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>American Spice &amp; Seasoning, Inc. is recalling Adkins Barbecue Spice (Net Wt. 25 lbs.).<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1794-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1794-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1794-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Brinkhoff &amp; Monoson Inc. is recalling Dark Chili Powder, Archer Farms Cumin, and HT Traders Blue Cheese Jalapeno Spicy &amp; Unique Seasoning, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Gilster-Mary Lee Corp. is recalling Market Pantry Honey &amp; Oat Mixers ready-to-eat dry cereal 18 oz. (510 g), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1806-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1806-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1806-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Zenobia Company LLC is recalling My Spice Sage Ground Cumin, packaged in 1 oz., 4 oz., 4.9 oz., 16 oz., and 50 lb. sizes, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1803-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1803-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1803-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Bidart Bros. is recalling Granny Smith Apples, "Granny's Best" or "Big B, and Gala Apples "Big B"; all sold in 40-45 lb. cases, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Tai Foong U.S.A., Inc is recalling Northern Chef Lightly Coated Cod Fingers 10 oz. (284 g), due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1807-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1807-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1807-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Beech-Nut Nutrition is recalling Stage 2 Beech-Nut Classics Sweet Potato &amp; Chicken, packaged in 4 oz. glass jars, due to possible contamination with broken glass.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-061-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-061-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-061-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>April 13, 2015</h2>
<ul>
	<li><strong>Texas Pecan Company Inc. is recalling several nut products and gift tins, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm442042.htm" href="http://www.fda.gov/Safety/Recalls/ucm442042.htm">http://www.fda.gov/Safety/Recalls/ucm442042.htm</a><br/><br/></li>
	<li><strong>Sabra Dipping Co., LLC is recalling Sabra Classic Hummus 10 oz., Sabra Classic Hummus 30 oz., Sabra Classic Hummus without Garnish 32oz., Sabra Classic Hummus 17oz Six Pack, and Hummus Dual Pack Classic/Garlic 23.5oz, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441863.htm" href="http://www.fda.gov/Safety/Recalls/ucm441863.htm">http://www.fda.gov/Safety/Recalls/ucm441863.htm</a><br/><br/></li>
	<li><strong>World Wide Gourmet Foods is recalling Central Market Teriyaki Salmon Jerky, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441838.htm" href="http://www.fda.gov/Safety/Recalls/ucm441838.htm">http://www.fda.gov/Safety/Recalls/ucm441838.htm</a><br/><br/></li>
	<li><strong>Blue Bell Creameries is recalling several ice cream and sherbet products sold in pint, quart, and half gallon sizes, due to possible Listeria monocytogenes contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441620.htm" href="http://www.fda.gov/Safety/Recalls/ucm441620.htm">http://www.fda.gov/Safety/Recalls/ucm441620.htm</a><br/><br/></li>
	<li><strong>Texas Star Nut and Food Co., Inc. is recalling Nature's Eats Mustang Island Macadamia Sunrise 14 oz., Nature's Eats Natural Macadamia Nuts 6 oz., and Central Market Natural Macadamia Nuts 6 oz., due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441686.htm" href="http://www.fda.gov/Safety/Recalls/ucm441686.htm">http://www.fda.gov/Safety/Recalls/ucm441686.htm</a><br/><br/></li>
</ul>

<hr/>
<h2>April 7, 2015</h2>
<ul>
	<li><strong>Agridient, Inc. is recalling Agridient Vital Wheat Gluten, packaged in a 50 lb. paper sack, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1618-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1618-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1618-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>El Popocatepetl Ind., Inc. is recalling Sundried Tomato flavored Tortilla Wraps 8 in., Spinach Pesto flavored Tortilla Wraps 8 in., and Chipotle flavored Tortilla Wraps 8 in., due to undeclared allergens and undeclared Yellow No. 5.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Mars Food US is recalling several varieties of Uncle Ben�s Ready Rice, due to possible metal fragment contamination.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder, packaged in Zip-Lock-type plastic bags, due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1580-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1580-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1580-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Unilever United States, Inc. is recalling Breyers No Sugar Added Salted Caramel Swirl 1.5-quart (1.41L), packaged in paperboard tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1584-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1584-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1584-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Whole Foods Market is recalling Chocolate Cake for Two packaged in clear plastic containers, due to undeclared allergens. <br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1585-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1585-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1585-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Sunfood Corporation is recalling Organic Sacha Inchi Powder, 8oz., due to possible Staphylococcus contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1586-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1586-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1586-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Hines Nut Co. is recalling Walnuts Halves &amp; Pieces net wt. 16 oz., due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1601-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1601-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1601-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Aloha is recalling Aloha Vanilla Premium Protein Powder and Aloha Chocolate Premium Protein Powder, sold under several different labels, due to possible Staphylococcus contamination.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Reo Spice &amp; Seasoning, Inc. is recalling several Seasonings, Spices, and Chili Blends, sold under Reo Bear, Vitek�s, Reo Ranch, Jmad�s, and Bon Ton brand names, due to undeclared allergens.</strong><br/>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>The Hain Celestial Group is recalling Taj Ethnic Bombay Curry Simmer Sauce 16 oz., Taj Ethnic Gourmet Calcutta Masala Simmer Sauce 16 oz., and Taj Ethnic Gourmet Punjab Saag Spinach Sauce 16 oz., due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Dursett Amigos, Ltd. is recalling Taco Kits, Taco Sauces, and Salsas, sold under Laura Lynn, Parade, HyVee, Brookshire, Roundy�s, and Rico�s brands, and HEB Bean &amp; Cheese Dip, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>FGF Brands is recalling US Foods brand Mini Naan, eight naan packaged in coated paper printed board and transparent wrap, net wt. 12.6 oz (360 g), due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1617-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1617-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1617-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Hope Foods is recalling Kale Pesto Hummus, packaged in 8 oz. plastic tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm440887.htm" href="http://www.fda.gov/Safety/Recalls/ucm440887.htm">http://www.fda.gov/Safety/Recalls/ucm440887.htm</a><br/><br/></li>
	<li><strong>Whole Foods Market is recalling Bran Muffin six packs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm440729.htm" href="http://www.fda.gov/Safety/Recalls/ucm440729.htm">http://www.fda.gov/Safety/Recalls/ucm440729.htm</a><br/><br/></li>
	<li><strong>Lebanese Butcher Slaughter, Inc. is recalling Beef Cuts in unlabeled plastic bags, and Lamb or Goat Cuts in unlabeled plastic bags, due to misbranding and processing without the benefit of full inspection.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-055-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-055-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-055-2015-release</a><br/><br/></li>
</ul>


<?php include '/home/codio/workspace/includes/footer.html' ?>	