<?php
	$title= "Summary of EPA's Renovation, Repair &amp; Painting Program Rule - Environmental Lead Program" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/elp_menu.html'; 
?>

<p>The U.S. Environmental Protection Agency (EPA) is administering the federal <a title="Renovation, Repair, and Painting (RRP) Program Rule" href="http://www2.epa.gov/lead/lead-renovation-repair-and-painting-program-rules">Renovation, Repair, and Painting (RRP) Program Rule</a> in Texas.</p>
<p>Common renovation activities like sanding, cutting, and demolition can create hazardous lead dust and chips by disturbing lead-based paint in pre-1978 construction, which can be harmful to adults and children. To protect against this risk, EPA issued this rule on April 22, 2008, which requires the use of lead-safe work practices and other actions aimed at preventing lead poisoning. Under the rule, effective December 22, 2008, renovators are required to provide a copy of the <a title="Lead-Safe Certified Guide to Renovate Right" href="http://www2.epa.gov/sites/production/files/documents/renovaterightbrochure.pdf">Lead-Safe Certified Guide to Renovate Right</a> <span class="small">(PDF, 7MB)</span> pamphlet to homeowners, building managers, day care centers, schools and occupants of pre-1978 construction of housing (called target housing) and child-occupied facilities before beginning work.</p> 
<p>Effective April 22, 2010, renovations in target housing (built prior to 1978) and child-occupied facilities (built prior to 1978) must be conducted by EPA certified (licensed) renovation firms using certified (trained by an EPA-accredited trainer) renovators who must follow the work practice requirements of the rule. The rule requires these certified renovators to use certain lead-safety techniques to renovate and/or remodel pre-1978 housing as well as in pre-1978 child-occupied facilities.</p> 
<p>The requirements of the RRP rule are triggered when a renovation, repair or a painting job disturbs more than 6 square feet of interior surface space in a room and/or 20 square feet of exterior surface space. A certified renovator could be a remodeler, a carpenter, a multi-family unit maintenance professional, a painter, a window or door replacement professional, or whoever else may disturb paint in pre-1978 construction.</p>

<hr/>
<h2>EPA Websites on Renovation, Repair, and Painting Program</h2>
<p>In order to get the word out about the rule, EPA has extensive materials on their web site explaining the rule and how to comply, as well as various brochures available. This information and materials are available in both English and Spanish on the <a title="EPA Lead Website" href="http://www2.epa.gov/lead">EPA Lead Website</a> where you can also obtain copies of the rule.  For copies of the educational brochures on this program, call 1-800-424-LEAD [5323] or download literature on the <a title="EPA Documents and Outreach Materials" href="http://www2.epa.gov/lead/documents-and-outreach-materials">EPA Documents and Outreach Materials</a> webpage.</p> 
<p>To find out who is offering EPA-accredited Renovator training, check the list of training providers maintained by EPA. For information on becoming an EPA-certified renovation firm and certified renovator, please visit the <a title="EPA Lead-Safe Certification Program" href="http://www2.epa.gov/lead/getcertified">EPA Lead-Safe Certification Program</a> webpage.</p>  
<p>For information on becoming an EPA-accredited RRP training provider, visit the <a title="EPA RRP Training Providers" href="http://www2.epa.gov/lead/renovation-repair-and-painting-program-training-providers">EPA RRP Training Providers</a> webpage.</p>

<hr/>
<h2>Responsible Agencies</h2>
<p>In Texas, the U.S. Environmental Protection Agency (EPA) is administering the <a title="Renovation, Repair, and Painting (RRP) Program Rule" href="http://www2.epa.gov/lead/lead-renovation-repair-and-painting-program-rules">Renovation, Repair, and Painting (RRP) Program Rule</a> while the Texas Department of State Health Services (DSHS) is administering the program for lead inspections, lead risk assessments, and lead abatements under the <a title="Texas Environmental Lead Reduction Rules (TELRR)" href="/elp/laws-rules.aspx">Texas Environmental Lead Reduction Rules (TELRR)</a>.</p>

<p>If you have questions regarding EPA's RRP rule, call 1-800-424-LEAD (5323) or the EPA Region 6 office in Dallas at 1-214-665-7577. For questions related to lead-based paint inspections, risk assessments, or lead abatements regulated through the TELRR, contact the state's Environmental Lead Program at 1-888-778-9440, ext. 2434 (toll-free in Texas), or 1-512-834-6787, ext. 2434. Keep in mind that both rules (federal and state) only apply to pre-1978 construction of housing and child-occupied facilities. The rules do not apply to commercial or industrial structures regardless of when they were constructed.</p>

<hr/>
<h2>Note On The Relationship of the TELRR To EPA's RRP Program Rule</h2>
<p>The primary difference between the <a title="Texas Environmental Lead Reduction Rules (TELRR)" href="/elp/laws-rules.aspx">Texas Environmental Lead Reduction Rules (TELRR)</a> and the federal <a title="EPA Renovation, Repair, and Painting (RRP) Program Rule" href="http://www2.epa.gov/lead/lead-renovation-repair-and-painting-program-rules">EPA Renovation, Repair, and Painting (RRP) Program Rule</a> is that the federal RRP rule regulates renovation, repairs, and painting activities where existing paint may be disturbed while the TELRR regulate lead inspections, lead risk assessments, and lead abatements.</p>
<p>Concerning inspections and testing for lead-based paint in pre-1978 construction, the federal RRP rule allows a certified renovator to test each component affected by the renovation, repair, or painting activity (EPA-approved chemical swab kits are allowed to test components affected by these activities) while the TELRR requires a certified lead inspector or certified lead risk assessor to conduct a surface-by-surface inspection for lead-based paint on all components with a distinct painting history using an x-ray fluorescence (XRF) detector or collecting of representative paint chip samples of each component and having them analyzed by an <a title="EPA-recognized laboratory" href="http://www2.epa.gov/lead/national-lead-laboratory-accreditation-program-list">EPA-recognized laboratory</a> (chemical swab kits are not allowed for testing paint under the TELRR). Under either rule, in the absence of any such test or inspection documentation to show the component lead-free, the paint must be assumed lead-containing.</p>

<hr/>
<h2>Note on the Relationship of the Texas Mold Rules to EPA's RRP Program Rule</h2>
<p>Renovation work by a contractor involving the removal/cleaning of mold-contaminated materials (25 contiguous square feet or greater of visible mold), regardless of the age of the home, is regulated under the <a title="Texas Mold Assessment and Remediation Rules" href="http://texreg.sos.state.tx.us/public/readtac$ext.ViewTAC?tac_view=5&ti=25&pt=1&ch=295&sch=J&rl=Y">Texas Mold Assessment and Remediation Rules (TMARR)</a> administered by the Texas Department of State Health Services (DSHS) Mold Program. As a result, there may also be some overlap of the TMARR and the EPA RRP rule in pre-1978 construction.</p> 
<p>In essence, a DSHS-licensed mold remediation contractor doing renovation projects involving mold in pre-1978 homes may also be required to follow the EPA's RRP rule including being EPA-certified (trained) as a renovator working for a certified (licensed) renovation firm. For information about the applicability of the TMARR, you can contact the <a title="DSHS Mold Program" href="http://www.dshs.state.tx.us/mold/">DSHS Mold Program</a> at 1-512-834-6787, or 1-800-293-0753, and then press "0" for the operator for more information on this issue. </p>

<?php include '/home/codio/workspace/includes/footer.html' ?>