<?php
	$title= "Texas Lead Rules and HUD Rehab Projects" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/elp_menu.html'; 
?>

<p>Policy, Standards, &amp; Quality Assurance Unit, Environmental Hazards Group, September 2011</p>

<hr/>
<p><strong>Download this Document:</strong> <a title="Texas Lead Rules and HUD Rehab Projects" href="http://www.dshs.state.tx.us/workarea/linkit.aspx?linkidentifier=id&amp;ItemID=17248">Texas Lead Rules and HUD Rehab Projects</a> <span class="small">(PDF, 248KB)</span></p>
<hr/>
<h2>Background</h2>
<p>The <strong>Texas Environmental Lead Reduction Rules</strong> (TELRR) have been in effect since February 19, 1996, and cover several areas of lead-based paint activities in housing (also known as “target housing” in the TELRR), including the training and certification of persons conducting lead inspections, risk assessments, abatements, and abatement project designs (regardless of whether any federal assistance is involved in that housing). Lead-based paint inspections conducted in target housing (housing built before 1978) or child-occupied facilities (constructed prior to 1978) can only be conducted by a certified Lead Inspector or certified Lead Risk Assessor in accordance with the TELRR. Lead-based paint abatements in these structures can only be conducted by a certified Lead Firm using a certified Lead Abatement Supervisor and certified Lead Abatement Workers. However, renovation activities are excluded from the definition of lead abatement in the TELRR.</p>
<p>Effective April 22, 2010, the U.S. Environmental Protection Agency’s (EPA) <strong>Renovation, Repair, and Painting (RRP) Program Rule</strong>, requires renovations in target housing and child-occupied facilities to be conducted by EPA-certified (licensed) Renovation Firms using certified Renovators (trained by an EPA-accredited trainer) who must follow the work practice requirements of the rule. The rule requires these certified Renovators to use certain lead-safe techniques to renovate and/or remodel pre-1978 housing as well as in pre-1978 child-occupied facilities. The requirements of the RRP rule are triggered when a renovation, repair or a painting job disturbs more than 6 square feet of existing interior surface paint in a room and/or 20 square feet of existing exterior surface paint on the outside. A certified Renovator could be a remodeler, a carpenter, a multi-family unit maintenance professional, a painter, a window or door replacement professional, or whoever else may disturb paint in pre-1978 construction. For more information, please see the <a title="EPA’s Renovation, Repair, and Painting Program Rule" href="http://www2.epa.gov/lead">EPA’s Renovation, Repair, and Painting Program Rule</a>.</p>
<p>The U.S. Department of Housing and Urban Development’s (HUD) <strong>Lead Safe Housing Rule</strong> (LSHR), which is found in HUD’s regulations at 24 CFR Part 35, Subparts B through M, generally applies to work performed in target housing units receiving HUD housing assistance, such as rehabilitation or acquisition assistance. There are some differences between EPA’s RRP Rule and HUD’s Lead Safe Housing Rule (LSHR). A major difference is that the LSHR requires clearance examinations. All housing receiving federal assistance must still comply with the LSHR. For a comparison of HUD’s LSHR and EPA’s RRP rule and guidance for steps that need to be taken to comply with both rules, please see <a title="HUD Lead-Safe Housing Rule page" href="http://portal.hud.gov/hudportal/HUD?src=/program_offices/healthy_homes/enforcement/lshr">HUD Lead-Safe Housing Rule page</a>.</p>

<hr/>
<h2>Lead Abatement vs. Interim Controls</h2>
<p>Lead abatement involves permanent methods (at least 20 years) of intentionally controlling lead hazards. Conversely, interim controls is not considered abatement and is typically performed in the context of maintaining a property to ensure that lead-based paint hazards that have been identified are at least temporarily (less than 20 years) eliminated to reduce human exposure or likely exposure to those hazards. Likewise, rehabilitation is not considered abatement because the purpose of rehabilitation is not to abate lead hazards, although there may be incidental removal of lead-based paint in the activity. For example, window replacement done for reasons other than to address lead hazards is not considered abatement, even if it results in eliminating lead hazards from the window. Similarly, removal of deteriorated paint to prepare the surface for repainting for the purpose of paint stabilization is an interim control. Furthermore, covering window troughs or other small surfaces with vinyl, aluminum, or other material for the purpose of maintenance or rehab work is not considered an enclosure and, therefore, not abatement. On the other hand, if the removal of the window is for the purpose of abating the lead hazard, this activity is considered abatement. Also, if covering a surface with new drywall, vinyl, or aluminum for the purpose of eliminating (permanently enclosing) lead-based paint exposure underneath, this activity is also considered abatement enclosure). Finally, the project may be considered an abatement if specified as such in the job scope or other project documents.</p>
<p>For federally-assisted rehabilitation projects involving target housing, U.S. Housing and Urban Development (HUD) specifies in their Lead-Safe Housing Rule that the project becomes a lead abatement requiring state-certified workers when federal assistance exceeds $25,000 per unit average or when abatement methods are intentionally used to control lead-based paint hazards. For example, window replacement done to control lead hazards is abatement, regardless of the level of federal assistance. But window replacement conducted as part of rehabilitation and not for the purpose to control lead hazards is not considered an abatement (unless the level of federal assistance exceeds $25,000 per unit), thus not requiring state-certified workers.</p>

<hr/>
<h2>Lead Inspections and Risk Assessments</h2>
<p>Paint chip collection and/or XRF (x-ray fluorescence) analysis are common ways to determine the presence of lead-based paint while chemical test kits are not acceptable as they give inaccurate results for TELRR purposes. Interpretation of the results of the inspection, including assessing any hazards, can only be done by a certified Lead Risk Assessor. In addition, lead hazard screens and any soil or dust sampling can only be done by a certified Lead Risk Assessor (the exception being that a certified Lead Inspector can conduct dust sampling for abatement clearance activities only). Paint chip, soil, or dust samples must be sent to a U.S. Environmental Protection Agency (EPA)- Recognized Laboratory (accredited through the National Lead Laboratory Accreditation Program - NLLAP) for analysis to determine the presence of any lead in the sample. To inquire about EPA- recognized laboratories, call the National Lead Information Center toll-free at (800) 424-LEAD.</p>

<hr/>
<h2>Clearance Sampling and Abatements</h2>
<p>According to the TELRR, lead abatement includes any measure or set of measures designed to permanently eliminate lead-based paint hazards. Abatement includes the removal of paint and dust, the permanent enclosure or encapsulation of lead-based paint, the replacement of painted surfaces or fixtures, or the removal or permanent covering of soil, when lead-based paint hazards are present in such paint, dust or soil. Furthermore, abatement includes all preparation, cleanup, disposal, and post-abatement clearance testing activities associated with such measures. Abatement projects include projects for which there is a written contract or other documentation, which provides that an individual or firm will be conducting activities in or to target housing or child-occupied facilities that shall result in the permanent elimination of lead-based paint hazards, lead contaminated dust or soil hazards, and other lead-based paint hazards. In accordance with Section 295.212(d)(13) of the TELRR, dust wipe clearance levels for abatements are less than 40µg/ft2 for floors/carpets; less than 250µg/ft2 for window sills; and less than 400µg/ft2 for window troughs (wells). All samples collected in connection with abatement, including clearance samples, must be sent to an EPA-Recognized Laboratory for analysis. (Note: The use of an XRF to analyze clearance (dust) samples in the state of Texas is not a recognized method.) Notification of each abatement project, as per Section 295.214 of the TELRR, is required to be made by the certified Lead Abatement Firm to the Texas Department of State Health Services (DSHS), Environmental Health Notifications Group (EHNG), in Austin and to the appropriate DSHS Regional Office at least seven working days (not calendar days) prior to the abatement job. Furthermore, it is the responsibility of the certified Lead Abatement Firm to notify the EHNG and the appropriate DSHS Regional Office of any amendments, cancellations, or emergency notifications.</p>

<hr/>
<h2>Clearance Sampling and Rehabilitation</h2>
<p>Clearance of rehab projects (dust sampling) can be performed to check the effectiveness of the clean-up efforts after rehabilitation is conducted in housing built before 1978. In some cases, dust sampling may be required as part of “clearance”, a defined process to ensure that a work area is not contaminated with lead dust after work is completed. In such cases and in accordance with HUD, dust sampling must be performed by a certified Lead Inspector, Lead Risk Assessor, or a Lead Sampling/Clearance Technician, and is required in properties receiving federal housing assistance. (Note: The use of Lead Sampling/Clearance Technicians is not allowed for determining clearance of abatement projects in the state of Texas.) Clearance is required in many of the rehab jobs in pre-1978 properties that receive federal housing assistance and, according to HUD, must be performed by a trained person independent of the crew performing the work. The property that fails clearance must be re-cleaned and another clearance examination performed. The dust-wipe clearance levels are as follows: less than 40µg/ft2 for floors; less than 250µg/ft2 for window sills (stools); and less than 400µg/ft2 for window troughs (wells). Although EPA’s RRP rule allows for clearance of RRP projects by a cleaning verification procedure using cleaning verification cards, HUD does not allow this on their federally-funded rehab projects. For more information on differences between HUD’s LSHR and EPA’s RRP rule, please see <a title="HUD Lead Safe Housing Rule and the Renovation, Repair and Painting Rule" href="http://www.hud.gov/offices/lead/enforcement/lshr_rrp_changes.cfm">HUD Lead Safe Housing Rule and the Renovation, Repair and Painting Rule</a>.</p>

<hr/>
<h2>For Further Information</h2>
<p>For more information on the U.S. Housing and Urban Development’s (HUD’s) lead-based paint requirements involving federally subsidized target housing, please see the <a title="HUD Lead-Safe Housing Rule page" href="http://portal.hud.gov/hudportal/HUD?src=/program_offices/healthy_homes/enforcement/lshr">HUD Lead-Safe Housing Rule page</a>. Please also see the joint HUD/EPA Clarification Letter on the Title X requirements for rehabilitation and lead hazard reduction in property receiving up to $25,000 per unit in federal rehabilitation assistance under HUD and the Guidance Policy on the application of the joint HUD/EPA Clarification Letter. You can also call the HUD Office of Lead Hazard Control at 202-755-1785.</p>

<?php include '/home/codio/workspace/includes/footer.html' ?>
