<?php
	$title= "Summary of the Texas Lead-Based Paint Rules" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/elp_menu.html'; 
?>

<p>Policy, Standards, &amp; Quality Assurance Unit, Environmental Health Group June 2007</p>

<hr/>
<p><strong>Download this Document:</strong> <a title="" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=17271">Summary of the Texas Lead-Based Paint Rules</a> <span class="small">(PDF, 263KB)</span></p>
<hr/>
<h2>Background</h2>
<p>On February 19, 1996, the Department of State Health Services (DSHS) promulgated the Texas Environmental Lead Reduction Rules (TELRR). These rules cover several areas of lead-based paint activities in housing (also known as "target housing" in the TELRR), including the training and certification of persons conducting lead inspections, risk assessments, abatements, and project design. The rules require that lead training providers be accredited by the DSHS and also set standards for conducting lead-based paint activities. DSHS amended its rules on May 10, 1998, to include child-occupied facilities thus allowing the state to obtain U.S. Environmental Protection Agency (EPA) authorization for a state program pursuant to Section 404 of the Toxic Substances Control Act (TSCA). Then, on March 18, 1999, the State of Texas obtained EPA authorization to administer a Lead-Based Paint Training and Certification Program. On January 5, 2001, the EPA amended Title 40 CFR, Part 745, entitled "Lead; Identification of Dangerous Levels of Lead; Final Rule," which established standards for identifying lead-based paint hazards, work clearance levels, and added amendments to dust and soil sampling requirements. DSHS amended its rules on March 23, 2003, to accommodate these changes and to clarify existing rule language for improved implementation. On December 24, 2004, DSHS amended its rules again to: 1) accommodate the requirement that certifications and accreditations must be two years in length (instead of three years) in accordance with House Bill 2292, 78th Legislature, 2003; and 2) to allow for the collection of license fees online in accordance with Senate Bill 1152, 78th Legislature, 2003, which amended Government Code, Section 2054.111.</p>

<hr/>
<h2>Applicability</h2>
<p>The TELRR applies to target housing and child-occupied facilities built before January 1, 1978. Exclusions, under Section 295.201(b)(2), are housing for the elderly or persons with disabilities, unless a child who is six years of age or younger resides or is expected to reside in that housing, nor do the rules apply to target housing with zero bedrooms. These rules also do not apply to homeowners performing lead-based paint activities in dwellings that they own, unless a person or persons other than the owner or the owner's immediate family occupy the dwelling while the lead activities are being performed. Furthermore, under Section 295.202(69)(B), since a residential dwelling unit is defined as a structure which is occupied, or intended to be used or occupied, in whole or in part, as the home or residence of one or more persons, demolishing of "housing" not meeting this definition is excluded from these rules.</p>

<hr/>
<h2>Lead-Based Paint Inspections</h2>
<p>Any lead-based paint inspection conducted in target housing or child-occupied facilities must be conducted by a certified Lead Inspector or Risk Assessor in accordance with the TELRR. A lead- based paint inspection is a surface-by-surface investigation using approved documented methodologies to determine the presence of lead-based paint in these facilities. If only an assumption is made that lead-based paint may be present (no testing or sampling conducted), a certified Inspector or Risk Assessor is not required. Paint-chip collection and/or XRF (X-ray fluorescence) analysis are common ways to determine the presence of lead-based paintwhile chemical test wipe (swab) kits are not an approved method as they give inaccurate results for TELRR purposes. Paint-chip, soil, or dust samples must be sent to an EPA-Recognized Laboratory (accredited through the National Lead Laboratory Accreditation Program - NLLAP) for analysis to determine the presence of any lead in the sample. To inquire about these EPA-recognized laboratories, call the National Lead Information Center tollfree at (800) 424-LEAD or view the <a title="current listing at the EPA website" href="http://www2.epa.gov/lead/">current listing at the EPA website</a>.</p>

<p>A written lead inspection report must be developed by the certified Lead Inspector or Risk Assessor that includes the information specified in Section 295.212(a)(4) of the TELRR, such as, among other things, the date of inspection, address of building sampled, specific locations (building components) tested for lead-based paint, and copies of all lab analysis reports and downloaded XRF data.</p>

<hr/>
<h2>Lead Hazard Screens</h2>
<p>Any lead-hazard screen conducted in target housing or child-occupied facilities must de done on- site by a certified Lead Risk Assessor in accordance with the TELRR. A lead-hazard screen is an activity that involves limited paint and dust sampling to determine the presence of a lead-based paint hazard. The screen includes the collection of background information regarding the physical characteristics of the residential dwelling or child-occupied facility and occupant use patterns that may cause lead-based paint exposure to one or more children six years of age or younger. It also includes a visual inspection to determine if any deteriorated paint is present, and to locate at least two dust sampling locations. If deteriorated paint is present, each surface with deteriorated paint and having a distinct painting history shall be tested, using approved documented methodologies, for the presence of lead-based paint (chemical test wipe [swab] kits are not an approved method as they give inaccurate results for TELRR purposes). In residential dwellings, two composite dust samples shall be collected, one from the floors and the other from the windows, in rooms, hallways, or stairwells where one or more children, age six or younger, are most likely to come in contact with dust. In multi-family dwellings and child-occupied facilities, in addition to the aforementioned floor and window samples, the certified Lead Risk Assessor shall also collect composite dust samples from any common areas where one or more children six years of age or younger are likely to come into contact with dust. Any dust samples collected must be sent to a EPA-Recognized Laboratory (accredited through the National Lead Laboratory Accreditation Program - NLLAP) for analysis to determine the presence of any lead in the sample. To inquire about these EPA-recognized laboratories, call the National Lead Information Center tollfree at (800) 424-LEAD or view the <a title="current listing at the EPA website" href="http://www2.epa.gov/lead/">current listing at the EPA website</a>.</p>

<p>The certified Lead Risk Assessor shall prepare a written lead hazard screen report that includes the information required in a risk assessment report as specified in Section 295.212(c) of the TELRR, excluding paragraphs (11)(P)-(R), such as, among other things, the date of the screen, physical address of the building sampled, specific locations of each building component tested for lead-based paint and dust-lead hazards, copies of all lab analysis reports and downloaded XRF data, and include recommendations concerning the desirability for follow-up risk assessments. A dust-lead hazard is present when dust sample results are equal to or greater than 40 &#181;g/ft2 for floors and 250 &#181;g/ft2 for interior window sills.</p>

<hr/>
<h2>Lead Risk Assessments</h2>
<p>A risk assessment is an on-site investigation to determine the existence, nature, severity, and location of leadbased paint hazards and the presence of lead in deteriorated paint and friction surfaces. The certified Lead Risk Assessor must prepare a written lead risk assessment report that includes the information specified in Section 295.212(c) of the TELRR, such as, among other things, the date of the risk assessment, physical address of the building sampled, specific locations of each building component tested for lead-based paint, copies of all lab analysis reports and downloaded XRF data, and an explanation of the results of the investigation and options for reducing lead-based paint hazards including a description of interim controls (i.e., operations and maintenance) and/or abatement options for each lead-based paint hazard. If an encapsulant or enclosure is recommended, then a maintenance and monitoring schedule shall be included in the risk assessment report. A dust lead hazard is present when dust sample results are equal to or greater than 40 &#181;g/ft2 for floors and 250 &#181;g/ft2 for interior window sills. A soil-lead hazard from lead-based paint is present when a play area sample of bare soil is equal to or greater than 400 parts per million (ppm); or in the rest of the yard (i.e., non-play areas) when the bare soil sample is equal to or greater than 1,200 ppm.</p>

<hr/>
<h2>Lead Abatements and Clearance Issues</h2>
<p>According to the TELRR, lead abatement includes any measure or set of measures designed to permanently eliminate lead-based paint hazards. Abatement includes the removal of paint and dust, the permanent enclosure or encapsulation of lead-based paint, the replacement of painted surfaces or fixtures, or the removal or permanent covering of soil, when lead-based paint hazards are present in such paint, dust or soil. Furthermore, abatement includes all preparation, cleanup, disposal, and post-abatement clearance testing activities associated with such measures.</p>

<p>Abatement projects include projects for which there is a written contract or other documentation, which provides that an individual or firm will be conducting activities in or to target housing or child-occupied facilities that shall result in the permanent elimination of lead-based paint hazards, lead contaminated dust or soil hazards, and other lead-based paint hazards. In accordance with Section 295.212(d)(13) of the TELRR, dust wipe clearance levels for abatements are less than 40&#181;g/ft2 for floors/carpets; less than 250&#181;g/ft2 for window sills; and less than 400&#181;g/ft2 for window troughs (wells).</p>

<p>All lead-based paint abatements in target housing or child-occupied facilities usually must have as a minimum the following certified entities involved: a certified Lead Abatement Firm; a certified Lead Abatement Supervisor to oversee the project; certified Lead Abatement Workers to work under an abatement supervisor; and a certified Lead Inspector or Lead Risk Assessor to do clearance testing of the abatement. All samples collected in connection with an abatement, including clearance samples, must be sent to an EPA-Recognized Laboratory for analysis. Larger projects may require the services of a certified Lead Abatement Project Designer. Certified individuals working on an abatement site are required to have in their possession a current department-issued certification identification (ID) card. Additionally, in accordance with Section 295.212(d)(5) of the TELRR, a certified Lead Abatement Supervisor or a certified Lead Abatement Project Designer must develop a written Occupant Protection Plan for each abatement project, and this document must be at the worksite at all times during the abatement activity by the certified Lead Abatement Firm. Unless presumed lead, a copy of the lead inspection or lead risk assessment report prepared for the lead abatement project shall be kept at the worksite by the certified lead abatement firm and be available for department inspection in accordance with 295.212(d)(6). Specific work practice standards, as referenced in Section 295.212(d)(7) of the TELRR, must be followed at all abatement jobs.</p>

<hr/>
<h2>Notifying DSHS of Lead-Based Paint Abatement Activity</h2>
<p>Notification of each abatement project, as per Section 295.214 of the TELRR, is required to be made by the certified Lead Abatement Firm to the DSHS Environmental Health Notifications Group (EHNG) in Austin, and to the appropriate DSHS Regional Office at least seven (7) working days prior to the abatement job. Furthermore, it is the responsibility of the certified Lead Abatement Firm to notify the DSHS Notifications Group and the appropriate DSHS Regional Office (http://www.dshs.state.tx.us/elp/regions.shtm) of any amendments, cancellations, or emergency notifications.</p>

<hr/>
<h2>Exclusions to Abatements</h2>
<p>The TELRR, under Section 295.202(51)(B), specifically excludes from the definition of abatement any renovation, remodeling, and landscaping activities which are not designed to permanently eliminate lead-based paint hazards, but, instead, are designed to repair, restore, or remodel a given structure or dwelling, even though these activities may incidentally result in a reduction or elimination of lead-based paint hazards. However, if activities being conducted are intended to permanently eliminate lead hazards, these activities are considered abatement. This is determined when abatement is specified in project specifications, job write-ups, bid contracts, or similar documents.</p>

<p>When the primary purpose of work is rehabilitation with no intent to permanently remove lead-based paint, this activity is not considered abatement. However, if any part of the rehabilitation project involves funds with the intent to permanently remove lead-based paint, then this activity must be considered abatement and is subject to the TELRR. The TELRR definition of abatement also excludes interim control activities, operations and maintenance activities, or other measures designed to only temporarily, but not permanently, reduce lead-based paint hazards. Also, the definition of abatement excludes demolition of target housing buildings and child-occupied facilities.</p>

<h2>For More Information</h2>
<p>Please contact the Department of State Health Services at (512) 834-6600, ext. 2434, or toll-free in Texas at 888-778-9440 if you have any lead-based paint questions. You can also visit the DSHS <a title="Environmental Lead Program website" href="http://www.dshs.state.tx.us/elp">Environmental Lead Program website</a>  to download certification applications and the TELRR, and to obtain further information.</p>

<?php include '/home/codio/workspace/includes/footer.html' ?>
