<?php
	$title= "Food Handler Certification" ;
	include '../includes/header.html';
    include '../includes/menus/foodhand_menu.html'; 
?>

<p>The Food Handler Education or Training Program (FHP) §229.178 is based on Senate Bill (SB) 552 of the 80th Legislature (2007), regarding the accreditation of basic food safety education or training programs for food handlers. </p>
<p>This rule is intended to provide the framework for the accrediting food safety education or training programs for food handlers. A uniform standard governing the accreditation of food handler programs enhances the recognition of reciprocity among regulatory agencies and reduces the expense of duplicate education incurred when food handlers work in multiple regulatory jurisdictions. Education of the food handlers provides more qualified employees, thereby reducing the risk of foodborne illness outbreaks caused by improper food preparation and handling techniques.</p>
<p>The Texas Department of State Health Services, Food Handler Program, along with the Certified Food Manager Program, is dedicated to the health and safety of the citizens of the state, educating food service employees in the principles of food safety to produce safe food products for Texas consumers. </p>
<p>Please email the <a title="Food Handler Program" href="mailto:cfm.bfds@dshs.state.tx.us?subject=Food Handler Program">Certified Food Manager Program</a> if you would like additional information, or telephone (512) 834-6727.</p>
<hr />
<ul>
	<li><a title="Applications" href="http://www.dshs.state.tx.us/fdlicense/apps.shtm#fhapp" target="_blank">Applications</a></li>
	<li><a title="Accredited Food Handler Training Programs" href="#training">Accredited Food Handler Training Programs</a></li>
	<li><a title="Accredited Food Handler Training Programs &quot;Sample Certificates&quot;" href="#sample">Accredited Food Handler Training Programs "Sample Certificates"</a></li>
	<li><a title="Frequently Asked Questions (FAQs)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlerFAQ.pdf" target="_blank">Frequently Asked Questions (FAQs)</a></li>
	<ul>
		<li><a title="Food Handler Education or Training Program" href="http://www.dshs.state.tx.us/foodestablishments/pdf/foodhandlerfaq.pdf" target="_blank"><font color="#0066cc">Food Handler Education or Training Program</font></a>   <span class="style2"><font size="1">(PDF 21KB)</font></span></li>
		<li><a title="How to Become an Accredited Food Handler Program" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FHP_FAQ.pdf" target="_blank">How to Become an Accredited Food Handler Program</a><span class="style2"><font size="1">  (PDF 21KB)</font></span>   </li>
	</ul>
	<li><a title="Information" href="#info">Information</a></li>
	<li><a title="Publications" href="http://www.dshs.state.tx.us/foodestablishments/pubs.shtm#FHP" target="_blank">Publications</a></li>
</ul>
<hr />
<h2><a title="training" class="bookmark" name="training"></a>Accredited Food Handler Training Programs</h2>
<h3><a title="Accredited Classroom Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589992781">Accredited Classroom Training</a><span class="style2"><font size="1">  (PDF 40KB)</font></span></h3>
<h3><a title="Accredited Online Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993243">Accredited Online Training</a>  <span class="style2"><font size="1">(PDF 33KB)</font></span></h3>
<h3><a title="Accredited Private Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/12-19-13-PRIVATE.pdf">Accredited Private Training</a>  -- Accredited PRIVATE Food Handler Programs DO NOT offer training to the public.  <span class="style2"><font size="1">(PDF 87KB)</font></span></h3>
<h3><a title="Top of Page" class="style2" href="#TopOfPage"><font color="#000066" size="1">Top of Page</font></a></h3>
<hr />
<h2><a name="sample"></a><a title="sample" class="bookmark" name="sample"></a>Accredited Food Handler Training Programs "Sample Certificates"</h2>
<p>All Food Handler Certificates now display a watermark in the form of text, graphics or background. The watermarks were added June 1, to September 28, 2009, to ensure certificate authenticity. If you have a question regarding a food handler certificate, please contact the issuing Food Handler Program for information or verification.</p>
<p><a title="A + Food Industry Inspections, Inc." href="http://www.dshs.state.tx.us/foodestablishments/pdf/A-Food-Industry-Inspections-Inc.pdf">A + Food Industry Inspections, Inc.</a>   <span class="style2"><font size="1">(PDF 85KB)</font></span> </p>
<p><a title="Absolutely Certified Texas Food Handler Program" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Absolutely-Certified-Texas-Food-Handler.pdf">Absolutely Certified Texas Food Handler Program</a> <font size="1">(PDF 1,324 KB)</font></p>
<p><a title="Adept On-Site Services" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589967390">Adept On-Site Services</a> Effective May 7, 2012  <span class="style2"><font size="1">(PDF 116 KB)</font></span></p>
<p><a title="Adept On-Site Services" href="http://www.dshs.state.tx.us/foodestablishments/pdf/AdeptOn-SiteServices.pdf" target="_blank">Adept On-Site Services</a> Prior to May 7, 2012   <span class="style2"><font size="1">(PDF 45KB)</font></span></p>
<p><span class="style2"><a title="Advance Service Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589943240" target="_blank">Advance Service Training</a>   <span class="style2"><font size="1">(PDF 1.3MB)</font></span> </span></p>
<p><a title="Allen I. S. D. Student Nutrition Program" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589937927" target="_blank">Allen I. S. D. Student Nutrition Program</a>   <span class="style2"><font size="1">(PDF 29KB)</font></span></p>
<p><a title="Brookshire Grocery Company" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589958731">Brookshire Grocery Company</a><span class="style2"><font size="1">(PDF 201KB)</font></span></p>
<p><a title="Caritas of Austin" href="http://www.dshs.state.tx.us/foodestablishments/pdf/CaritasofAustin.pdf">Caritas of Austin</a> <span class="style2"><font size="1">(PDF 269KB)</font></span></p>
<p><a title="Child Inc&amp;nbsp;" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ChildInc.pdf" target="_blank">Child Inc </a>   <span class="style2"><font size="1">(PDF 61KB)</font></span></p>
<p><a title="City of Austin EHS Food Handler Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589965355">City of Austin EHS Food Handler Training</a>   <span class="style2"><font size="1">(PDF 82 KB)</font></span></p>
<p><a title="City of Baytown Food Handler Certificate" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968483">City of Baytown Food Handler Certificate</a> <span class="style2"><font size="1">(PDF 127 KB)</font></span></p>
<p><span class="style2"><a title="CST SERVICES LLC" href="http://www.dshs.state.tx.us/foodestablishments/pdf/CSTServicesLLC052013.pdf">CST SERVICES LLC</a> (Formerly  Valero Retail Holding Inc.)  <font size="1">(PDF 278KB)</font> </span></p>
<p><span class="style2"><a title="DFW Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589974711">DFW Food Handlers</a><font size="1"> -</font> Effective February 5, 2013<font size="1"> (PDF 191KB)</font></span></p>
<p><a title="DFW Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972882">DFW Food Handlers</a> - Prior to February 5, 2013 <span class="style2"><font size="1">(PDF 450KB)</font></span></p>
<p><a title="eFoodHandlers" href="http://www.dshs.state.tx.us/foodestablishments/pdf/eFoodHandlersInc.pdf">eFoodHandlers</a> <span class="style2"><font size="1">(PDF 65KB)</font></span></p>
<p><a title="El Paso Food Handlers" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ElPasoFoodHandlers.pdf" target="_blank">El Paso Food Handlers</a>   <span class="style2"><font size="1">(PDF 209KB)</font></span>  (Now known as <a title="Food Handlers of Texas" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlersOfTexasSample.pdf" target="_blank">Food Handlers of Texas</a>  <span class="style2"><font size="1">(PDF 205KB)</font></span></p>
<p><a title="First Defense Food Handler Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FirstDefenseFoodhandlerTraining.pdf" target="_blank">First Defense Food Handler Training</a>   <span class="style2"><font size="1">(PDF 28KB)</font></span></p>
<p><a title="Food Handler Classes" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlerClasses.pdf" target="_blank">Food Handler Classes</a> License #8  <span class="style2"><font size="1">(PDF 221KB)</font></span></p>
<p><a title="Food Handler Classes" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935975" target="_blank">Food Handler Classes</a> License #41  <span class="style2"><font size="1">(PDF 68KB)</font></span></p>
<p><a title="Food Handlers of Texas" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlersOfTexasSample.pdf" target="_blank">Food Handlers of Texas</a>  <span class="style2"><font size="1">(PDF 205KB)</font></span>  (formerly <a title="El Paso Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18713" target="_blank">El Paso Food Handlers</a>   <span class="style2"><font size="1">(PDF 78KB)</font></span>)    </p>
<p><a title="Food Marketing Institute (FMI)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FMI.pdf" target="_blank">Food Marketing Institute <span class="style3"><font size="1">(FMI)</font></span></a>   <span class="style3"><font size="1"><span class="style2">(PDF 412KB)</span></font></span></p>
<span class="style3"><span class="style2"><p><a title="Food Safety Direct (in English)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Food-Safety-Direct---English.pdf">Food Safety Direct (in English)</a><font size="1">   <span class="style2"><font size="1">(PDF 253KB)</font></span></font></p>
	<span class="style2"><p><a title="Food Safety Direct (in Spanish)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Food-Safety-Direct---Spanish.pdf">Food Safety Direct (in Spanish)</a><font size="1">  <span class="style2"><font size="1">(PDF 268KB)</font></span></font></p>
	</span></span></span><p><a title="Food Safety International, L.L.C." href="http://www.dshs.state.tx.us/foodestablishments/pdf/FSI.pdf" target="_blank">Food Safety International, L.L.C.</a>   <span class="style2"><font size="1">(PDF 604KB)</font></span></p>
	<p><a title="Food Safety Sense" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodSafetySenseCard2014.pdf">Food Safety Sense</a> - Effective March 26, 2014  <span class="style2"><font size="1">(PDF 126KB)</font></span></p>
	<p><a title="Food Safety Sense" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodSafetySense.pdf" target="_blank">Food Safety Sense</a> - Prior to March 26, 2014   <span class="style2"><font size="1">(PDF 88KB)</font></span></p>
	<p><span class="style2"><a title="Food Safety Training Course" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodSafetyTrainingCourse.pdf">Food Safety Training Course</a><span class="style2"><font size="1">(PDF 70KB)</font></span></span></p>
	<p><a title="Healthinspectionorg" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589936213" target="_blank">Healthinspectionorg</a>   <span class="style2"><font size="1">(PDF 375KB)</font></span></p>
	<p><a title="Jack in the Box" href="http://www.dshs.state.tx.us/foodestablishments/pdf/JackintheBox.pdf" target="_blank">Jack in the Box</a>   <span class="style2"><font size="1">(PDF 121KB)  </font></span></p>
	<p><a title="Learn2Serve.com Effective Effective June 2014" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Learn2Serve-com06_2014.pdf">Learn2Serve.com Effective Effective June 2014</a><span class="style2"><font size="1">(PDF 653KB)</font></span></p>
	<p><a title="Learn2Serve.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Learn2Serve-com-6_13.pdf">Learn2Serve.com</a>  Effective Prior to June 2014 <span class="style2"><font size="1">(PDF 121KB)  </font></span></p>
	<p><a title="Learn2Serve.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Learn2ServeFH.pdf" target="_blank">Learn2Serve.com</a>   Prior to June 4, 2013 <span class="style2"><font size="1">(PDF 172KB)</font></span></p>
	<p><a title="Le Cordon Bleu" href="http://www.dshs.state.tx.us/foodestablishments/pdf/LCB.pdf" target="_blank">Le Cordon Bleu</a>  <span class="style2"><font size="1">(PDF 103KB)</font></span>  (formerly <a title="Texas Culinary Academy" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TCA.pdf" target="_blank">Texas Culinary Academy</a> <span class="style2"><font size="1">PDF 106KB</font></span>)</p>
	<p><a title="Lone Star Food Safety" href="http://www.dshs.state.tx.us/foodestablishments/pdf/LoneStarFoodSafety.pdf">Lone Star Food Safety</a>  <span class="style2"><font size="1">(PDF 663KB)</font></span></p>
	<p><span class="style2"><a title="MarksSafetyConsultSvcSampleCertEffDecember" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SampleCerts/MarksSafetyConsultSvcSampleCertEffDecember.pdf">Marks Safety Consultant Service</a> - <span>Effective December 2014</span><font size="1">   (PDF 865KB)</font></span></p>
	<p><span class="style2"><span class="style2"><a title="MarksSafetyConsultSvcSampleCertPrior" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SampleCerts/MarksSafetyConsultSvcSampleCertPrior.pdf">Marks Safety Consultant Service</a> - <span>Prior to December 2014</span><font size="1">   (PDF 865KB)</font></span></span></p>
	<p><a title="MindLeaders, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935888" target="_blank">MindLeaders, Inc.</a> Prior to October 2014 – Now known as Skillsoft Corporation  <span class="style2"><font size="1">(PDF 142KB)</font></span></p>
	<p><a title="Mineral Wells, City of" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589992501">Mineral Wells, City of</a>  Effective October 2014 (PDF 62KB)</p>
	<p><a title="Mineral Wells, City of" href="http://www.dshs.state.tx.us/foodestablishments/pdf/MineralWellsCityof.pdf" target="_blank">Mineral Wells, City of</a>  Prior to October 2014 <span class="style2"><font size="1">(PDF 62KB)</font></span></p>
	<p><a title="Ms. Ree's Food Safety" href="http://www.dshs.state.tx.us/foodestablishments/pdf/MsReesFoodSafety.pdf" target="_blank">Ms. Ree's Food Safety</a>   <span class="style2"><font size="1">(PDF 121KB)</font></span></p>
	<p><a title="MyFoodHandler.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/MyFoodHandler-Com.pdf">MyFoodHandler.com</a> (1MB)</p>
	<p><a title="National Registry of Food Safety Professionals" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NationalRegistryFoodSafetyProf.pdf">National Registry of Food Safety Professionals</a> Effective February 13, 2013 <span class="style2"><font size="1">(PDF 152KB)</font></span></p>
	<p><a title="National Registry of Food Safety Professionals" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NationalRegistryFoodSafety.pdf" target="_blank">National Registry of Food Safety Professionals</a> Prior to February 13, 2013   <span class="style2"><font size="1">(PDF 294KB)</font></span></p>
	<p><a title="NEHA Food Safety Training&amp;nbsp;" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NEHA.pdf" target="_blank">NEHA Food Safety Training </a>   <span class="style2"><font size="1">(PDF, 1.54MB, Large File, Long Download)</font></span></p>
	<p><a title="Northwest Texas Educational Services" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NorthwestTexasEducationalSvc.pdf" target="_blank">Northwest Texas Educational Services</a>   <span class="style2"><font size="1">(PDF 205KB)</font></span><span class="style2"> </span></p>
	<p><span class="style2"></span><a title="Plano, City of" href="http://www.dshs.state.tx.us/foodestablishments/pdf/PlanoFoodHandlerCert.pdf" target="_blank">Plano, City of</a>   <span class="style2"><font size="1">(PDF 37KB)</font></span></p>
	<p><span class="style2"><a title="Premier Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589964510">Premier Food Safety</a> Effective February 23, 2012 <span class="style2"><font size="1">(PDF 731KB)</font></span></span></p>
	<p><span class="style2"></span><span class="style2"><a title="Premier Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589960968">Premier Food Safety</a>   Prior to February 23, 2012 <span class="style2"><font size="1">(PDF 731KB)</font></span></span><span class="style2"><span class="style2"> </span></span></p>
	<p><span class="style2"><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589983906">Professional Server Certification Corporation</a> Effective January 2, 2014 <font size="1">(PDF 1MB)</font></span></p>
	<p><span class="style2"></span><span class="style2"><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589983905">Professional Server Certification Corporation</a> Wallet Card Effective January 2, 2014 <font size="1">(PDF 183KB)</font></span></p>
	<p><span class="style2"><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodHandler_Updated.pdf">Professional Server Certification Corporation</a> Prior September 15, 2011  <font size="1">(PDF 83KB)</font></span></p>
	<p><span class="style2"></span><span class="style2"><span class="style2"><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589946917" target="_blank">Professional Server Certification Corporation</a><font size="1"><font size="1">  </font></font>Prior March 7, 2011   <font size="1"><font size="1">(PDF 138KB)</font></font></span></span></p>
	<p><span class="style2"><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589942169" target="_blank">Professional Server Certification Corporation</a><font size="1">  </font>Prior to March 7, 2011      <font size="1">(PDF 138KB) </font></span></p>
	<p><a title="Public Health Education" href="http://www.dshs.state.tx.us/foodestablishments/pdf/PublicHealthEducation.pdf" target="_blank">Public Health Education</a>   <span class="style2"><font size="1">(PDF 83KB)</font></span></p>
	<p><span class="style2"><a title="RaceTrac Petroleum, Inc." href="http://www.dshs.state.tx.us/foodestablishments/pdf/RaceTracPetroleumInc2014.pdf">RaceTrac Petroleum, Inc.</a> Effective January 10, 2014 <span class="style2"><font size="1">(PDF 264KB)</font></span></span></p>
	<p><span class="style2"></span><span class="style2"><a title="RaceTrac Petroleum, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589963657">RaceTrac Petroleum, Inc.</a>  Prior to January 10, 2014 <span class="style2"><font size="1">(PDF 176KB)</font></span></span></p>
	<p><span class="style2"><span class="style2"><a title="Safe Food Solutions" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Safe-Food-Solutions-LLC.pdf">Safe Food Solutions</a> #59 - Effective July 2014</span></span></p>
	<span class="style2"><span class="style2"><p><a title="Safe Food Solutions" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968516">Safe Food Solutions</a>  <font size="1">(PDF 162KB)</font><font size="3"> - Prior to July 2014</font></p>
	</span></span><p><span class="style2"><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972811">Safe Food 4 U</a> - License # 55 - Effective November 2012 <span class="style2"><font size="1">(PDF 146KB)</font></span></span></p>
	<p><span class="style2"><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972810">Safe Food 4 U</a> - License # 14 - Effective November 2012 <span class="style2"><font size="1">(PDF 72KB)</font></span>  </span></p>
	<p><span class="style2"><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935511" target="_blank">Safe Food 4 U</a> - Prior to November 2012  <span class="style2"><font size="1">(PDF 165KB)</font></span></span></p>
	<p><span class="style2"><a title="Safe Food 4 U (Spanish)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589965906">Safe Food 4 U (Spanish)</a><span class="style2"><font size="1">(PDF 99KB)</font></span></span></p>
	<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SafeFood4U.pdf" target="_blank">Safe Food 4 U</a>  -  Prior to October 12, 2010 <span class="style2"><font size="1">(PDF 174KB)</font></span></p>
	<p><a title="StateFoodTest.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972812">SafeFoodTest.com</a> - <font size="1">(PDF 3MB)</font></p>
	<p><a title="Sam Houston State University" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SamHoustonStateUniversity.pdf" target="_blank">Sam Houston State University</a>   <span class="style2"><font size="1">(PDF 210KB)</font></span></p>
	<p><a title="ServSafe Starters - Classroom" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SerSafeStartersClassroom.pdf" target="_blank">ServSafe Starters - Classroom</a>   <span class="style2"><font size="1">(PDF 176KB)</font></span></p>
	<p><a title="ServSafe Starters - Online" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ServSafeStartersOnline.pdf" target="_blank">ServSafe Starters - Online</a>   <span class="style2"><font size="1">(PDF 234KB)</font></span></p>
	<p><a title="Skillsoft Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993241">Skillsoft Corporation</a> - License # 39 - Effective October 2014 – Formerly MindLeaders Inc.  <span class="style2"><font size="1">(PDF 112KB)</font></span></p>
	<p><a title="State Educational Systems, LLC" href="http://www.dshs.state.tx.us/foodestablishments/pdf/StateEducationalSystemsLLC.pdf" target="_blank">State Educational Systems, LLC</a>   <span class="style2"><font size="1">(PDF 953KB)</font></span></p>
	<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993430">StateFoodSafety.com</a> - License # 3 - Effective November 2014 <span class="style2"><font size="1">(PDF 808KB)</font></span></p>
	<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/StateFoodSafety-Com_08_2014.pdf">StateFoodSafety.com</a> - License # 3 -- Prior to November 2014 <span class="style2"><font size="1">(PDF 63KB)</font></span></p>
	<p><a title="StateFoodSafety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589970268">StateFoodSafety.com</a> - License # 38 - Prior August 2014 <span class="style2"><font size="1">(PDF 335KB)</font></span></p>
	<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935918" target="_blank">StateFoodSafety.com</a> - License #38  - Prior August 2012 <span class="style2"><font size="1">(PDF 236KB)</font></span></p>
	<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18760" target="_blank">StateFoodSafety.com</a> - License #3 - Prior to November 12, 2010<span class="style2"><font size="1">    (PDF 64KB)</font></span></p>
	<p><a title="Sonic Drive-In" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SonicDrive-In.pdf">Sonic Drive-In</a>  <span class="style2"><font size="1">(PDF 2MB)</font></span></p>
	<p><a title="Stripes" href="http://www.dshs.state.tx.us/foodestablishments/pdf/stripes.pdf" target="_blank">Stripes</a>   <span class="style2"><font size="1">(PDF 84KB)</font></span></p>
	<p><a title="Texas A&amp;amp;M AgriLife Extension Service License # 76 " href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas-AM-AgriLife-Extension-Service-License---76.pdf">Texas A&amp;M AgriLife Extension Service License # 76 </a>- Effective July 2014</p>
	<p><a title="Texas AgriLife Extension Service" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589969466">Texas A&amp;M AgriLife Extension Service License #6</a> - Effective April 2012  <span class="style2"><font size="1">(PDF 88KB)</font></span></p>
	<p><a title="Texas AgriLife Extension Service" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas_20AgriLife.pdf" target="_blank">Texas A&amp;M AgriLife Extension Service License #6</a> - Prior to April 21, 2012  <span class="style2"><font size="1">(PDF 55KB)</font></span></p>
	<p><a title="Texas Best Food Services Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasBestFoodServicesTraining.pdf">Texas Best Food Services Training</a> (3MB)</p>
	<p><a title="Texas Culinary Academy" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TCA.pdf" target="_blank">Texas Culinary Academy</a>   <span class="style2"><font size="1">(PDF 106KB)</font></span> - (Now known as <a title="Le Cordon Bleu" href="http://www.dshs.state.tx.us/foodestablishments/pdf/LCB.pdf" target="_blank">Le Cordon Bleu</a>  (<span class="style2"><font size="1">PDF 103KB</font></span>)</p>
	<p><a title="TexasFoodCard.com license" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodCardCom2014.pdf">TexasFoodCard.com license</a> # 21- Effective December 2014 (<span class="style2"><font size="1">PDF 328MB</font></span>)</p>
	<p><a title="TexasFoodCard.com, license" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993112">TexasFoodCard.com, license</a> # 21- Prior to December 2014 (<span class="style2"><font size="1">PDF 8MB</font></span>)</p>
	<p><a title="Texas foodcard.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texasfoodcardcom.pdf" target="_blank">Texas FoodCard.com</a> - Prior to October 2014 <span class="style2"><font size="1">(PDF 577KB)</font></span></p>
	<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodHandler06_2013-com.pdf">TexasFoodHandler.com/Safeway Certifications</a> - Effective June 2013 <span class="style2"><font size="1">(PDF 246KB</font></span>)</p>
	<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968423">TexasFoodHandler.com/Safeway Certifications</a> - Prior to June 2013 (<span class="style2"><font size="1">PDF 800KB</font></span>)</p>
	<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodHandlercom.pdf" target="_blank">TexasFoodHandler.com/Safeway Certifications</a>  - Prior to May 2012 <span class="style2"><font size="1">(PDF 550KB)</font></span></p>
	<p><a title="Texas Food Safety Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas-Food-Safety-Training.pdf">Texas Food Safety Training</a>  <span class="style2"><font size="1">(PDF 3423KB)</font></span></p>
	<p><span class="style2"><a title="Texas Online Food Handler" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasOnlineFoodHandlerProgram.pdf">Texas Online Food Handler</a> <span class="style2"><font size="1">(PDF 300 KB)</font></span></span></p>
	<p><a title="Texas State University - San Marcos Food Handler Program" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas-State-University---San-Marcos.pdf">Texas State University - San Marcos Food Handler Program</a>  <span class="style2"><font size="1">(PDF 383KB)</font></span></p>
	<p><a title="Texoma Food Service" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexomaFoodService.pdf" target="_blank">Texoma Food Service</a>   <span class="style2"><font size="1">(PDF 108KB)</font></span></p>
	<p><a title="Thornhill Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972506">Thornhill Training</a> - Effective November 2012 <font size="1">(PDF </font><font size="1">293KB)</font></p>
	<p><a title="Thornhill Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ThornhillTraining.pdf" target="_blank">Thornhill Training</a>  - Prior to November 2012 <span class="style2"><font size="1">(PDF 94KB)</font></span></p>
	<p><a title="Tokyo Gardens Catering, LLC" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TGCFoodHandlerCertificate.pdf" target="_blank">Tokyo Gardens Catering, LLC</a>   <span class="style2"><font size="1">(PDF 360KB)</font></span></p>
	<p><span class="style2"><a title="Training Achievement Program (TAP series)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Training-Achievement-Program-(TAP-Series)2014.pdf">Training Achievement Program (TAP series)</a> Effective June 2014 <span class="style2"><font size="1">(PDF 88KB)</font></span></span></p>
	<p><span class="style2"></span><a title="Training Achievement Program (TAP series)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968521">Training Achievement Program (TAP series)</a> Prior to June 2014 <span class="style2"><font size="1">(PDF 1MB)</font></span></p>
	<p><a title="United Supermarkets" href="http://www.dshs.state.tx.us/foodestablishments/pdf/UnitedSupermarkets.pdf" target="_blank">United Supermarkets</a>   <span class="style2"><font size="1">(pdf 54KB)</font></span></p>
	<p><span class="style2"><a title="One Valero Way" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589946918" target="_blank">Valero Retail Holdings, Inc.</a> (Now known as CST Services LLC)  <span class="style2"><font size="1">(PDF 742KB) </font></span></span></p>
	<p><a title="Wal-Mart" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Wal-Mart-Stores-Texas.pdf" target="_blank">Wal-Mart</a>   <span class="style2"><font size="1">(PDF 658KB)</font></span></p>
	<p><a title="Western Refining" href="http://www.dshs.state.tx.us/foodestablishments/pdf/WesternRefining.pdf">Western Refining</a> <span class="style2"><font size="1">(pdf  324KB)</font></span></p>
	<p><a title="Whole Foods Markets - Southwest" href="http://www.dshs.state.tx.us/foodestablishments/pdf/WholeFoods.pdf">Whole Foods Markets - Southwest</a>   <span class="style2"><font size="1">(PDF 121KB)</font></span></p>
	<p><a title="Woody's Training in Texas" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Woody_sTraininginTexas.pdf" target="_blank">Woody's Training in Texas</a>   <span class="style2"><font size="1">(PDF 60KB)</font></span></p>
	<p><a title="World Credential Diagnostic" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589958631">World Credential Diagnostic</a> (<span class="style2"><font size="1">PDF 328KB)</font></span></p>
	<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/www-TrainingNow-com01_07_14.pdf">www.TrainingNow.com</a>  Effective January 7, 2014 <font size="1">(PDF 194KB)</font></p>
	<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589976686">www.TrainingNow.com</a> Prior to January 7, 2014 <font size="1">(PDF 961KB)</font></p>
	<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589971977">www.TrainingNow.com</a> Prior to April 26, 2013  <span class="style2"><font size="1">(PDF 341KB)</font></span></p>
	<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TrainingNow_com.pdf" target="_blank">www.TrainingNow.com</a>  Prior to November 5, 2012 <span class="style2"><font size="1">(PDF 60KB)</font></span></p>
	<p><a title="Zepol Dietary Consults" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Zepol-Dietary-Consults2014.pdf">Zepol Dietary Consults</a> Effective April 1, 2014 <span class="style2"><font size="1">(PDF 955KB</font></span>) </p>
	<p><a title="Zepol Dietary Consults" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ZepolDietaryConsults.pdf" target="_blank">Zepol Dietary Consults</a> Proior to April 1, 2014   <span class="style2"><font size="1">(PDF 104KB)</font></span></p>
	<p>  <a title="Top of Page" class="style2" href="#TopOfPage"><font color="#000066" size="1">Top of Page</font></a></p>
	<hr />
	<h2><a name="info"></a><a title="info" class="bookmark" name="info"></a>Information</h2>
	<p><a title="&quot;Rule for Food Handler Education or Training Program 25 TAC §229.178&quot; Document" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlerRule.pdf" target="_blank"><font color="#000066">"Rule for Food Handler Education or Training Program 25 TAC §229.178" Document</font></a> <span class="style2"><font size="1">(PDF file, 35KB)</font></span></p>
	<p><span class="style2"></span></p>
	
	<?php include '../includes/footer.html' ?>	