<?php
	$title= "Sample Certificates - Food Handler Certification" ;
	include '../includes/header.html';
    include '../includes/menus/foodhand_menu.html'; 
?>

<h2><a name="sample"></a><a title="sample" class="bookmark" name="sample"></a>Accredited Food Handler Training Programs "Sample Certificates"</h2>
<p>All Food Handler Certificates now display a watermark in the form of text, graphics or background. The watermarks were added June 1, to September 28, 2009, to ensure certificate authenticity. If you have a question regarding a food handler certificate, please contact the issuing Food Handler Program for information or verification.</p>
<p><a title="A + Food Industry Inspections, Inc." href="http://www.dshs.state.tx.us/foodestablishments/pdf/A-Food-Industry-Inspections-Inc.pdf">A + Food Industry Inspections, Inc.</a> <span class="small">(PDF, 85KB)</span> </p>
<p><a title="Absolutely Certified Texas Food Handler Program" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Absolutely-Certified-Texas-Food-Handler.pdf">Absolutely Certified Texas Food Handler Program</a> <span class="small">(PDF 1.3MB)</span></p>
<p><a title="Adept On-Site Services" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589967390">Adept On-Site Services</a> Effective May 7, 2012  <span class="small">(PDF, 116KB)</span></p>
<p><a title="Adept On-Site Services" href="http://www.dshs.state.tx.us/foodestablishments/pdf/AdeptOn-SiteServices.pdf">Adept On-Site Services</a> Prior to May 7, 2012   <span class="small">(PDF, 45KB)</span></p>
<p><a title="Advance Service Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589943240">Advance Service Training</a> <span class="small">(PDF, 1.3MB)</span> </p>
<p><a title="Allen I. S. D. Student Nutrition Program" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589937927">Allen I. S. D. Student Nutrition Program</a> <span class="small">(PDF, 29KB)</span></p>
<p><a title="Brookshire Grocery Company" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589958731">Brookshire Grocery Company</a> <span class="small">(PDF, 201KB)</span></p>
<p><a title="Caritas of Austin" href="http://www.dshs.state.tx.us/foodestablishments/pdf/CaritasofAustin.pdf">Caritas of Austin</a> <span class="small">(PDF, 269KB)</span></p>
<p><a title="Child Inc&amp;nbsp;" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ChildInc.pdf">Child Inc </a> <span class="small">(PDF, 61KB)</span></p>
<p><a title="City of Austin EHS Food Handler Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589965355">City of Austin EHS Food Handler Training</a>   <span class="small">(PDF, 82KB)</span></p>
<p><a title="City of Baytown Food Handler Certificate" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968483">City of Baytown Food Handler Certificate</a> <span class="small">(PDF 127 KB)</span></p>
<p><a title="CST SERVICES LLC" href="http://www.dshs.state.tx.us/foodestablishments/pdf/CSTServicesLLC052013.pdf">CST SERVICES LLC</a> (Formerly  Valero Retail Holding Inc.)  <span class="small">(PDF, 278KB)</span> </p>
<p><a title="DFW Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589974711">DFW Food Handlers</a> - Effective February 5, 2013<span class="small">(PDF, 191KB)</span></p>
<p><a title="DFW Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972882">DFW Food Handlers</a> - Prior to February 5, 2013 <span class="small">(PDF, 450KB)</span></p>
<p><a title="eFoodHandlers" href="http://www.dshs.state.tx.us/foodestablishments/pdf/eFoodHandlersInc.pdf">eFoodHandlers</a> <span class="small">(PDF, 65KB)</span></p>
<p><a title="El Paso Food Handlers" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ElPasoFoodHandlers.pdf">El Paso Food Handlers</a> <span class="small">(PDF, 209KB)  (Now known as <a title="Food Handlers of Texas" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlersOfTexasSample.pdf">Food Handlers of Texas</a>  (PDF, 205KB)</span></p>
<p><a title="First Defense Food Handler Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FirstDefenseFoodhandlerTraining.pdf">First Defense Food Handler Training</a> <span class="small">(PDF, 28KB)</span></p>
<p><a title="Food Handler Classes" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlerClasses.pdf">Food Handler Classes</a> License #8  <span class="small">(PDF, 221KB)</span></p>
<p><a title="Food Handler Classes" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935975">Food Handler Classes</a> License #41  <span class="small">(PDF, 68KB)</span></p>
<p><a title="Food Handlers of Texas" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodHandlersOfTexasSample.pdf">Food Handlers of Texas</a>  <span class="small">(PDF, 205KB) -- (formerly <a title="El Paso Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18713">El Paso Food Handlers</a> PDF, 78KB)</span></p>
<p><a title="Food Marketing Institute (FMI)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FMI.pdf">Food Marketing Institute <span class="small">(FMI)</a>   <span class="small">(PDF, 412KB)</span></p>
<p><a title="Food Safety Direct (in English)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Food-Safety-Direct---English.pdf">Food Safety Direct (in English)</a> <span class="small">(PDF, 253KB)</span></p>
<p><a title="Food Safety Direct (in Spanish)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Food-Safety-Direct---Spanish.pdf">Food Safety Direct (in Spanish)</a> <span class="small">(PDF, 268KB)</span></p>
<p><a title="Food Safety International, L.L.C." href="http://www.dshs.state.tx.us/foodestablishments/pdf/FSI.pdf">Food Safety International, L.L.C.</a>   <span class="small">(PDF, 604KB)</span></p>
<p><a title="Food Safety Sense" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodSafetySenseCard2014.pdf">Food Safety Sense</a> - Effective March 26, 2014  <span class="small">(PDF, 126KB)</span></p>
<p><a title="Food Safety Sense" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodSafetySense.pdf">Food Safety Sense</a> - Prior to March 26, 2014   <span class="small">(PDF, 88KB)</span></p>
<p><a title="Food Safety Training Course" href="http://www.dshs.state.tx.us/foodestablishments/pdf/FoodSafetyTrainingCourse.pdf">Food Safety Training Course</a> <span class="small">(PDF, 70KB)</span></p>
<p><a title="Healthinspectionorg" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589936213">Healthinspectionorg</a> <span class="small">(PDF, 375KB)</span></p>
<p><a title="Jack in the Box" href="http://www.dshs.state.tx.us/foodestablishments/pdf/JackintheBox.pdf">Jack in the Box</a> <span class="small">(PDF, 121KB)  </span></p>
<p><a title="Learn2Serve.com Effective Effective June 2014" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Learn2Serve-com06_2014.pdf">Learn2Serve.com Effective Effective June 2014</a> <span class="small">(PDF, 653KB)</span></p>
<p><a title="Learn2Serve.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Learn2Serve-com-6_13.pdf">Learn2Serve.com</a>  Effective Prior to June 2014 <span class="small">(PDF, 121KB)  </span></p>
<p><a title="Learn2Serve.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Learn2ServeFH.pdf">Learn2Serve.com</a>   Prior to June 4, 2013 <span class="small">(PDF, 172KB)</span></p>
<p><a title="Le Cordon Bleu" href="http://www.dshs.state.tx.us/foodestablishments/pdf/LCB.pdf">Le Cordon Bleu</a>  <span class="small">(PDF, 103KB)  (formerly <a title="Texas Culinary Academy" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TCA.pdf">Texas Culinary Academy</a> PDF 106KB</span>)</p>
<p><a title="Lone Star Food Safety" href="http://www.dshs.state.tx.us/foodestablishments/pdf/LoneStarFoodSafety.pdf">Lone Star Food Safety</a>  <span class="small">(PDF, 663KB)</span></p>
<p><a title="MarksSafetyConsultSvcSampleCertEffDecember" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SampleCerts/MarksSafetyConsultSvcSampleCertEffDecember.pdf">Marks Safety Consultant Service</a> - Effective December 2014 <span class="small">(PDF, 865KB)</span></p>
<p><a title="MarksSafetyConsultSvcSampleCertPrior" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SampleCerts/MarksSafetyConsultSvcSampleCertPrior.pdf">Marks Safety Consultant Service</a> - Prior to December 2014 <span class="small">(PDF, 865KB)</span></p>
<p><a title="MindLeaders, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935888">MindLeaders, Inc.</a> Prior to October 2014 – Now known as Skillsoft Corporation  <span class="small">(PDF, 142KB)</span></p>
<p><a title="Mineral Wells, City of" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589992501">Mineral Wells, City of</a>  Effective October 2014  <span class="small">(PDF, 62KB)</span></p>
<p><a title="Mineral Wells, City of" href="http://www.dshs.state.tx.us/foodestablishments/pdf/MineralWellsCityof.pdf">Mineral Wells, City of</a>  Prior to October 2014 <span class="small">(PDF, 62KB)</span></p>
<p><a title="Ms. Ree's Food Safety" href="http://www.dshs.state.tx.us/foodestablishments/pdf/MsReesFoodSafety.pdf">Ms. Ree's Food Safety</a> <span class="small">(PDF, 121KB)</span></p>
<p><a title="MyFoodHandler.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/MyFoodHandler-Com.pdf">MyFoodHandler.com</a> <span class="small">(PDF, 1MB)</span></p>
<p><a title="National Registry of Food Safety Professionals" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NationalRegistryFoodSafetyProf.pdf">National Registry of Food Safety Professionals</a> Effective February 13, 2013 <span class="small">(PDF, 152KB)</span></p>
<p><a title="National Registry of Food Safety Professionals" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NationalRegistryFoodSafety.pdf">National Registry of Food Safety Professionals</a> Prior to February 13, 2013   <span class="small">(PDF, 294KB)</span></p>
<p><a title="NEHA Food Safety Training&amp;nbsp;" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NEHA.pdf">NEHA Food Safety Training </a> <span class="small">(PDF, 1.54MB)</span></p>
<p><a title="Northwest Texas Educational Services" href="http://www.dshs.state.tx.us/foodestablishments/pdf/NorthwestTexasEducationalSvc.pdf">Northwest Texas Educational Services</a>   <span class="small">(PDF, 205KB)</span> </p>
<p><a title="Plano, City of" href="http://www.dshs.state.tx.us/foodestablishments/pdf/PlanoFoodHandlerCert.pdf">Plano, City of</a> <span class="small">(PDF, 37KB)</span></p>
<p><a title="Premier Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589964510">Premier Food Safety</a> Effective February 23, 2012 <span class="small">(PDF, 731KB)</span></p>
<p><a title="Premier Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589960968">Premier Food Safety</a>   Prior to February 23, 2012 <span class="small">(PDF, 731KB)</span> </p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589983906">Professional Server Certification Corporation</a> Effective January 2, 2014 <span class="small">(PDF, 1KB)</span></p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589983905">Professional Server Certification Corporation</a> Wallet Card Effective January 2, 2014 <span class="small">(PDF, 183KB)</span></p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodHandler_Updated.pdf">Professional Server Certification Corporation</a> Prior September 15, 2011  <span class="small">(PDF, 83KB)</span></p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589946917">Professional Server Certification Corporation</a> Prior March 7, 2011   <span class="small">(PDF, 138KB)</span></p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589942169">Professional Server Certification Corporation</a> Prior to March 7, 2011 <span class="small">(PDF, 138KB) </span></p>
<p><a title="Public Health Education" href="http://www.dshs.state.tx.us/foodestablishments/pdf/PublicHealthEducation.pdf">Public Health Education</a> <span class="small">(PDF, 83KB)</span></p>
<p><a title="RaceTrac Petroleum, Inc." href="http://www.dshs.state.tx.us/foodestablishments/pdf/RaceTracPetroleumInc2014.pdf">RaceTrac Petroleum, Inc.</a> Effective January 10, 2014 <span class="small">(PDF, 264KB)</span></p>
<p><a title="RaceTrac Petroleum, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589963657">RaceTrac Petroleum, Inc.</a>  Prior to January 10, 2014 <span class="small">(PDF, 176KB)</span></p>
<p><a title="Safe Food Solutions" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Safe-Food-Solutions-LLC.pdf">Safe Food Solutions</a> #59 - Effective July 2014</p>
<p><a title="Safe Food Solutions" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968516">Safe Food Solutions</a> Prior to July 2014 <span class="small">(PDF, 162KB)</span></p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972811">Safe Food 4 U</a> - License # 55 - Effective November 2012 <span class="small">(PDF, 146KB)</span></p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972810">Safe Food 4 U</a> - License # 14 - Effective November 2012 <span class="small">(PDF, 72KB)</span>  </p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935511">Safe Food 4 U</a> - Prior to November 2012  <span class="small">(PDF, 165KB)</span></p>
<p><a title="Safe Food 4 U (Spanish)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589965906">Safe Food 4 U (Spanish)</a> <span class="small">(PDF, 99KB)</span></p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SafeFood4U.pdf">Safe Food 4 U</a>  -  Prior to October 12, 2010 <span class="small">(PDF, 174KB)</span></p>
<p><a title="StateFoodTest.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972812">SafeFoodTest.com</a> - <span class="small">(PDF, 3KB)</span></p>
<p><a title="Sam Houston State University" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SamHoustonStateUniversity.pdf">Sam Houston State University</a> <span class="small">(PDF, 210KB)</span></p>
<p><a title="ServSafe Starters - Classroom" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SerSafeStartersClassroom.pdf">ServSafe Starters - Classroom</a> <span class="small">(PDF, 176KB)</span></p>
<p><a title="ServSafe Starters - Online" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ServSafeStartersOnline.pdf">ServSafe Starters - Online</a> <span class="small">(PDF, 234KB)</span></p>
<p><a title="Skillsoft Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993241">Skillsoft Corporation</a> - License # 39 - Effective October 2014 – Formerly MindLeaders Inc.  <span class="small">(PDF, 112KB)</span></p>
<p><a title="State Educational Systems, LLC" href="http://www.dshs.state.tx.us/foodestablishments/pdf/StateEducationalSystemsLLC.pdf">State Educational Systems, LLC</a>   <span class="small">(PDF, 953KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993430">StateFoodSafety.com</a> - License # 3 - Effective November 2014 <span class="small">(PDF, 808KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/StateFoodSafety-Com_08_2014.pdf">StateFoodSafety.com</a> - License # 3 -- Prior to November 2014 <span class="small">(PDF, 63KB)</span></p>
<p><a title="StateFoodSafety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589970268">StateFoodSafety.com</a> - License # 38 - Prior August 2014 <span class="small">(PDF, 335KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935918">StateFoodSafety.com</a> - License #38  - Prior August 2012 <span class="small">(PDF, 236KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18760">StateFoodSafety.com</a> - License #3 - Prior to November 12, 2010 <span class="small">(PDF, 64KB)</span></p>
<p><a title="Sonic Drive-In" href="http://www.dshs.state.tx.us/foodestablishments/pdf/SonicDrive-In.pdf">Sonic Drive-In</a>  <span class="small">(PDF, 2KB)</span></p>
<p><a title="Stripes" href="http://www.dshs.state.tx.us/foodestablishments/pdf/stripes.pdf">Stripes</a>   <span class="small">(PDF, 84KB)</span></p>
<p><a title="Texas A&amp;amp;M AgriLife Extension Service License # 76 " href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas-AM-AgriLife-Extension-Service-License---76.pdf">Texas A&amp;M AgriLife Extension Service License # 76 </a>- Effective July 2014</p>
<p><a title="Texas AgriLife Extension Service" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589969466">Texas A&amp;M AgriLife Extension Service License #6</a> - Effective April 2012  <span class="small">(PDF, 88KB)</span></p>
<p><a title="Texas AgriLife Extension Service" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas_20AgriLife.pdf">Texas A&amp;M AgriLife Extension Service License #6</a> - Prior to April 21, 2012  <span class="small">(PDF, 55KB)</span></p>
<p><a title="Texas Best Food Services Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasBestFoodServicesTraining.pdf">Texas Best Food Services Training</a> <span class="small">(PDF, 3MB)</span></p>
<p><a title="Texas Culinary Academy" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TCA.pdf">Texas Culinary Academy</a> <span class="small">(PDF, 106KB) - (Now known as <a title="Le Cordon Bleu" href="http://www.dshs.state.tx.us/foodestablishments/pdf/LCB.pdf">Le Cordon Bleu</a>  (PDF 103KB</span>)</p>
<p><a title="TexasFoodCard.com license" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodCardCom2014.pdf">TexasFoodCard.com license</a> # 21- Effective December 2014 (<span class="small">PDF 328MB</span>)</p>
<p><a title="TexasFoodCard.com, license" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993112">TexasFoodCard.com, license</a> # 21- Prior to December 2014 (<span class="small">PDF 8MB</span>)</p>
<p><a title="Texas foodcard.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texasfoodcardcom.pdf">Texas FoodCard.com</a> - Prior to October 2014 <span class="small">(PDF, 577KB)</span></p>
<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodHandler06_2013-com.pdf">TexasFoodHandler.com/Safeway Certifications</a> - Effective June 2013 <span class="small">(PDF 246KB</span>)</p>
<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968423">TexasFoodHandler.com/Safeway Certifications</a> - Prior to June 2013 (<span class="small">PDF 800KB</span>)</p>
<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasFoodHandlercom.pdf">TexasFoodHandler.com/Safeway Certifications</a>  - Prior to May 2012 <span class="small">(PDF, 550KB)</span></p>
<p><a title="Texas Food Safety Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas-Food-Safety-Training.pdf">Texas Food Safety Training</a>  <span class="small">(PDF, 3423KB)</span></p>
<p><a title="Texas Online Food Handler" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexasOnlineFoodHandlerProgram.pdf">Texas Online Food Handler</a> <span class="small">(PDF, 300KB)</span></p>
<p><a title="Texas State University - San Marcos Food Handler Program" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Texas-State-University---San-Marcos.pdf">Texas State University - San Marcos Food Handler Program</a>  <span class="small">(PDF, 383KB)</span></p>
<p><a title="Texoma Food Service" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TexomaFoodService.pdf">Texoma Food Service</a> <span class="small">(PDF, 108KB)</span></p>
<p><a title="Thornhill Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972506">Thornhill Training</a> - Effective November 2012 <span class="small">(PDF 293KB)</span></p>
<p><a title="Thornhill Training" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ThornhillTraining.pdf">Thornhill Training</a>  - Prior to November 2012 <span class="small">(PDF, 94KB)</span></p>
<p><a title="Tokyo Gardens Catering, LLC" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TGCFoodHandlerCertificate.pdf">Tokyo Gardens Catering, LLC</a> <span class="small">(PDF, 360KB)</span></p>
<p><a title="Training Achievement Program (TAP series)" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Training-Achievement-Program-(TAP-Series)2014.pdf">Training Achievement Program (TAP series)</a> Effective June 2014 <span class="small">(PDF, 88KB)</span></p>
<p><a title="Training Achievement Program (TAP series)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968521">Training Achievement Program (TAP series)</a> Prior to June 2014 <span class="small">(PDF, 1KB)</span></p>
<p><a title="United Supermarkets" href="http://www.dshs.state.tx.us/foodestablishments/pdf/UnitedSupermarkets.pdf">United Supermarkets</a> <span class="small">(PDF, 54KB)</span></p>
<p><a title="One Valero Way" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589946918">Valero Retail Holdings, Inc.</a> (Now known as CST Services LLC)  <span class="small">(PDF, 742KB) </span></p>
<p><a title="Wal-Mart" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Wal-Mart-Stores-Texas.pdf">Wal-Mart</a> <span class="small">(PDF, 658KB)</span></p>
<p><a title="Western Refining" href="http://www.dshs.state.tx.us/foodestablishments/pdf/WesternRefining.pdf">Western Refining</a> <span class="small">(PDF, 324KB)</span></p>
<p><a title="Whole Foods Markets - Southwest" href="http://www.dshs.state.tx.us/foodestablishments/pdf/WholeFoods.pdf">Whole Foods Markets - Southwest</a> <span class="small">(PDF, 121KB)</span></p>
<p><a title="Woody's Training in Texas" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Woody_sTraininginTexas.pdf">Woody's Training in Texas</a> <span class="small">(PDF, 60KB)</span></p>
<p><a title="World Credential Diagnostic" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589958631">World Credential Diagnostic</a> <span class="small">(PDF 328KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/www-TrainingNow-com01_07_14.pdf">www.TrainingNow.com</a>  Effective January 7, 2014 <span class="small">(PDF, 194KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589976686">www.TrainingNow.com</a> Prior to January 7, 2014 <span class="small">(PDF, 961KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589971977">www.TrainingNow.com</a> Prior to April 26, 2013  <span class="small">(PDF, 341KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/foodestablishments/pdf/TrainingNow_com.pdf">www.TrainingNow.com</a>  Prior to November 5, 2012 <span class="small">(PDF, 60KB)</span></p>
<p><a title="Zepol Dietary Consults" href="http://www.dshs.state.tx.us/foodestablishments/pdf/Zepol-Dietary-Consults2014.pdf">Zepol Dietary Consults</a> Effective April 1, 2014 <span class="small">(PDF 955KB)</span> </p>
<p><a title="Zepol Dietary Consults" href="http://www.dshs.state.tx.us/foodestablishments/pdf/ZepolDietaryConsults.pdf">Zepol Dietary Consults</a> Prior to April 1, 2014   <span class="small">(PDF, 104KB)</span></p>

<?php include '../includes/footer.html' ?>