<?php 
	$title= "Patient Safety: Questions and Answers" ; 
	include '/home/codio/workspace/includes/header.html'; 
	include '/home/codio/workspace/includes/menus/hfp_menu.html'; 
?>
<ul>
	<li><a href="#stillborn">Stillborn infants and perinatal death</a></li>
	<li><a href="#perinataldeath">Death occurring after transfer to a hospital for a higher level of care</a></li>
	<li><a href="#clarifythereporting">Death occurring when a transfer of infant from one hospital to another hospital is involved.</a> </li>
	<li><a href="#wrongpatient">Surgical procedure on the wrong patient or the wrong body part</a></li>
	<li><a href="#foreignobject">Foreign object accidentally left in a patient during a procedure</a></li>
	<li><a href="#retentionrootcause">Retention for the root cause analyses and action plans</a></li>
	<li><a href="#hospitalASC">Hospitals with off-site ambulatory surgical centers</a></li>
	<li><a href="#hospitalcampuses">Hospitals with multiple campuses</a></li>
</ul>
<hr/>
<dl>
	<dt><a name="stillborn"></a>Is a stillborn infant considered a perinatal death? <br/><br/></dt>
	<dd>Stedman's Medical Dictionary defines "perinatal" as "occurring during, or pertaining to, the periods before, during, or after the time of birth; i.e., before delivery from the 28th week of gestation through the first 7 days after delivery." A stillborn with a birth weight greater that 2,500 grams who's death is unrelated to a congenital condition would be a reportable incident. An example would be failure to identify fetal distress from cord compression during labor. This would be reportable if the root cause analysis concluded the infant died during labor due to cord compression, the infant was otherwise normal, and the death may have been prevented if medical interventions had been implemented. (Posted 12/20/05) <br/><br/></dd>
	<dt><a id="perinataldeath"></a>Regarding the reportable occurrence of "a perinatal death unrelated to a congenital condition in an infant with a birth weight greater than 2500 grams," please clarify the definition of "perinatal" and does this include a death occurring after transfer to a hospital for a higher level of care. <br/><br/></dt>
	<dd>If a normal newborn infant, without congenital conditions and weighing greater than 2500 grams, dies unexpectedly during the post-birth hospitalization (prior to discharge), or within seven (7) days of birth, then the event must be reported and a root cause analysis must be completed. 
		<br/><br/><em>Example 1</em>: An infant who was born without congenital conditions and weighed more than 2500 grams at birth develops post-birth complications, and subsequently expires on the 12th day following birth while still hospitalized. The infant was not discharged, so this death occurred during the post-birth hospitalization, and therefore would be a reportable event. 
	<br/><br/><em>Example 2</em>: An infant who was born without congenital conditions and weighed more than 2500 grams at birth is discharged to home on day 3, but returns to the hospital on day 4 with post-birth complications and dies on day 5. This event would be reportable since it occurs within 7 days of birth (the Centers for Disease Control and Prevention defines perinatal mortality as a death occurring within 7 days of birth). (Posted 08/12/04)<br/><br/></dd>
	<dt><a id="clarifythereporting"></a>Clarify the reporting requirements related to "a perinatal death unrelated to a congenital condition in an infant with a birth weight greater than 2500 grams" when a transfer of the infant from one hospital to another hospital is involved. What are the responsibilities of both the sending and the receiving hospitals? <br/><br/></dt>
	<dd>In most instances, we anticipate that infants would be transferred from one hospital to another hospital because they had a congenital condition or post-birth complication that necessitated a higher level of care. If this is the situation, and the infant subsequently dies after transfer, the receiving hospital is not obligated to report the event or to complete a RCA. However, the receiving hospital is encouraged to notify the sending hospital of the death, and then the sending hospital would be required to report the event and complete a RCA. 
	<br/><br/>If a normal, newborn infant without congenital conditions and weighing more 2500 grams is received through transfer from another hospital because the sending hospital did not have the capability of providing OB or normal perinatal care, and the newborn subsequently dies unexpectedly during the post-birth hospitalization (prior to discharge), or within seven (7) days of birth, then the receiving hospital would be expected to report the events and complete a RCA. (Posted 08/12/04)<br/><br/></dd>
	<dt><a id="wrongpatient"></a>At what point does the "surgical procedure on the wrong patient or the wrong body part" apply? <br/><br/></dt>
	<dd>If the skin is cut, even if only superficially, then it applies. We would expect the event to be reported and a RCA to be completed. (Posted 08/12/04) <br/><br/></dd>
	<dt><a id="foreignobject"></a>Clarify what the state is expecting related to "a foreign object accidentally left in a patient during a procedure." We always x-ray prior to taking the patient out of the OR, and we have on occasion identified retained sponges. JCAHO does not consider this a sentinel event if we identify it prior to leaving the OR and the patient does not die or sustain permanent loss of bodily function. What about cases where the OR had to be cleared quickly to make room for an emergency case? <br/><br/></dt>
	<dd>The state requirement differs from JCAHO in that there is no provision related to whether the patient sustains serious injury or permanent loss of bodily function. It is our position that if the retained object is not identified until after the surgical site has been closed, then the event is reportable and a RCA must be completed. The fact the patient has not left the OR and may not have sustained permanent loss of bodily function does not negate the fact that the system in place for some reason has failed. The patient will have to sustain the additional trauma of the reopening of the surgical site and possibly prolonged anesthesia and recovery. It is imperative that facilities evaluate the cause of such a failure to help protect patients in the future. The example of having to "clear the OR quickly to make room for an emergency case" is not acceptable justification for compromising the safety of the patient. If such an event did occur under these circumstances, a RCA must be conducted to determine why this was allowed to occur in the first place, and what can be done to prevent it in the future. (Posted 08/12/04)<br /></dd>
	<dt><a id="retentionrootcause"></a>What is the retention for the root cause analyses and action plans required by the regulations? <br/><br/></dt>
	<dd> Although the statute does not specifically address this issue, the department believes the facility should retain the documents for at least the life of the legislation, which is 4 years. It is highly recommended that you develop a retention schedule for these records that is consistent with your Quality Assurance/Performance Improvement data retention schedule, since the RCA information will link directly to any corrective actions you may have taken if an adverse event has occurred. You may also want to consider placing these records on the same retention schedule specified in the rules for medical records in general. (Posted 08/12/04) <br/><br/></dd>
	<dt><a id="hospitalASC"></a> Our hospital has an off-site ambulatory surgical center. Do we include events that occur at the ASC on the same form with the hospital data?<br/><br/></dt>
	<dd>The reporting of events is tied to the facility's license. If your offsite surgical department is included under the hospital's license, then you would include events occurring at that location with hospital's data, submitting only one form for all locations under the license. It is possible that your ASC could be considered provider-based by the Centers for Medicare and Medicaid services, but under state licensing, they are required to be licensed separately as an Ambulatory Surgical Center. If the ASC is licensed separately, then events occurring at that cite must be reported on the Ambulatory Surgical Center reporting form. (Posted 08/12/04) <br/><br/></dd>
	<dt><a id="hospitalcampuses"></a>Our hospital is comprised of 3 separate campuses. Do we submit a report for each campus?<br/><br/></dt>
	<dd>The reporting of events is tied to the facility's license. If all three campuses are under the same license, then you should submit only one report for all locations under that license number. (Posted 08/12/04) </dd>
</dl>
<?php include '/home/codio/workspace/includes/footer.html' ?>