<?php
	$title= "Food Alerts and Recalls Affecting Texas - Food Manufacturers and Distributors" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/foods_menu.html'; 
?>

<h2>Sources for Recall Information</h2>

<p><a title="USDA Current Recalls and Alerts" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/current-recalls-and-alerts" target="_blank">USDA Current Recalls and Alerts</a></p>
<p><a title="FDA Recalls, Market Withdrawals, &amp; Safety Alerts" href="http://www.fda.gov/Safety/Recalls/default.htm" target="_blank">FDA Recalls, Market Withdrawals, &amp; Safety Alerts</a></p>
<p><a title="FDA Enforcement Reports" href="http://www.fda.gov/Safety/Recalls/EnforcementReports/default.htm">FDA Enforcement Reports</a></p>

<hr/>

<h2>March 2, 2015</h2>

<p><a title="Hamchorom Inc. is recalling Haitai Tayo Crackers (140 g) 24 boxes/carton, in box colors: blue, yellow, and red, and Haitai Gyeran Crackers (70 g) 20 boxes/carton, in yellow box with "Angry Birds" logo, due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food">Hamchorom Inc. is recalling Haitai Tayo Crackers (140 g) 24 boxes/carton, in box colors: blue, yellow, and red, and Haitai Gyeran Crackers (70 g) 20 boxes/carton, in yellow box with "Angry Birds" logo, due to undeclared allergens.</a></p>
<p><a title="Probar LLC is recalling Frosted Peanut Butter BASE Protein Bar, 2.46 oz., film wrapped bar packaged in 12 wrapped units per sleeve/carton, due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng">Probar LLC is recalling Frosted Peanut Butter BASE Protein Bar, 2.46 oz., film wrapped bar packaged in 12 wrapped units per sleeve/carton, due to undeclared allergens.</a></p>
<p><a title="Talenti® Gelato &amp; Sorbetto is recalling Talenti® Gelato &amp; Sorbetto Sea Salt Caramel Gelato packaged in one pint (473 mL) clear plastic jars, due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm436020.htm">Talenti® Gelato &amp; Sorbetto is recalling Talenti® Gelato &amp; Sorbetto Sea Salt Caramel Gelato packaged in one pint (473 mL) clear plastic jars, due to undeclared allergens.</a></p>
<p><a title="Fairway “Like No Other Market” is recalling Fairway brand Raw Hazelnuts (Filberts), packaged in clear, plastic cello bags of varying weights, each weighing less than one pound, due to possible Salmonella contamination." href="http://www.fda.gov/Safety/Recalls/ucm435547.htm">Fairway “Like No Other Market” is recalling Fairway brand Raw Hazelnuts (Filberts), packaged in clear, plastic cello bags of varying weights, each weighing less than one pound, due to possible Salmonella contamination.</a></p>
<p><a title="Oscar’s Hickory House Inc. is recalling Oscar’s Adirondack Mountain Smokehouse Beef Jerky in 4 oz. and 8 oz. cryovac packages, due to a processing deviation." href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release">Oscar’s Hickory House Inc. is recalling Oscar’s Adirondack Mountain Smokehouse Beef Jerky in 4 oz. and 8 oz. cryovac packages, due to a processing deviation.</a></p>

<hr/>

<h2>February 24, 2015</h2>

<p><a title="Freeland Foods Inc. is recalling Go Raw 100% Organic Sunflower Seeds; Net Wt. 1 lb. (454 g), due to possible Salmonella contamination." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1196-2015&amp;w=02182015&amp;lang=eng">Freeland Foods Inc. is recalling Go Raw 100% Organic Sunflower Seeds; Net Wt. 1 lb. (454 g), due to possible Salmonella contamination.</a></p>
<p><a title="HVL, LLC is recalling Melatonin Control- Released Tablets, 60 tablets, in plastic bottles, due to mislabeling." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1202-2015&amp;w=02182015&amp;lang=eng">HVL, LLC is recalling Melatonin Control- Released Tablets, 60 tablets, in plastic bottles, due to mislabeling.</a></p>
<p><a title="Kellogg USA Inc. is recalling MorningStar Farms Spicy Black Bean Burger and MorningStar Farms Chipotle Black Bean Burger, due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food">Kellogg USA Inc. is recalling MorningStar Farms Spicy Black Bean Burger and MorningStar Farms Chipotle Black Bean Burger, due to undeclared allergens.</a></p>
<p><a title="Full Tilt Ice Cream is recalling several flavors of ice cream packaged in 16 oz. paper containers, and 1.5 gallon and 3 gallon plastic tubs, due to possible Listeria monocytogenes contamination." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food">Full Tilt Ice Cream is recalling several flavors of ice cream packaged in 16 oz. paper containers, and 1.5 gallon and 3 gallon plastic tubs, due to possible Listeria monocytogenes contamination.</a></p>
<p><a title="El Popocatepetl Ind., Inc. is recalling El Popocatepetl’s 8 in. Chipotle, Spinach Pesto, and Sun Dried Tomato Wraps, due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm435190.htm">El Popocatepetl Ind., Inc. is recalling El Popocatepetl’s 8 in. Chipotle, Spinach Pesto, and Sun Dried Tomato Wraps, due to undeclared allergens.</a></p>
<p><a title="WhiteWave Foods is recalling Horizon Cheddar Sandwich Crackers (7.5 oz.), due to undeclared allergens. " href="http://www.fda.gov/Safety/Recalls/ucm435172.htm">WhiteWave Foods is recalling Horizon Cheddar Sandwich Crackers (7.5 oz.), due to undeclared allergens. </a></p>
<p><a title="Con Yeager Spice Company is recalling multiple sized packages under multiple brand names of ground cumin and multiple seasoning blends (containing ground cumin) due to undeclared allergens. " href="http://www.fda.gov/Safety/Recalls/ucm435171.htm">Con Yeager Spice Company is recalling multiple sized packages under multiple brand names of ground cumin and multiple seasoning blends (containing ground cumin) due to undeclared allergens. </a></p>
<p><a title="Old Home Kitchens is recalling Sock It To Me Crème Cake under the “Bakery baked with pride" label, packaged in plastic domes, due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm435170.htm">Old Home Kitchens is recalling Sock It To Me Crème Cake under the “Bakery baked with pride" label, packaged in plastic domes, due to undeclared allergens.</a></p>
<p><a title="Goya Foods, Inc. is recalling Kirby Black Beans Creole Seasoning (29 oz.) and Goya Black Bean Soup (29 oz.), due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm434542.htm">Goya Foods, Inc. is recalling Kirby Black Beans Creole Seasoning (29 oz.) and Goya Black Bean Soup (29 oz.), due to undeclared allergens.</a></p>
<p><a title="ESS Food is recalling Pini Polona Pork Belly Boneless (40 lb.) packaged in boxes containing 4-5 pieces, due to not being presented at the U.S. point of entry for inspection. " href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release">ESS Food is recalling Pini Polona Pork Belly Boneless (40 lb.) packaged in boxes containing 4-5 pieces, due to not being presented at the U.S. point of entry for inspection. </a></p>

<hr/>

<h2>February 18, 2015</h2>

<p><a title="High Road Craft Ice Cream, Inc. is recalling High Road Craft Ice Cream &amp; Sorbet, Limoncello Sorbet packed in 4.9L (1.3 gallon) tubs, due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0967-2015&amp;w=02112015&amp;lang=eng">High Road Craft Ice Cream, Inc. is recalling High Road Craft Ice Cream &amp; Sorbet, Limoncello Sorbet packed in 4.9L (1.3 gallon) tubs, due to undeclared allergens.</a></p>
<p><a title="Zilks Foods is recalling several flavors of Zilks brand Hummus (8 oz.), due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">Zilks Foods is recalling several flavors of Zilks brand Hummus (8 oz.), due to undeclared allergens.</a></p>
<p><a title="Gemini Food Corporation Inc. is recalling Description Dried Bean Curd Satay Flavor (150g), Dried Bean Curd Anka Flavor (150g), Dried Bean Curd Chili Flavor (150g), Dried Bean Curd Spicy Flavor (150g), and Dried Bean Curd Garlic Flavor (150g), to due possible dimethyl yellow contamination." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">Gemini Food Corporation Inc. is recalling Description Dried Bean Curd Satay Flavor (150g), Dried Bean Curd Anka Flavor (150g), Dried Bean Curd Chili Flavor (150g), Dried Bean Curd Spicy Flavor (150g), and Dried Bean Curd Garlic Flavor (150g), to due possible dimethyl yellow contamination.</a></p>
<p><a title="Reily Foods Co. is recalling Carroll Shelby’s Original Texas Brand Chili Kit (4 oz.)( 113 g), Carroll Shelby’s Original Texas Brand White Chicken Chili kit (3 oz.) (85 g), Wick Fowler’s Famous Texas Style 2-Alarm Chilli Kit (3.6525 oz.) (102 g), and Wick Fowler’s Famous Texas Style False Alarm Mild Chilli Kit (3.03 oz.) (86 g), due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">Reily Foods Co. is recalling Carroll Shelby’s Original Texas Brand Chili Kit (4 oz.)( 113 g), Carroll Shelby’s Original Texas Brand White Chicken Chili kit (3 oz.) (85 g), Wick Fowler’s Famous Texas Style 2-Alarm Chilli Kit (3.6525 oz.) (102 g), and Wick Fowler’s Famous Texas Style False Alarm Mild Chilli Kit (3.03 oz.) (86 g), due to undeclared allergens.</a></p>
<p><a title="Riba Foods Inc. is recalling Arriba! Chili Con Queso-Hot (16 oz.), Salpica Salsa Con Queso (11.5 oz. &amp;16 oz.), Salpica Ballpark Nacho (8 oz.), Salpica Black Bean Nacho (8 oz.), Crate &amp; Barrel Monterey Jack Queso Dip (11.5 oz.), and Salpica Jalapeno Jack Queso Dip (16 oz.), due to undeclared allergens." href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">Riba Foods Inc. is recalling Arriba! Chili Con Queso-Hot (16 oz.), Salpica Salsa Con Queso (11.5 oz. &amp;16 oz.), Salpica Ballpark Nacho (8 oz.), Salpica Black Bean Nacho (8 oz.), Crate &amp; Barrel Monterey Jack Queso Dip (11.5 oz.), and Salpica Jalapeno Jack Queso Dip (16 oz.), due to undeclared allergens.</a></p>
<p><a title="Unilever United States, Inc. is recalling Breyers® No Sugar Added Salted Caramel Swirl packaged in 1.5-quart (1.41L) paperboard tubs, due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm434540.htm">Unilever United States, Inc. is recalling Breyers® No Sugar Added Salted Caramel Swirl packaged in 1.5-quart (1.41L) paperboard tubs, due to undeclared allergens.</a></p>
<p><a title="Whole Foods Market is recalling Chocolate Cake for Two packaged in clear plastic containers, due to undeclared allergens. " href="http://www.fda.gov/Safety/Recalls/ucm434430.htm">Whole Foods Market is recalling Chocolate Cake for Two packaged in clear plastic containers, due to undeclared allergens. </a></p>
<p><a title="Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder packaged in clear plastic bags (0.25 lb. – 0.30lb.), due to possible Salmonella contamination. " href="http://www.fda.gov/Safety/Recalls/ucm434254.htm">Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder packaged in clear plastic bags (0.25 lb. – 0.30lb.), due to possible Salmonella contamination. </a></p>
<p><a title="Michigan Brand, Inc. is recalling Michigan Brand Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and The Jerky Outlet Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and 40 count boxes, due to undeclared allergens." href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release">Michigan Brand, Inc. is recalling Michigan Brand Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and The Jerky Outlet Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and 40 count boxes, due to undeclared allergens.</a></p>
<p><a title="Ruiz Foods is recalling Egg Sausage and Cheese Wrapped in a Flour Tortilla packaged in 4.5-lb. cases containing 3 trays with 8 pieces, due to undeclared allergens." href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release">Ruiz Foods is recalling Egg Sausage and Cheese Wrapped in a Flour Tortilla packaged in 4.5-lb. cases containing 3 trays with 8 pieces, due to undeclared allergens.</a></p>

<hr/>

<h2>February 12, 2015</h2>

<p><a title="Sunfood is recalling Organic Sacha Inchi Powder, packaged in 8 oz. white bags, due to possible Staphylococcus enterotoxin contamination." href="http://www.fda.gov/Safety/Recalls/ucm434009.htm">Sunfood is recalling Organic Sacha Inchi Powder, packaged in 8 oz. white bags, due to possible Staphylococcus enterotoxin contamination.</a></p>
<p><a title="Hines Nut Company is recalling Hines Nut Brand Walnut Halves and Pieces (12 or 16 oz.) due to possible Salmonella contamination." href="http://www.fda.gov/Safety/Recalls/ucm433797.htm">Hines Nut Company is recalling Hines Nut Brand Walnut Halves and Pieces (12 or 16 oz.) due to possible Salmonella contamination.</a></p>
<p><a title="Detox Transforms Health and Nutrition is recalling EDGE Amplified Weight Release, iNDiGO, AMPD Gold Bee Pollen, BtRim Max, and iNSANE Bee Pollen, all packaged in white bottles with 60 capsules, due to undeclared drug ingredients." href="http://www.fda.gov/Safety/Recalls/ucm433513.htm">Detox Transforms Health and Nutrition is recalling EDGE Amplified Weight Release, iNDiGO, AMPD Gold Bee Pollen, BtRim Max, and iNSANE Bee Pollen, all packaged in white bottles with 60 capsules, due to undeclared drug ingredients.</a></p>
<p><a title="Korean Food Co. is recalling Go-Hang Soybean Sprouts in 1 lb. and 2 lb. plastic bags, and 10 lb. black plastic bags, due to possible Listeria monocytogenes contamination. " href="http://www.fda.gov/Safety/Recalls/ucm433403.htm">Korean Food Co. is recalling Go-Hang Soybean Sprouts in 1 lb. and 2 lb. plastic bags, and 10 lb. black plastic bags, due to possible Listeria monocytogenes contamination. </a></p>
<p><a title="Pepperidge Farm is recalling Cinnamon Raisin Bagels (21 oz. and 17oz.), Plain Mini Bagels (17 oz.), Everything Bagels (21 oz.), Plain Bagels (21 oz.) Brown Sugar/Cinnamon Mini Bagels (17 oz.), and 100% Whole Wheat Mini Bagels (17 oz.), due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm433775.htm">Pepperidge Farm is recalling Cinnamon Raisin Bagels (21 oz. and 17oz.), Plain Mini Bagels (17 oz.), Everything Bagels (21 oz.), Plain Bagels (21 oz.) Brown Sugar/Cinnamon Mini Bagels (17 oz.), and 100% Whole Wheat Mini Bagels (17 oz.), due to undeclared allergens.</a></p>
<p><a title="See’s Company is recalling Classic Red Hearts with Assorted Chocolates 8 oz., due to undeclared allergens." href="http://www.fda.gov/Safety/Recalls/ucm433408.htm">See’s Company is recalling Classic Red Hearts with Assorted Chocolates 8 oz., due to undeclared allergens.</a></p>
<p><a title="Sunrise Poultry Processors is recalling Sunrise Poultry Brand Chicken Thighs in 40 lb. bulk cases, Chicken Thighs Boneless in 25 lb. cases, Boneless Chicken Breast in 2.5lb. cases, and Chicken Whole Fryer in 2.5 lb., 4 lb., and 3.25-3.75 lb. cases, due to not being presented at the U.S. point of entry for inspection." href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release">Sunrise Poultry Processors is recalling Sunrise Poultry Brand Chicken Thighs in 40 lb. bulk cases, Chicken Thighs Boneless in 25 lb. cases, Boneless Chicken Breast in 2.5lb. cases, and Chicken Whole Fryer in 2.5 lb., 4 lb., and 3.25-3.75 lb. cases, due to not being presented at the U.S. point of entry for inspection.</a></p>

<hr/>

<h2>February 6, 2015 </h2>

<p><a title="Eillien's Candies, Inc. is recalling Walnut Pieces in several sizes, under the following brand names: Eillien’s, Blain’s Farm and Fleet, Mill’s Fleet Farm, Piggly Wiggly, Rural King, and Trig’s, due to possible Salmonella contamination. " href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng">Eillien's Candies, Inc. is recalling Walnut Pieces in several sizes, under the following brand names: Eillien’s, Blain’s Farm and Fleet, Mill’s Fleet Farm, Piggly Wiggly, Rural King, and Trig’s, due to possible Salmonella contamination. </a></p>
<p><a title="The Harvard Drug Group, LLC is recalling Thera Tablets with Beta Carotene Dietary Supplement, due to mislabeling. " href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng">The Harvard Drug Group, LLC is recalling Thera Tablets with Beta Carotene Dietary Supplement, due to mislabeling. </a></p>
<p><a title="John B. Sanfilippo &amp; Son Inc. is recalling Fisher Brand Chopped Walnuts, and Pecan Cookie Pieces , both packaged in 8 oz. (226 g) plastic bags, due to possible Salmonella contamination. " href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food">John B. Sanfilippo &amp; Son Inc. is recalling Fisher Brand Chopped Walnuts, and Pecan Cookie Pieces , both packaged in 8 oz. (226 g) plastic bags, due to possible Salmonella contamination. </a></p>
<p><a title="Zachary Confections, Inc. is recalling Market Pantry Brand Dark Chocolate Covered Almonds (9 oz.), due to undeclared allergens. " href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng">Zachary Confections, Inc. is recalling Market Pantry Brand Dark Chocolate Covered Almonds (9 oz.), due to undeclared allergens. </a></p>
<p><a title="The Spice Mill is recalling Ground Cumin (2.75 oz.) and Cajun Seasoning (4 oz.), due to undeclared allergens. " href="http://www.fda.gov/Safety/Recalls/ucm432761.htm">The Spice Mill is recalling Ground Cumin (2.75 oz.) and Cajun Seasoning (4 oz.), due to undeclared allergens. </a></p>
<p><a title="Krehbiel’s Specialty Meats, Inc. is recalling Fresh Beer Bratwurst Made With Tallgrass Brewery Oasis Beer in 16 oz. vacuum sealed packages, due to misbranding. " href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015">Krehbiel’s Specialty Meats, Inc. is recalling Fresh Beer Bratwurst Made With Tallgrass Brewery Oasis Beer in 16 oz. vacuum sealed packages, due to misbranding. </a></p>

<hr/>

<h2>February 3, 2015 </h2>

<p><a title="Quest Nutrition, LLC is recalling QuestBar Protein Bar Chocolate Chip Cookie Dough Flavor net wt. 2.12 OZ (60 g) and QuestBar Protein Bar Double Chocolate Chunk Flavor net wt. 2.12 OZ (60 g), due to the possibility of plastic pieces introduced into the products by an ingredients supplier. " href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food">Quest Nutrition, LLC is recalling QuestBar Protein Bar Chocolate Chip Cookie Dough Flavor net wt. 2.12 OZ (60 g) and QuestBar Protein Bar Double Chocolate Chunk Flavor net wt. 2.12 OZ (60 g), due to the possibility of plastic pieces introduced into the products by an ingredients supplier. </a></p>
<p><a title="American Roland Food Corp. is recalling Roland brand Bruschetta, Italian-Style Appetizer (12 oz.) (340g), packaged in a glass jar, due to glass fragment found in product. " href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng">American Roland Food Corp. is recalling Roland brand Bruschetta, Italian-Style Appetizer (12 oz.) (340g), packaged in a glass jar, due to glass fragment found in product. </a></p>
<p><a title="Hamchorom, Inc. is recalling HAITAI Tayo Crackers (140 g) and HAITAI Gyeran Crackers (70 g), due to undeclared allergens. " href="http://www.fda.gov/Safety/Recalls/ucm432560.htm">Hamchorom, Inc. is recalling HAITAI Tayo Crackers (140 g) and HAITAI Gyeran Crackers (70 g), due to undeclared allergens. </a></p>
<p><a title="Project Healthy Living, Inc. is recalling all packages of Premium Protein powder in chocolate and vanilla blends in both 14-serving sized steel tins and single-serving sized pouches, due to possible Staphylococcus enterotoxins contamination. " href="http://www.fda.gov/Safety/Recalls/ucm432558.htm">Project Healthy Living, Inc. is recalling all packages of Premium Protein powder in chocolate and vanilla blends in both 14-serving sized steel tins and single-serving sized pouches, due to possible Staphylococcus enterotoxins contamination. </a></p>
<p><a title="Freeland Foods, Inc. is recalling Go Raw Organic Sunflower Seed, due to possible Salmonella contamination. " href="http://www.fda.gov/Safety/Recalls/ucm432417.htm">Freeland Foods, Inc. is recalling Go Raw Organic Sunflower Seed, due to possible Salmonella contamination. </a></p>
<p><a title="Morrison Meat Packers is recalling “El Toro Cooked Pork and Water Product” and “Vida Latina Cooked Pork and Water Product”, of various weights, due to undeclared allergens. " href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release">Morrison Meat Packers is recalling “El Toro Cooked Pork and Water Product” and “Vida Latina Cooked Pork and Water Product”, of various weights, due to undeclared allergens. </a></p>

<p><a title="Back to top" href="#Back to top">Back to top</a></p>
<hr/>

<h2>Food Alert Archives</h2>

<p><a title="Food Alerts - January 2015" href="/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589995948">JANUARY 2015</a></p>
<p><a title="Food Alerts December 2014" href="/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589995339">DECEMBER 2014</a></p>
<p><a title="Food Alerts November 2014" href="/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589995388">NOVEMBER 2014</a></p>

<hr/>

<h2>Links for Information on National Food Recall: </h2>
<p><a title="http://www.fda.gov/Safety/Recalls/default.htm" href="http://www.fda.gov/Safety/Recalls/default.htm">FDA Recall site (non-meat items)</a></p>
<p><a title="http://www.fsis.usda.gov/Fsis_recalls/" href="http://www.fsis.usda.gov/Fsis_recalls/">USDA Recall site (meats and foods containing meat)</a></p>
<p><a title="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg" href="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg">Basic recall information for consumers</a></p>
<p><a title="http://www.foodsafety.gov/keep/recalls/" href="http://www.foodsafety.gov/keep/recalls/">Many links to other agencies (also e-mail updates available)</a></p>


<?php include '/home/codio/workspace/includes/footer.html' ?>						