<?php
	$title= "Frequently Asked Questions about Licensing - Medical Device Manufacturers and Distributors" ;
	include '/home/codio/workspace/includes/header.html';
  include '/home/codio/workspace/includes/menus/mdev_menu.html'; 
?>

<p><strong>I manufacture my own devices and I also distribute other manufacturer’s devices. Do I need two licenses?</strong></p>
<p>No. A manufacturer who also distributes other manufacturer’s devices at the same location, only needs to license as a device manufacturer. However, the licensing fee is based on the gross annual sales of both the manufactured and distributed items. A company that manufactures or distributes at more than one physical location must license each location according to the activities conducted at the particular location.</p>

<p><strong>In addition to distributing medical devices, I also intend to distribute food, nonprescription drugs, and compressed medical gases. What type of license do I need?</strong></p>
<p>In order to be eligible for a Multiple Products License, you must be distributing at least two of the following products: medical devices, food, nonprescription drugs, and/or compressed medical gases. A separate license is needed if you are doing any manufacturing or distribution of prescription drugs other than compressed medical gases. Please visit our <a title="multiple product licenses" href="/medical-devices/forms.aspx#multiple-products">Multiple Products website</a> for further information.</p>
<p><strong>Can my private residence be licensed as a device manufacturer or distributor?</strong></p>
<p>No manufacturing, assembling, packaging, packing, holding, testing, or labeling operations of devices by device manufacturers or distributors shall be conducted in any personal residence.</p>
<p><strong>Your license application form requests information concerning the types of devices I manufacture or distribute. What are Class I, II and III devices?</strong></p>
<p>The U.S. Food and Drug Administration (FDA) is responsible for classifying all devices based upon the level of control necessary to assure the safety and effectiveness of the device. </p> 
<p>Class I devices are subject to the least regulatory control and usually present minimal potential for harm to the user. Examples of Class I devices include elastic bandages, examination gloves, non-absorbable gauze, manual wheelchairs, crutches, walkers, nonprescription sunglasses, incontinence garments, eye pads and enema kits.</p>
<p>Class II devices are those for which general controls alone are insufficient to assure safety and effectiveness and are therefore also subject to special controls. Examples of Class II devices include powered wheelchairs, infusion pumps, sterile surgical drapes, blood glucose meters, nebulizers, x-ray systems, TENS units, oxygen concentrators, lasers and diagnostic ultrasound devices.</p>
<p>Class III devices are subject to the most stringent regulatory controls and are those for which insufficient information exists to assure safety and effectiveness solely through general or special controls. Class III devices are usually those that support or sustain human life, are of substantial importance in preventing impairment of human health, or which present a potential, unreasonable risk of illness or injury. Examples of Class III devices include implantable defibrillators, coronary stents, spinal cord stimulators, hip joint implants and cardiopulmonary bypass pumps.</p>
<p>For more information concerning device classifications, please visit the FDA <a title="Classify Your Medical Device" href="http://www.fda.gov/MedicalDevices/DeviceRegulationandGuidance/Overview/ClassifyYourDevice/default.htm">Classify Your Medical Device</a> web page.</p>

<p><strong>My company is a corporation and your license application form asks for a Registered Agent. Who is that?</strong></p>
<p>The Texas Business Organizations Code (“BOC”) requires every domestic or foreign filing entity to maintain a registered agent and office in Texas. The BOC also permits the filing of an appointment of agent for service of process by an unincorporated nonprofit association. Additionally, the Texas Finance Code permits a Texas financial institution to appoint an agent for service of process. An entity’s registered agent is an agent of the entity on whom may be served any process, notice, or demand required or permitted by law to be served on the entity. Section 5.201(b) of the BOC requires that registered agents designated on or after January 1, 2010 must have consented to serve in that capacity in a written or electronic form developed by the Office of the Secretary of State. See <a title="Form 401-A" href="http://www.sos.state.tx.us/corp/forms/401-a-boc.pdf">Form 401-A</a> <span class="small">(PDF, 38KB)</span> and <a title="1 Tex. Admin. Code &#167;79.29" href="http://texreg.sos.state.tx.us/public/readtac$ext.TacPage?sl=R&app=9&p_dir=&p_rloc=&p_tloc=&p_ploc=&pg=1&p_tac=&ti=1&pt=4&ch=79&rl=29">1 Tex. Admin. Code &#167;79.29</a>. </p>

<p>If you do not know the name of your Registered Agent, you should be able to obtain it from your corporation’s Franchise Tax Account Status on the Texas Comptroller of Public Accounts, <a title="Taxable Entity Search" href="https://mycpa.cpa.state.tx.us/coa/Index.html">Taxable Entity Search</a> webpage.</p>

<p><strong>What is a Taxpayer I.D. #?</strong></p>
<p>The requirement to obtain a Texas Sales and Use Tax Permit applies to individuals as well as corporations, firms, partnerships, and all other legal entities. You must obtain a Texas Sales and Use Tax Permit if you are engaged in business in Texas and you: sell tangible personal property in Texas; lease tangible personal property in Texas; or sell taxable services in Texas. For more information, please visit the <a title="Texas Comptroller of Public Accounts" href="http://www.cpa.state.tx.us/">Texas Comptroller of Public Accounts</a> website.</p>

<p><strong>Who can sign a license application form?</strong></p>
<p>We must have the signature of a person who can legally bind the firm to the affirmation statement on the first page of the license application form. Please refer to The <a title="Texas Statutes" href="http://www.statutes.legis.state.tx.us/">Texas Statutes</a>, Business Corporation Act. </p>

<p><strong>I have moved. I have changed the name of my company. I have changed the legal entity of my company. I have sold my company. Does that affect my license?</strong></p>
<p>Yes. The Rules require the license holder to notify the department in writing within ten days of any change which would render the information contained in the application for the license to be no longer accurate. Moving, changing the name of your company and/or changing the legal entity of your company requires you to submit a license application form and pay a fee before the change occurs. If you sell your company, you will need to send us written correspondence so that we can remove you from our records. The new owner will be required to obtain a new license, as licenses are non-transferable.</p>

<p><strong>I no longer do anything that requires me to continue to license. Does the Food and Drug Licensing Office need to know that?</strong></p>
<p>Yes. The Rules require the license holder to notify the department in writing within ten days of any change which would render the information contained in the application for the license to be no longer accurate. If you know you no longer need to license, notify us in writing as soon as possible. State that you no longer need to license, document the date your business ceased operations requiring a license, sign your written statement, and mail to RLU, Food and Drug Licensing Group MC 2835, Texas Department of State Health Services, PO Box 149347, Austin, TX 78714-9347. If you receive a license renewal application form, please check the box on the second page that states “Notice that firm is out of business” or “not required to license/permit”, sign and date the signature box on the first page, and return to us. Phone contact with us alone will not suffice for adequate notification of a change in your operational status.</p>


<?php include '/home/codio/workspace/includes/footer.html' ?>