<?php 
    $title= "Freqently Asked Questions - Certificates of Free Sale" ; 
    include '../includes/header.html'; 
    include '../includes/menus/cfs_menu.html'; 
?>

<p><strong>1. How long does it take to get a certificate after I have submitted my application?</strong></p>
<p>No later than 15 business days of receipt of a completed application, the department shall issue a certificate, deny a certificate, schedule an inspection, and/or request supplemental information. Time frames are suspended any time applicant is requested to submit additional information. </p>
<p>Manufacturers, distributors and wholesalers of cosmetics only are not required to license with DSHS; however, they are required to have a current compliant inspection. If your company requires an inspection and/or product label review, it can take up to 30 business days to process an application.</p>
<p>If you need a license, please contact the Regulatory Licensing Unit at 512 834-6626. </p>
<p>If you need a certificate application follow this link to <a title="Certificate of Freesale and/or Certificate of Origin" href="/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=35261#Free">Certificate of Freesale and/or Certificate of Origin</a>. There is not an option to apply online.</p>
<p><strong>2. Can I send my application by an overnight courier service such as Federal Express to the physical address instead of the P.O. Box address listed on the application to speed up the process?</strong></p>
<p>Sending an application to the physical address of DSHS will actually delay receipt of your application. You can send your application to the physical address of the DSHS Main Campus at 1100 W. 49th Street, Austin, Texas 78756; however, applications received at the Main Campus location must be processed through several channels before they are sent to the staff person who actually processes them. Applications are processed in the Regulatory Licensing Unit, which is located off-site from the Main Campus, and does not accept monies for fees or any type of regular mail. Therefore, the fastest way for your application to reach the Regulatory Licensing Unit is to send it to the P.O. Box address, since this address has been established at the Comptroller of Public Accounts office and is specifically for receipt of applications for Certificates of Free Sale and/or Certificates of Origin. You can send an application to the P.O. Box address via Express Mail (which is overnight delivery) at any U.S. Post Office. Overnight courier services do not deliver to a P.O. Box.</p>
<p><strong>3. Is there any other option other than mailing my application to speed up the process? Can I fax my application?</strong></p>
<p>We do not accept applications sent via facsimile or e-mail, since you are required to submit an original application, signed and dated, along with the appropriate non-refundable fees. However, you can hand-carry your application and fees to the Regulatory Licensing Unit at 8407 Wall St, Austin TX 78754 where it will be stamped with a remittance number and then sent to the fiscal division for processing. You can also take a copy of your application and the receipt for the fees that were paid to the Foods Licensing Group at the same location. Once you have delivered your application and receipt for the fees to the Foods Licensing Group, it can take up to 15 business days for processing. Applications are processed in the order they are received.</p>
<p><strong>4. Do the certificates have an expiration date?</strong></p>
<p>Yes, based on the license expiration date or inspection date of the company. Certificates are valid for the lesser of the term of the license or the inspection interval. Expiration dates are applied on the certificates by the department. The company must have passed the inspection (compliant inspection). For manufacturers, of food, drug, medical device products, the certificates are valid for 12 months from the date of the last compliant inspection. For manufacturers, distributors, or wholesalers of cosmetic products, the certificates are valid for 24 months. For distributors or wholesalers of foods, drugs, or medical devices, the certificates are valid for 24 months. For producers, processors, and distributors of milk or dairy, frozen dessert, and molluscan shellfish products, the certificates are valid for three (3) months from the date of the last compliant inspection.</p>
<p><strong>5. Can I add or delete products to my product list after I have sent it to the department?</strong></p>
<p>No. We cannot add products to your product list once an application has been received by DSHS since your fees are based on the number of products for the first original certificate. All fees are non-refundable. However, we can delete or replace products since this does not add an additional cost to your fees. For example, if your list contained the product “whole milk” and you wanted to change this product to “2% reduced-fat milk,” or your list contained “black-eyed peas” and you wanted to change this product to “canned peaches,” we could make this change to your product list at no additional cost to you or to DSHS.</p>
<p><strong>6. How do I figure out how many certificates I will need? Can I just order one (1) original certificate and make copies to use for my shipments?</strong></p>
<p>We can issue as many original certificates to your company as you request on your application and payment of the correct amount of fees. Each original certificate is signed, dated and notarized, and is an official governmental document. It is a felony offense under the Texas Penal Code '32.21 or '37.10 to forge (alter, reproduce, or make) or tamper with the certificate. Therefore, if you are unsure of how many certificates you will need, you may want to contact the person or country you are shipping your products to in order to ascertain what documents are required by the receiving country. Many companies request one original certificate per shipment of products. If you are planning to ship the same products periodically over a period of time, it may save your company money to request additional original certificates. If you are planning to ship the same products listed on the application, and then decide to ship additional products, you will be required to submit a new application since you cannot alter the original certificate.</p>
<p><strong>7. How do I calculate what my fees will be?</strong></p>
<p>On Page 2 of the Application Form, there is a Fee Schedule to help you calculate your fees based on the number products you want to list and the number of certificates you are requesting. The first original of each Certificate of Free Sale and/or Certificate of Origin has a fee based on the amount of products you wish to list. You only pay for the number of products once. Each additional identical certificate is about 10% of the base fee. </p>
<p>For example, if your first original lists 110 products, the cost of the original certificate would be $60.00 and each additional identical certificate would cost $6.00. </p>
<p>Another example is if you are requesting one original Certificate of Free Sale and one original Certificate of Origin with one product on each certificate, and you needed one additional original of each certificate, you would calculate your fees as follows:</p>
<p><u>   2  </u>  original certificates x $50.00 (this is the first Certificate of Free Sale, and the first Certificate of Origin with 1 product listed on each) = $100.00<br /><u>   2  </u>  additional certificates x $5.00 per certificate (your certificates have 1 product listed) = $10.00<br />TOTAL = $110.00</p>
<p>$  100.00<br /><u>+    10.00<br /></u>$  110.00</p>
<p><em>Please see below for the entire fee schedule:</em></p>
<p>$50 for 1 - 50 products per original certificate; $5 for each additional identical certificate</p>
<p>$60 for 51 - 200 products per original certificate; $6 for each additional identical certificate </p>
<p>$75 for 201 - 500 products per original certificate; $8 for each additional identical certificate </p>
<p>$100 for 501 - 1000 products per original certificate; $10 for each additional identical certificate </p>
<p>$150 for 1001+ products per original certificate; $15 for each additional identical certificate</p>
<p><strong>8. Can I mix food and non-food products on one certificate?</strong></p>
<p>We cannot list food and non-food products on one certificate. Food products are approved by the <a title="Foods Group" href="http://www.dshs.state.tx.us/foods">Foods Group</a> of DSHS, and the non-food products (i.e., drugs, cosmetics, and medical devices) are approved by the <a title="Drugs and Medical Devices Group" href="http://www.dshs.state.tx.us/dmd">Drugs and Medical Devices Group</a> of DSHS. You must submit a separate application for the food and non-food products with separate product lists for each food and non-food product. </p>
<p><strong>9. How long does it take to get an inspection scheduled?</strong></p>
<p>Once an application is received by Regulatory Licensing Unit, DSHS has 30 business days from the date the application is received to schedule and complete an inspection. The inspections are scheduled by the appropriate group of DSHS that will be conducting the inspection. Once the inspection has been completed and the company is in compliance with applicable laws, rules, and regulations, the appropriate group notifies the appropriate staff in the Regulatory Licensing Unit and the application is processed.</p>
<p><strong>10. How are certificates sent to the requestor after they are prepared?</strong></p>
<p>On the application form, there is a space for a company to indicate how they would like for the certificate to be sent. If a company prefers that the certificate be sent to them via an overnight courier service such as Federal Express, Airborne Express, etc., the requestor=s account number must be included on the application. It is not necessary to include an invoice or an envelope for the specific courier service. DSHS has access to the appropriate supplies for each courier service that operates in the State of Texas. If there is no indication of how a requestor would like for the certificates to be sent, the certificate will be sent via regular first class mail. </p>
<p>There have been instances where the certificates are sent to the requestor via regular first class mail and the certificates are subsequently lost in the mail. This causes undue hardship on the company requesting the certificates, and also costs DSHS additional staff time and money. In order to avoid having to resubmit a new application and non-refundable fees due to this situation, we recommend that companies indicate on their application form that the certificates be mailed to them via an overnight courier service and include their account number for billing purposes.</p>
<p><strong>11. Where can I find the statute and rules for Certificates of Free Sale and Certificates of Origin? </strong></p>
<p>The statute is the <a title="Texas Health and Safety Code, Chapter 431, §431.241(g)" href="http://www.statutes.legis.state.tx.us/Docs/HS/htm/HS.431.htm#431.241">Texas Health and Safety Code, Chapter 431, §431.241(g)</a>, and the rules are <a title="Title 25, Texas Administrative Code, Chapter 229, Subchapter R, §§229.301 – 229.307" href="http://info.sos.state.tx.us/pls/pub/readtac$ext.ViewTAC?tac_view=4&amp;ti=25&amp;pt=1&amp;ch=229">Title 25, Texas Administrative Code, Chapter 229, Subchapter R, §§229.301 – 229.307</a>. </p>
<p><strong>12. Who do I contact if I am exporting meat and poultry products from Texas? </strong></p>
<p>Rick Harries, Director, Export Programs Staff<br />(202) 720-0082<br />FAX: (202) 720-7990</p>

<?php include '../includes/footer.html' ?>