<?php
	$title= "Sample Certificates - Food Handler Certification" ;
	include '..//home/codio/workspace/includes/header.html';
	include '..//home/codio/workspace/includes/menus/foodhand_menu.html'; 
?>

<h2>Accredited Food Handler Training Programs "Sample Certificates"</h2>
<p>All Food Handler Certificates now display a watermark in the form of text, graphics or background. The watermarks were added June 1, to September 28, 2009, to ensure certificate authenticity. If you have a question regarding a food handler certificate, please contact the issuing Food Handler Program for information or verification.</p>
<p><a title="A + Food Industry Inspections, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589953078">A + Food Industry Inspections, Inc.</a> <span class="small">(PDF, 86KB)</span> </p>
<p><a title="Absolutely Certified Texas Food Handler Program" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589982937">Absolutely Certified Texas Food Handler Program</a> <span class="small">(PDF 1.3MB)</span></p>
<p><a title="Adept On-Site Services" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589967390">Adept On-Site Services</a> - Effective May 7, 2012  <span class="small">(PDF, 119KB)</span></p>
<p><a title="Adept On-Site Services" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934904">Adept On-Site Services</a> - Prior to May 7, 2012   <span class="small">(PDF, 46KB)</span></p>
<p><a title="Advance Service Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589943240">Advance Service Training</a> <span class="small">(PDF, 1.4MB)</span> </p>
<p><a title="Allen I. S. D. Student Nutrition Program" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589937927">Allen I. S. D. Student Nutrition Program</a> <span class="small">(PDF, 30KB)</span></p>
<p><a title="Brookshire Grocery Company" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589958731">Brookshire Grocery Company</a> <span class="small">(PDF, 205KB)</span></p>
<p><a title="Caritas of Austin" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589981659">Caritas of Austin</a> <span class="small">(PDF, 270KB)</span></p>
<p><a title="City of Austin EHS Food Handler Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589965355">City of Austin EHS Food Handler Training</a> <span class="small">(PDF, 80KB)</span></p>
<p><a title="City of Baytown Food Handler Certificate" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968483">City of Baytown Food Handler Certificate</a> <span class="small">(PDF, 131KB)</span></p>
<p><a title="City of Gun Barrel City Food Handler Program" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589995657">City of Gun Barrel City Food Handler Program</a> <span class="small">(PDF, 264KB)</span></p>
<p><a title="CST SERVICES LLC" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589977079">CST SERVICES LLC</a> <span class="small">(PDF, 273KB) -- (Formerly  <a title="Valero Retail Holding Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589946918">Valero Retail Holding Inc.</a> PDF, 742KB)</span> </p>
<p><a title="DFW Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589974711">DFW Food Handlers</a> - Effective February 5, 2013 <span class="small">(PDF, 195KB)</span></p>
<p><a title="eFoodHandlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589981683">eFoodHandlers</a> <span class="small">(PDF, 61KB)</span></p>
<p><a title="El Paso Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18713">El Paso Food Handlers</a> <span class="small">(PDF, 142KB) -- (Currently known as <a title="Food Handlers of Texas" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934880">Food Handlers of Texas</a> PDF, 209KB)</span></p>
<p><a title="First Defense Food Handler Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934911">First Defense Food Handler Training</a> <span class="small">(PDF, 29KB)</span></p>
<p><a title="Food Handler Classes" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=52061">Food Handler Classes</a> <span class="small">(PDF, 334KB)</span></p>
<p><a title="Food Handler Classes" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935975">Food Handler Classes</a> <span class="small">(PDF, 69KB)</span></p>
<p><a title="Food Handlers of Texas" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934880">Food Handlers of Texas</a>  <span class="small">(PDF, 209KB) -- (formerly <a title="El Paso Food Handlers" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18713">El Paso Food Handlers</a> PDF, 145KB)</span></p>
<p><a title="Food Marketing Institute (FMI)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=52058">Food Marketing Institute (FMI)</a> <span class="small">(PDF, 425KB)</span></p>
<p><a title="Food Safety Direct (in English)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589991218">Food Safety Direct (in English)</a> <span class="small">(PDF, 259KB)</span></p>
<p><a title="Food Safety Direct (in Spanish)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589991219">Food Safety Direct (in Spanish)</a> <span class="small">(PDF, 274KB)</span></p>
<p><a title="Food Safety International, L.L.C." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934895">Food Safety International, L.L.C.</a>   <span class="small">(PDF, 618KB)</span></p>
<p><a title="Food Safety Sense" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589986800">Food Safety Sense</a> - Effective March 26, 2014  <span class="small">(PDF, 124KB)</span></p>
<p><a title="Food Safety Sense" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18722">Food Safety Sense</a> - Prior to March 26, 2014   <span class="small">(PDF, 145KB)</span></p>
<p><a title="Food Safety Training Course" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589986554">Food Safety Training Course</a> <span class="small">(PDF, 66KB)</span></p>
<p><a title="Healthinspectionorg" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589936213">Healthinspectionorg</a> <span class="small">(PDF, 384KB)</span></p>
<p><a title="Jack in the Box" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18730">Jack in the Box</a> <span class="small">(PDF, 290KB)  </span></p>
<p><a title="Learn2Serve.com Effective Effective June 2014" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589988571">Learn2Serve.com Effective Effective June 2014</a> <span class="small">(PDF, 663KB)</span></p>
<p><a title="Learn2Serve.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589977763">Learn2Serve.com</a> - Effective Prior to June 2014 <span class="small">(PDF, 631KB)  </span></p>
<p><a title="Learn2Serve.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18732">Learn2Serve.com</a> - Prior to June 4, 2013 <span class="small">(PDF, 1.2MB)</span></p>
<p><a title="Lone Star Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589982240">Lone Star Food Safety</a>  <span class="small">(PDF, 673KB)</span></p>
<p><a title="MarksSafetyConsultSvcSampleCertEffDecember" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589970985">Marks Safety Consultant Service</a> - Effective December 2014 <span class="small">(PDF, 301KB)</span></p>
<p><a title="MarksSafetyConsultSvcSampleCertPrior" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589994673">Marks Safety Consultant Service</a> - Prior to December 2014 <span class="small">(PDF, 884KB)</span></p>
<p><a title="MindLeaders, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935888">MindLeaders, Inc.</a> - Prior to October 2014 – <span class="small">(PDF, 145KB) -- (Currently known as <a title="Skillsoft Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993241">Skillsoft Corporation</a> PDF,115KB)</span></p>
<p><a title="Mineral Wells, City of" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589992501">Mineral Wells, City of</a> - Effective October 2014  <span class="small">(PDF, 362KB)</span></p>
<p><a title="Mineral Wells, City of" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934915">Mineral Wells, City of</a> - Prior to October 2014 <span class="small">(PDF, 63KB)</span></p>
<p><a title="Ms. Ree's Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934879">Ms. Ree's Food Safety</a> <span class="small">(PDF, 123KB)</span></p>
<p><a title="MyFoodHandler.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589980043">MyFoodHandler.com</a> <span class="small">(PDF, 1.5MB)</span></p>
<p><a title="National Registry of Food Safety Professionals" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589978679">National Registry of Food Safety Professionals</a> - Effective February 13, 2013 <span class="small">(PDF, 149KB)</span></p>
<p><a title="National Registry of Food Safety Professionals" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18742">National Registry of Food Safety Professionals</a> - Prior to February 13, 2013   <span class="small">(PDF, 290KB)</span></p>
<p><a title="NEHA Food Safety Training&amp;nbsp;" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=52064">NEHA Food Safety Training </a> <span class="small">(PDF, 1.6MB)</span></p>
<p><a title="Plano, City of" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18745">Plano, City of</a> <span class="small">(PDF, 72KB)</span></p>
<p><a title="Premier Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589964510">Premier Food Safety</a> - Effective February 23, 2012 <span class="small">(PDF, 598KB)</span></p>
<p><a title="Premier Food Safety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589960968">Premier Food Safety</a> - Prior to February 23, 2012 <span class="small">(PDF, 754KB)</span> </p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589983906">Professional Server Certification Corporation</a> - Effective January 2, 2014 <span class="small">(PDF, 1MB)</span></p>
<p><a title="Professional Server Certification Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589983905">Professional Server Certification Corporation</a> Wallet Card Effective January 2, 2014 <span class="small">(PDF, 186KB)</span></p>
<p><a title="Public Health Education" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18748">Public Health Education</a> <span class="small">(PDF, 74KB)</span></p>
<p><a title="RaceTrac Petroleum, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589984322">RaceTrac Petroleum, Inc.</a> - Effective January 10, 2014 <span class="small">(PDF, 265KB)</span></p>
<p><a title="RaceTrac Petroleum, Inc." href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589963657">RaceTrac Petroleum, Inc.</a> - Prior to January 10, 2014 <span class="small">(PDF, 177KB)</span></p>
<p><a title="RGV Certification Zone" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589996416">RGV Certification Zone</a> <span class="small">(PDF, 184KB)</span></p>
<p><a title="Safe Food Solutions" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589990108">Safe Food Solutions</a> #59 - Effective July 2014 <span class="small">(PDF, 72KB)</span></p>
<p><a title="Safe Food Solutions" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968516">Safe Food Solutions</a> - Prior to July 2014 <span class="small">(PDF, 163KB)</span></p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972811">Safe Food 4 U</a> - Effective November 2012 <span class="small">(PDF, 441KB)</span></p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972810">Safe Food 4 U</a> - Effective November 2012 <span class="small">(PDF, 213KB)</span>  </p>
<p><a title="Safe Food 4 U" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935511">Safe Food 4 U</a> - Prior to November 2012 <span class="small">(PDF, 281KB)</span></p>
<p><a title="Safe Food 4 U (Spanish)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589965906">Safe Food 4 U (Spanish)</a> <span class="small">(PDF, 102KB)</span></p>
<p><a title="StateFoodTest.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972812">SafeFoodTest.com</a> - <span class="small">(PDF, 3.4MB)</span></p>
<p><a title="ServSafe Starters - Classroom" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18757">ServSafe Starters - Classroom</a> <span class="small">(PDF, 290KB)</span></p>
<p><a title="ServSafe Starters - Online" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18759">ServSafe Starters - Online</a> <span class="small">(PDF, 2.3MB)</span></p>
<p><a title="Skillsoft Corporation" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993241">Skillsoft Corporation</a> - Effectiv8e October 2014 – <span class="small">(PDF, 115KB) -- (Formerly <a title="MindLeaders Inc" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935888">MindLeaders Inc</a>. PDF, 145KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993430">StateFoodSafety.com</a> - Effective November 2014 <span class="small">(PDF, 826KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589991087">StateFoodSafety.com</a> - Prior to November 2014 <span class="small">(PDF, 64KB)</span></p>
<p><a title="StateFoodSafety" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589970268">StateFoodSafety.com</a> - Prior August 2014 <span class="small">(PDF, 343KB)</span></p>
<p><a title="StateFoodSafety.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589935918">StateFoodSafety.com</a> - Prior August 2012 <span class="small">(PDF, 236KB)</span></p>
<p><a title="Sonic Drive-In" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589981663">Sonic Drive-In</a> <span class="small">(PDF, 1.8MB)</span></p>
<p><a title="Stripes" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=52068">Stripes</a> <span class="small">(PDF, 82KB)</span></p>
<p><a title="Texas A&amp;amp;M AgriLife Extension Service License # 76 " href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589989775">Texas A&amp;M AgriLife Extension Service</a> - Effective July 2014 <span class="small">(PDF, 55KB)</span></p>
<p><a title="Texas AgriLife Extension Service" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589969466">Texas A&amp;M AgriLife Extension Service</a> - Effective April 2012  <span class="small">(PDF, 92KB)</span></p>
<p><a title="Texas AgriLife Extension Service" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18763">Texas A&amp;M AgriLife Extension Service</a> - Prior to April 21, 2012  <span class="small">(PDF, 145KB)</span></p>
<p><a title="Texas Best Food Services Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589980041">Texas Best Food Services Training</a> <span class="small">(PDF, 2.8MB)</span></p>
<p><a title="TexasFoodCard.com license" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589994179">TexasFoodCard.com</a> - Effective December 2014 (<span class="small">PDF 335MB</span>)</p>
<p><a title="TexasFoodCard.com, license" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589993112">TexasFoodCard.com</a> - Prior to December 2014 (<span class="small">PDF 1.9MB</span>)</p>
<p><a title="Texas foodcard.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18764">Texas FoodCard.com</a> - Prior to October 2014 <span class="small">(PDF, 902KB)</span></p>
<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589978268">TexasFoodHandler.com/Safeway Certifications</a> - Effective June 2013 <span class="small">(PDF 252KB</span>)</p>
<p><a title="TexasFoodHandler.com/Safeway Certifications" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968423">TexasFoodHandler.com/Safeway Certifications</a> - Prior to June 2013 <span class="small">(PDF, 640KB)</span></p>
<p><a title="Texas Food Safety Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589977705">Texas Food Safety Training</a> - Effective February 20155 <span class="small">(PDF, 3.5MB)</span></p>
<p><a title="Texas Food Safety Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589996107">Texas Food Safety Training</a> - Prior to February 2015 <span class="small">(PDF, 3.4MB)</span></p>
<p><a title="Texas Online Food Handler" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589988057">Texas Online Food Handler</a> <span class="small">(PDF, 306KB)</span></p>
<p><a title="Texas State University - San Marcos Food Handler Program" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589977706">Texas State University - San Marcos Food Handler Program</a>  <span class="small">(PDF, 392KB)</span></p>
<p><a title="Texoma Food Service" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18766">Texoma Food Service</a> <span class="small">(PDF, 72KB)</span></p>
<p><a title="Thornhill Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589972506">Thornhill Training</a> - Effective November 2012 <span class="small">(PDF 294KB)</span></p>
<p><a title="Thornhill Training" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18774">Thornhill Training</a>  - Prior to November 2012 <span class="small">(PDF, 580KB)</span></p>
<p><a title="Tokyo Gardens Catering, LLC" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=52071">Tokyo Gardens Catering, LLC</a> <span class="small">(PDF, 368KB)</span></p>
<p><a title="Training Achievement Program (TAP series)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589988572">Training Achievement Program (TAP series)</a> - Effective June 2014 <span class="small">(PDF, 187KB)</span></p>
<p><a title="Training Achievement Program (TAP series)" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589968521">Training Achievement Program (TAP series)</a> - Prior to June 2014 <span class="small">(PDF, 1MB)</span></p>
<p><a title="Valero Retail Holdings, Inc" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589946918">Valero Retail Holdings, Inc.</a> -- <span class="small">(Currently known as <a title="CST Services LLC" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589977079">CST Services LLC</a> PDF, 759KB) </span></p>
<p><a title="Wal-Mart" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589977862">Wal-Mart</a> <span class="small">(PDF, 673KB)</span></p>
<p><a title="Western Refining" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589981751">Western Refining</a> <span class="small">(PDF, 331KB)</span></p>
<p><a title="Whole Foods Markets - Southwest" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=18777">Whole Foods Markets - Southwest</a> <span class="small">(PDF, 145KB)</span></p>
<p><a title="World Credential Diagnostic" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589958631">World Credential Diagnostic</a> <span class="small">(PDF 335KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589984029">www.TrainingNow.com</a> - Effective January 7, 2014 <span class="small">(PDF, 197KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589976686">www.TrainingNow.com</a> - Prior to January 7, 2014 <span class="small">(PDF, 96KB)</span></p>
<p><a title="www.TrainingNow.com" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589971977">www.TrainingNow.com</a> - Prior to April 26, 2013  <span class="small">(PDF, 349KB)</span></p>
<p><a title="Zepol Dietary Consults" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589987732">Zepol Dietary Consults</a> - Effective April 1, 2014 <span class="small">(PDF 401KB)</span> </p>
<p><a title="Zepol Dietary Consults" href="http://www.dshs.state.tx.us/WorkArea/linkit.aspx?LinkIdentifier=id&amp;ItemID=8589934912">Zepol Dietary Consults</a> - Prior to April 1, 2014   <span class="small">(PDF, 106KB)</span></p>

<?php include '../../includes/footer.html' ?>