<?php
	$title= "Food Alerts and Recalls Affecting Texas - Food Manufacturers and Distributors" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/foods_menu.html'; 
?>

<h2>Sources for Recall Information Include:</h2>
<ul>
	<li><a title="USDA Current Recalls and Alerts" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/current-recalls-and-alerts" target="_blank">USDA Current Recalls and Alerts</a></li>
	<li><a title="FDA Recalls, Market Withdrawals, &amp; Safety Alerts" href="http://www.fda.gov/Safety/Recalls/default.htm" target="_blank">FDA Recalls, Market Withdrawals, &amp; Safety Alerts</a></li>
<li><a title="FDA Enforcement Reports" href="http://www.fda.gov/Safety/Recalls/EnforcementReports/default.htm">FDA Enforcement Reports</a></li>
</ul>

<hr>
<h2>March 9, 2015</h2>
<ul>
	<li><strong>Washington Harvest Wapato is recalling The World's Finest Mixed Fruit containing Red Delicious Apples, Granny Smith Apples and Navel Oranges, packed in poly bags 6/4 lb. bags per case, and Fast &amp; Fresh Grab Mixed Apples And/or Oranges containing Fuji Apples, Granny Smith Apples and Oranges, packed in poly bags 10/4 lb. bags per case or 8/5lb. mesh bags per case, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a></li><br/>
	<li><strong>Kabobs Inc. is recalling Frozen Shrimp Empanada 100 count, Frozen Vegetable Empanada 100 count, and Frozen Yucatan Style Roasted Corn &amp; Black Bean Tart, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a></li><br/>
	<li><strong>Gulf Coast Blenders, Inc. is recalling several spices and seasonings sold under different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a></li><br/>
	<li><strong>Schwan Food Company is recalling Holiday Foods Hors D'Oeuvre Vegetable Samosa Triangle, 60 1.5 oz., and Holiday Foods Hors D'Oeuvre Vegetable Samosa Potsticker, 100 0.7 oz pieces , both for institutional use only, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a></li><br/>
	<li><strong>Harvest Food Group, Inc. is recalling Tommy's Superfoods&nbsp; Seasoned Santa Fe Rice packed in 10 oz. (284 g) plastic film bags and Tastee Western Rice packaged in 40 lb. corrugated boxes with blue poly liners, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1302-2015&amp;amp;w=03042015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1302-2015&amp;w=03042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1302-2015&amp;w=03042015&amp;lang=eng</a></li><br/>
	<li><strong>Sugar Daddy LTD is recalling Caramel Apples labeled as Merbs Candies, Double Dipped individually wrapped in plastic, and Caramel and Pecan Apple labeled as Merbs Candies, Bionic Apple packaged in plastic wrappers, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a></li><br/>
	<li><strong>Adams Extract &amp; Spice LLC is recalling several spices and seasonings sold under different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a></li><br/>
	<li><strong>Relish Foods Inc. is recalling Pacific Fusion Frozen Tuna Steak Wild Caught net wt. 15 lb. (240 oz.) 6.80 kg, due to elevated levels of histamine.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-0801-2015&amp;amp;w=03042015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0801-2015&amp;w=03042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0801-2015&amp;w=03042015&amp;lang=eng</a></li><br/>
	<li><strong>Maternal Science, Inc. is recalling healthy mama® Boost It Up! Mighty Mango with Ginger&nbsp; 12 fl oz. packaged in a bottle and healthy mama® Boost It Up! Mighty Mango 12 fl oz. packaged in a bottle, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm436491.htm" href="http://www.fda.gov/Safety/Recalls/ucm436491.htm">http://www.fda.gov/Safety/Recalls/ucm436491.htm</a></li><br/>
	<li><strong>Rio Tex Wholesale Meats is recalling Hausman Foods Brand Cooked Beef Taco Filling Seasoned Cooked Beef Barbacoa, Fully Cooked Barbacoa, and Beef Carne Guisada packaged in 20-lb. boxes containing four 5-lb. packages, and Rio-Tex-Meats Barbacoa packaged in 15-lb. and 45-lb. boxes containing three 5-lb. or 15-lb. packages, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release</a></li><br/>
	<li><strong>Campos Foods, LLC is recalling H-E-B Fully Cooked Thick N’ Tasty Cheese Burgers Natural Smoke Flavor Added net wt. 15-oz. (425g) bag containing four 3.75-oz. burgers and net wt. 30-oz. (1.87lbs) (850g) bag containing eight 3.75-oz. burgers, and H-E-B Fully Cooked Thick N’ Tasty&nbsp; Bacon Cheese Burgers Natural Smoke Flavor Added net wt. 30-oz. (1.87lbs) (850g) bag containing eight 3.75-oz. burgers, misbranding and undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release</a></li><br/>
</ul>
<h2><hr>
</h2>
<h2>March 2, 2015</h2>
<ul>
	<li><strong>Hamchorom Inc. is recalling Haitai Tayo Crackers (140 g) 24 boxes/carton, in box colors: blue, yellow, and red, and Haitai Gyeran Crackers (70 g) 20 boxes/carton, in yellow box with "Angry Birds" logo, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food</a></li><br/>
	<li><strong>Probar LLC is recalling Frosted Peanut Butter BASE Protein Bar, 2.46 oz., film wrapped bar packaged in 12 wrapped units per sleeve/carton, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1224-2015&amp;amp;w=02252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng</a></li><br/>
	<li><strong>Talenti® Gelato &amp; Sorbetto is recalling Talenti® Gelato &amp; Sorbetto Sea Salt Caramel Gelato packaged in one pint (473 mL) clear plastic jars, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm436020.htm" href="http://www.fda.gov/Safety/Recalls/ucm436020.htm">http://www.fda.gov/Safety/Recalls/ucm436020.htm</a></li><br/>
	<li><strong>Fairway “Like No Other Market” is recalling Fairway brand Raw Hazelnuts (Filberts), packaged in clear, plastic cello bags of varying weights, each weighing less than one pound, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435547.htm" href="http://www.fda.gov/Safety/Recalls/ucm435547.htm">http://www.fda.gov/Safety/Recalls/ucm435547.htm</a></li><br/>
	<li><strong>Oscar’s Hickory House Inc. is recalling Oscar’s Adirondack Mountain Smokehouse Beef Jerky in 4 oz. and 8 oz. cryovac packages, due to a processing deviation.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release</a></li><br/>
</ul>
<hr>
<h2>February 24, 2015</h2>
<ul>
	<li><strong>Freeland Foods Inc. is recalling Go Raw 100% Organic Sunflower Seeds; Net Wt. 1 lb. (454 g), due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1196-2015&amp;amp;w=02182015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1196-2015&amp;w=02182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1196-2015&amp;w=02182015&amp;lang=eng</a></li><br/>
	<li><strong>HVL, LLC is recalling Melatonin Control- Released Tablets, 60 tablets, in plastic bottles, due to mislabeling.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1202-2015&amp;amp;w=02182015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1202-2015&amp;w=02182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1202-2015&amp;w=02182015&amp;lang=eng</a></li><br/>
	<li><strong>Kellogg USA Inc. is recalling MorningStar Farms Spicy Black Bean Burger and MorningStar Farms Chipotle Black Bean Burger, due to undeclared allergens.</strong><br/>Please see the FDA Enforcement Report, Week of February 18, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02182015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food</a></li><br/>
	<li><strong>Full Tilt Ice Cream is recalling several flavors of ice cream packaged in 16 oz. paper containers, and 1.5 gallon and 3 gallon plastic tubs, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of February 18, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02182015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food</a></li><br/>
	<li><strong>El Popocatepetl Ind., Inc. is recalling El Popocatepetl’s 8 in. Chipotle, Spinach Pesto, and Sun Dried Tomato Wraps, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435190.htm" href="http://www.fda.gov/Safety/Recalls/ucm435190.htm">http://www.fda.gov/Safety/Recalls/ucm435190.htm</a></li><br/>
	<li><strong>WhiteWave Foods is recalling Horizon Cheddar Sandwich Crackers (7.5 oz.), due to undeclared allergens. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435172.htm" href="http://www.fda.gov/Safety/Recalls/ucm435172.htm">http://www.fda.gov/Safety/Recalls/ucm435172.htm</a></li><br/>
	<li><strong>Con Yeager Spice Company is recalling multiple sized packages under multiple brand names of ground cumin and multiple seasoning blends (containing ground cumin) due to undeclared allergens.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435171.htm" href="http://www.fda.gov/Safety/Recalls/ucm435171.htm">http://www.fda.gov/Safety/Recalls/ucm435171.htm</a></li><br/>
	<li><strong>Old Home Kitchens is recalling Sock It To Me Crème Cake under the “Bakery baked with pride" label, packaged in plastic domes, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435170.htm" href="http://www.fda.gov/Safety/Recalls/ucm435170.htm">http://www.fda.gov/Safety/Recalls/ucm435170.htm</a></li><br/>
	<li><strong>Goya Foods, Inc. is recalling Kirby Black Beans Creole Seasoning (29 oz.) and Goya Black Bean Soup (29 oz.), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434542.htm" href="http://www.fda.gov/Safety/Recalls/ucm434542.htm">http://www.fda.gov/Safety/Recalls/ucm434542.htm</a></li><br/>
	<li><strong>ESS Food is recalling Pini Polona Pork Belly Boneless (40 lb.) packaged in boxes containing 4-5 pieces, due to not being presented at the U.S. point of entry for inspection.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release</a></li><br/>
</ul>

<hr>
<h2>February 18, 2015</h2>
<ul>
	<li><strong>High Road Craft Ice Cream, Inc. is recalling High Road Craft Ice Cream &amp; Sorbet, Limoncello Sorbet packed in 4.9L (1.3 gallon) tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-0967-2015&amp;amp;w=02112015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0967-2015&amp;w=02112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0967-2015&amp;w=02112015&amp;lang=eng</a></li><br/>
	<li><strong>Zilks Foods is recalling several flavors of Zilks brand Hummus (8 oz.), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a></li><br/>
	<li><strong>Gemini Food Corporation Inc. is recalling Description&nbsp; Dried Bean Curd Satay Flavor (150g), Dried Bean Curd Anka Flavor (150g), Dried Bean Curd Chili Flavor (150g), Dried Bean Curd Spicy Flavor (150g), and Dried Bean Curd Garlic Flavor (150g), to due possible dimethyl yellow contamination.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a></li><br/>
	<li><strong>Reily Foods Co. is recalling Carroll Shelby’s Original Texas Brand Chili Kit (4 oz.)( 113 g), Carroll Shelby’s Original Texas Brand White Chicken Chili kit (3 oz.) (85 g), Wick Fowler’s Famous Texas Style 2-Alarm Chilli Kit (3.6525 oz.) (102 g), and Wick Fowler’s Famous Texas Style False Alarm Mild&nbsp; Chilli Kit (3.03 oz.) (86 g), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a></li><br/>
	<li><strong>Riba Foods Inc. is recalling Arriba! Chili Con Queso-Hot (16 oz.), Salpica Salsa Con Queso (11.5 oz. &amp;16 oz.), Salpica Ballpark Nacho (8 oz.), Salpica Black Bean Nacho (8 oz.), Crate &amp; Barrel&nbsp; Monterey Jack Queso Dip (11.5 oz.), and Salpica Jalapeno Jack Queso Dip (16 oz.), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a></li><br/>
	<li><strong>Unilever United States, Inc. is recalling Breyers® No Sugar Added Salted Caramel Swirl packaged in 1.5-quart (1.41L) paperboard tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434540.htm" href="http://www.fda.gov/Safety/Recalls/ucm434540.htm">http://www.fda.gov/Safety/Recalls/ucm434540.htm</a></li><br/>
	<li><strong>Whole Foods Market is recalling Chocolate Cake for Two packaged in clear plastic containers, due to undeclared allergens. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434430.htm" href="http://www.fda.gov/Safety/Recalls/ucm434430.htm">http://www.fda.gov/Safety/Recalls/ucm434430.htm</a></li><br/>
	<li><strong>Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder packaged in clear plastic bags (0.25 lb. – 0.30lb.), due to possible Salmonella contamination. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434254.htm" href="http://www.fda.gov/Safety/Recalls/ucm434254.htm">http://www.fda.gov/Safety/Recalls/ucm434254.htm</a></li><br/>
	<li><strong>Michigan Brand, Inc. is recalling Michigan Brand Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and The Jerky Outlet Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and 40 count boxes, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release</a></li><br/>
	<li><strong>Ruiz Foods is recalling Egg Sausage and Cheese Wrapped in a Flour Tortilla packaged in 4.5-lb. cases containing 3 trays with 8 pieces, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release</a></li><br/>
</ul>
<h2><hr>
</h2>
<h2>February 12, 2015</h2>
<ul>
	<li><strong>Sunfood is recalling Organic Sacha Inchi Powder, packaged in&nbsp; 8 oz. white bags, due to possible Staphylococcus enterotoxin contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434009.htm" href="http://www.fda.gov/Safety/Recalls/ucm434009.htm">http://www.fda.gov/Safety/Recalls/ucm434009.htm</a></li><br/>
	<li><strong>Hines Nut Company is recalling Hines Nut Brand Walnut Halves and Pieces (12 or 16 oz.) due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433797.htm" href="http://www.fda.gov/Safety/Recalls/ucm433797.htm">http://www.fda.gov/Safety/Recalls/ucm433797.htm</a></li><br/>
	<li><strong>Detox Transforms Health and Nutrition is recalling EDGE Amplified Weight Release, iNDiGO, AMPD Gold Bee Pollen, BtRim Max, and iNSANE Bee Pollen, all packaged in white bottles with 60 capsules, due to undeclared drug ingredients.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433513.htm" href="http://www.fda.gov/Safety/Recalls/ucm433513.htm">http://www.fda.gov/Safety/Recalls/ucm433513.htm</a></li><br/>
	<li><strong>Korean Food Co. is recalling Go-Hang Soybean Sprouts in 1 lb. and &nbsp;2 lb. plastic bags, and 10 lb. black plastic bags, due to possible Listeria monocytogenes contamination. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433403.htm" href="http://www.fda.gov/Safety/Recalls/ucm433403.htm">http://www.fda.gov/Safety/Recalls/ucm433403.htm</a></li><br/>
	<li><strong>Pepperidge Farm is recalling Cinnamon Raisin Bagels (21 oz. and 17oz.), Plain Mini Bagels (17 oz.), Everything Bagels (21 oz.), Plain Bagels (21 oz.) Brown Sugar/Cinnamon Mini Bagels (17 oz.), and 100% Whole Wheat Mini Bagels (17 oz.), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433775.htm" href="http://www.fda.gov/Safety/Recalls/ucm433775.htm">http://www.fda.gov/Safety/Recalls/ucm433775.htm</a></li><br/>
	<li><strong>See’s Company is recalling Classic Red Hearts with Assorted Chocolates 8 oz., due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433408.htm" href="http://www.fda.gov/Safety/Recalls/ucm433408.htm">http://www.fda.gov/Safety/Recalls/ucm433408.htm</a></li><br/>
	<li><strong>Sunrise Poultry Processors is recalling Sunrise Poultry Brand Chicken Thighs in 40 lb. bulk cases, Chicken Thighs Boneless in 25 lb. cases, Boneless Chicken Breast in 2.5lb. cases, and Chicken Whole Fryer in 2.5 lb., 4 lb., and 3.25-3.75 lb. cases, due to not being presented at the U.S. point of entry for inspection.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release</a></li><br/>
</ul>
<h2><hr>
</h2>
<h2>February 6, 2015 </h2>
<ul>
	<li><strong>Eillien's Candies, Inc. is recalling Walnut Pieces in several sizes, under the following brand names: Eillien’s, Blain’s Farm and Fleet, Mill’s Fleet Farm, Piggly Wiggly, Rural King, and Trig’s, due to possible Salmonella contamination. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng</a><br/></li><br/>
	<li><strong>The Harvard Drug Group, LLC is recalling Thera Tablets with Beta Carotene Dietary Supplement, due to mislabeling. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng</a><br/></li><br/>
	<li><strong>John B. Sanfilippo &amp; Son Inc. is recalling Fisher Brand Chopped Walnuts, and Pecan Cookie Pieces , both packaged in 8 oz. (226 g) plastic bags, due to possible Salmonella contamination. <br/></strong>Please see the FDA Enforcement Report, Week of February 4, 2015 for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food</a><br/></li><br/>
	<li><strong>Zachary Confections, Inc. is recalling Market Pantry Brand Dark Chocolate Covered Almonds (9 oz.), due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng</a><br/></li><br/>
	<li><strong>The Spice Mill is recalling Ground Cumin (2.75 oz.) and Cajun Seasoning (4 oz.), due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432761.htm" href="http://www.fda.gov/Safety/Recalls/ucm432761.htm">http://www.fda.gov/Safety/Recalls/ucm432761.htm</a><br/></li><br/>
	<li><strong>Krehbiel’s Specialty Meats, Inc. is recalling Fresh Beer Bratwurst Made With Tallgrass Brewery Oasis Beer in 16 oz. vacuum sealed packages, due to misbranding. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015</a></li><br/>
</ul>
<hr>
<h2>February 3, 2015 </h2>
<ul>
	<li><strong>Quest Nutrition, LLC is recalling QuestBar Protein Bar Chocolate Chip Cookie Dough Flavor net wt. 2.12 OZ (60 g) and QuestBar Protein Bar Double Chocolate Chunk Flavor net wt. 2.12 OZ (60 g), due to the possibility of plastic pieces introduced into the products by an ingredients supplier. <br/></strong>Please see the FDA Enforcement Report, Week of January 28, 2015 for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food</a><br/></li><br/>
	<li><strong>American Roland Food Corp. is recalling Roland brand Bruschetta, Italian-Style Appetizer (12 oz.) (340g), packaged in a glass jar, due to glass fragment found in product. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng</a><br/></li><br/>
	<li><strong>Hamchorom, Inc. is recalling HAITAI Tayo Crackers (140 g) and HAITAI Gyeran Crackers (70 g), due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432560.htm" href="http://www.fda.gov/Safety/Recalls/ucm432560.htm">http://www.fda.gov/Safety/Recalls/ucm432560.htm</a><br/></li><br/>
	<li><strong>Project Healthy Living, Inc. is recalling all packages of Premium Protein powder in chocolate and vanilla blends in both 14-serving sized steel tins and single-serving sized pouches, due to possible Staphylococcus enterotoxins contamination. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432558.htm" href="http://www.fda.gov/Safety/Recalls/ucm432558.htm">http://www.fda.gov/Safety/Recalls/ucm432558.htm</a><br/></li><br/>
	<li><strong>Freeland Foods, Inc. is recalling Go Raw Organic Sunflower Seed, due to possible Salmonella contamination. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432417.htm" href="http://www.fda.gov/Safety/Recalls/ucm432417.htm">http://www.fda.gov/Safety/Recalls/ucm432417.htm</a><br/></li><br/>
	<li><strong>Morrison Meat Packers is recalling “El Toro Cooked Pork and Water Product” and “Vida Latina Cooked Pork and Water Product”, of various weights, due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release</a></li><br/>
</ul>
<hr>
<h2>Food Alert Archives for Previous Months</h2>
<ul>
	<li><a title="Food Alerts - January 2015" href="/foods/alerts/archives/january2015.aspx">January 2015 - Alerts and Recalls</a></li>
	<li><a title="Food Alerts December 2014" href="/foods/alerts/archives/december2014.aspx">December 2014 - Alerts and Recalls</a></li>
	<li><a title="Food Alerts November 2014" href="/foods/alerts/archives/november2014.aspx">November 2014 - Alerts and Recalls</a></li>
</ul>
<hr>
<h2>Links for Information on National Food Recall:</h2>
<ul>
	<li><a title="http://www.fda.gov/Safety/Recalls/default.htm" href="http://www.fda.gov/Safety/Recalls/default.htm">FDA Recall site (non-meat items)</a></li>
	<li><a title="http://www.fsis.usda.gov/Fsis_recalls/" href="http://www.fsis.usda.gov/Fsis_recalls/">USDA Recall site (meats and foods containing meat)</a></li>
	<li><a title="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg" href="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg">Basic recall information for consumers</a></li>
	<li><a title="http://www.foodsafety.gov/keep/recalls/" href="http://www.foodsafety.gov/keep/recalls/">Many links to other agencies (also e-mail updates available)</a></li>
</ul>


<?php include '/home/codio/workspace/includes/footer.html' ?>	