<?php
	$title= "Food Alerts and Recalls Affecting Texas - Food Manufacturers, Wholesalers, and Warehouses" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/foods_menu.html'; 
?>

<h2>Email Updates</h2>
<p>Sign up to receive email updates about important changes regarding food alerts and recalls. This feature will serve as a tool to increase communication with license holders regarding new information added to the website.</p>
<p><a title="sign up for email updates" href="https://public.govdelivery.com/accounts/TXHHSC/subscriber/new?topic_id=TXHHSC_228"><img alt="sign up for email updates" src="https://www.dshs.state.tx.us/uploadedImages/Common/button-govdelsq.gif"/></a><br/><br/></p>

<hr/>
<p><strong>Sources for recall information:</strong></p>
<ul>
	<li><a title="USDA Current Recalls and Alerts" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/current-recalls-and-alerts">USDA Current Recalls and Alerts</a></li>
	<li><a title="FDA Recalls, Market Withdrawals, &amp; Safety Alerts" href="http://www.fda.gov/Safety/Recalls/default.htm">FDA Recalls, Market Withdrawals, &amp; Safety Alerts</a></li>
	<li><a title="FDA Enforcement Reports" href="http://www.fda.gov/Safety/Recalls/EnforcementReports/default.htm">FDA Enforcement Reports</a></li>
</ul>
<hr/>
<h2>June 3, 2015</h2>
<ul>
	<li><strong>Conway Import Co. is recalling Citrus Organic Vinaigrette Dressing and Organic Sesame Ginger Dressing, both packaged in a plastic gallon jar with a white twist cap, due to possible Salmonella contamination.</strong><br/>Please see the FDA Enforcement Report, Week of June 3, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=06032015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=06032015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=06032015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Santa Barbara Smokehouse is recalling all Smoked Salmon (excluding Hot Smoked Salmon) distributed under the following brands: Cambridge House, Coastal Harbor, Harbor Point, North Shore S.F. Specialty, Channel Islands and Santa Barbara, due to possible Listeria monocytogenes contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm449915.htm" href="http://www.fda.gov/Safety/Recalls/ucm449915.htm">http://www.fda.gov/Safety/Recalls/ucm449915.htm</a><br/><br/></li>
	<li><strong>Dr. Praeger’s Sensible Foods is recalling Gluten Free California Veggie Burger, due to undeclared allergens. </strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm449691.htm" href="http://www.fda.gov/Safety/Recalls/ucm449691.htm">http://www.fda.gov/Safety/Recalls/ucm449691.htm</a><br/><br/></li>
	<li><strong>SmartLipo365 is recalling Smart Lipo (800, 900, 950 mg) capsules, due to unapproved ingredients.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm449741.htm" href="http://www.fda.gov/Safety/Recalls/ucm449741.htm">http://www.fda.gov/Safety/Recalls/ucm449741.htm</a><br/><br/></li>
	<li><strong>Quincy Street, Inc. is recalling several pork sausage products, sold in various packages and sizes, due to possible foreign material contamination. </strong><br/>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-087-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-087-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-087-2015-release</a><br/><br/></li>
	<li><strong>Demes Gourmet Corp. is recalling Pamana Sweet Chicken Longanisa, packaged in 18 lb. cases of 12 oz. tray packs, due to misbranding.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-086-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-086-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-086-2015-release</a><br/><br/></li>
	<li><strong>Total Packaging of KY, Inc., is recalling Anytime Foods Turkey &amp; Cheese Lunch Kit, packaged in 4 compartment plastic tray packages, due to misbranding and an undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-084-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-084-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-084-2015-release</a><br/><br/></li>
</ul>
<hr/>
<h2>May 29, 2015</h2>
<ul>
	<li><strong>Top Taste, Inc. is recalling Fetting's Jumbo Cinnamon Roll Dough, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2283-2015&amp;amp;w=05272015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2283-2015&amp;w=05272015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2283-2015&amp;w=05272015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Texas Pecan Co. is recalling several products containing Macadamia Nuts, due to possible Salmonella contamination. <br/></strong>Please see the FDA Enforcement Report, Week of May 27, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05272015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05272015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05272015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Taylor Fresh Foods Inc. is recalling Spinach, packaged in 4 lb. bags, 2.5 lb. bags, and 1 lb. bags, due to possible Salmonella contamination.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2313-2015&amp;amp;w=05272015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2313-2015&amp;w=05272015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2313-2015&amp;w=05272015&amp;lang=eng</a><br/><br/></li>
	<li><strong>The Popcorn Factory is recalling Lite Works Dill Pickle Popcorn (4 oz.), packaged in foil bags, due to undeclared ingredients.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm448559.htm" href="http://www.fda.gov/Safety/Recalls/ucm448559.htm">http://www.fda.gov/Safety/Recalls/ucm448559.htm</a><br/><br/></li>
	<li><strong>Vitamin Cottage Natural Food Markets Inc. Raw Macadamia Nuts (10 oz.), due to possible Salmonella contamination.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm448353.htm" href="http://www.fda.gov/Safety/Recalls/ucm448353.htm">http://www.fda.gov/Safety/Recalls/ucm448353.htm</a><br/><br/></li>
	<li><strong>Falcon Trading Company, Inc./SunRidge Farms is recalling Sunridge Candy-Vanilla Coconut Chews, due to possible foreign object contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm447917.htm" href="http://www.fda.gov/Safety/Recalls/ucm447917.htm">http://www.fda.gov/Safety/Recalls/ucm447917.htm</a><br/><br/></li>
	<li><strong>Falcon Trading Company, Inc./SunRidge Farms is recalling Coconut-Medium Shred, due to possible foreign object contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm447916.htm" href="http://www.fda.gov/Safety/Recalls/ucm447916.htm">http://www.fda.gov/Safety/Recalls/ucm447916.htm</a><br/><br/></li>
	<li><strong>Culinary Brands Inc. is recalling Simply Balanced Pork Chile Verde (9 oz.), packaged in plastic trays, due to mislabeling and undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-083-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-083-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-083-2015-release</a><br/><br/></li>
</ul>
<hr/>
<h2>May 21, 2015</h2>
<ul>
	<li><strong>World Wide Gourmet Foods, Inc. dba Alaska Smokehouse is recalling Central Market Teriyaki Salmon Jerky (3 oz.), due to mislabeling and undeclared allergens.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2256-2015&w=05202015&lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2256-2015&w=05202015&lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2256-2015&w=05202015&lang=eng</a>	<br/><br/></li>
	<li><strong>Texas Star Nut and Food Co., Inc. is recalling Nature's Eats Natural Macadamia Nuts net wt. 6 oz. (170g), and Central Market Macadamia Nuts net wt. 6 oz. (170g), both packaged in clear cello bags, due to possible Salmonella contamination.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2284-2015&w=05202015&lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2284-2015&w=05202015&lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2284-2015&w=05202015&lang=eng</a>	<br/><br/></li>
	<li><strong>Natural Foodworks Group is recalling Purely Elizabeth Cranberry Cashew Ancient Grain Muesli 10 oz., due to undeclared ingredients. </strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2257-2015&w=05202015&lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2257-2015&w=05202015&lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2257-2015&w=05202015&lang=eng</a>	<br/><br/></li>
	<li><strong>Magic Valley Fresh Frozen, Inc. is recalling several Chopped Spinach products, sold under different brands and packaged in a variety of sizes, due to presence of unapproved pesticide.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2287-2015&w=05202015&lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2287-2015&w=05202015&lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2287-2015&w=05202015&lang=eng</a>	<br/><br/></li>
	<li><strong>Greenies LLC d.b.a. Terra Spice Company is recalling several Dry Spice Mixes, sold in various sizes, due to undeclared allergens.</strong><br/>		Please see the FDA Enforcement Report, Week of May 20, 2015 for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food</a>	<br/><br/></li>
	<li><strong>Gourmet Kitchen, Inc. is recalling several prepared food products packaged on plastic trays, shrink wrapped and placed in boxes, due to undeclared allergens.</strong><br/>		Please see the FDA Enforcement Report, Week of May 20, 2015 for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food</a>	<br/><br/></li>
	<li><strong>Aurora Products, Inc. is recalling several Walnut and Mixed Nut products, sold under different brands and in various packaging, due to possible Salmonella contamination.</strong><br/>		Please see the FDA Enforcement Report, Week of May 20, 2015 for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food</a>	<br/><br/></li>
	<li><strong>Trader Joes Company is recalling Trader Joe's Nuts Raw California Walnut Pieces net wt. 16oz. (1 lb.), Trader Joe's Nuts Raw California Walnut Halves & Pieces net wt. 16oz. (1 lb.), Trader Joe's Nuts Raw California Walnut Baking net wt. 16oz. (1 lb.), Trader Joe's Nuts Raw California Premium Walnut Halves net wt. 16oz. (1 lb.), and Trader Joe's Organic Raw Walnut Halves & Pieces net wt. 16oz. (1 lb.), due to possible Salmonella contamination.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2186-2015&w=05202015&lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2186-2015&w=05202015&lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2186-2015&w=05202015&lang=eng</a>	<br/><br/></li>
	<li><strong>Aleia’s Gluten Free Foods LLC is recalling Aleia's Parmesan Croutons Gluten Free net wt. 8 oz. (226.8g), and Aleia's Classic Croutons Gluten Free net wt. 8 oz. (226.8g), due to undeclared allergens.</strong><br/>		Please see the FDA Enforcement Report, Week of May 20, 2015 for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&w=05202015&lang=eng#food</a>	<br/><br/></li>
	<li><strong>The Santa Barbara Smokehouse, Inc. is recalling Cambridge House Balmoral Thinly Sliced Exceptional Ready to Enjoy Smoked Salmon, and The Santa Barbara Smokehouse Smoked Atlantic Salmon, both packaged in reduced oxygen packaging (ROP) with varying weights, due to possible Listeria monocytogenes contamination.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2270-2015&w=05202015&lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2270-2015&w=05202015&lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&recall_number=F-2270-2015&w=05202015&lang=eng</a>	<br/><br/></li>
	<li><strong>Natural Creations is recalling Natural Creations New Zealand Colostrum, packaged in a white plastic container containing 120 capsules, due to undeclared allergens.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.fda.gov/Safety/Recalls/ucm447054.htm" href="http://www.fda.gov/Safety/Recalls/ucm447054.htm">http://www.fda.gov/Safety/Recalls/ucm447054.htm</a>	<br/><br/></li>
	<li><strong>LQNN, Inc. is recalling several Pate Chaud products, Steamed Bun products, Sliced Deli Meat products, and Beef Jerky products, due to misbranding and being reproduced without the benefit of inspection.</strong><br/>		Please see the following website for more details:<br/>		<a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-081-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-081-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-081-2015-release</a>	<br/><br/></li>
</ul>
<hr/>
<h2>May 15, 2015</h2>
<ul>
	<li><strong>Whole Food Market is recalling Whole Foods Market Health Starts Here Rye Bread (formerly 100% Rye) 16 oz., due to undeclared allergens</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2193-2015&amp;amp;w=05132015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2193-2015&amp;w=05132015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2193-2015&amp;w=05132015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Sazon, Inc. is recalling Sazon Coriander &amp; Annatto, Sazon with Saffron, Sazon without Annatto, Sazon Coriander &amp; Annatto Low Sodium, and Sazon Bohio with Coriander and Annatto, due to undeclared allergens</strong><br/>Please see the FDA Enforcement Report, Week of May 13, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05132015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05132015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05132015&amp;lang=eng#food</a><br/><br/></li>
<li><strong>Prolaiat is recalling Trader Joe’s A Dozen Sweet Bites Chocolate and Coffee Opera Cake, Raspberry Macaroon Cake, Caramel &amp; Chocolate Cake (9.16 oz.), due to undeclared ingredients</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2143-2015&amp;amp;w=05132015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2143-2015&amp;w=05132015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2143-2015&amp;w=05132015&amp;lang=eng</a><br/><br/></li>
<li><strong>Mead Johnson Nutrition is recalling Pregestimil ready to use 20 calorie, sold in 2 oz., bottles; 6 bottles per carton, due to mislabeling</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2170-2015&amp;amp;w=05132015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2170-2015&amp;w=05132015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2170-2015&amp;w=05132015&amp;lang=eng</a><br/><br/></li>
<li><strong>Cott Beverages Inc. is recalling several soft drinks and energy drinks, sold under different brand names, due to undeclared allergens</strong><br/>Please see the FDA Enforcement Report, Week of May 13, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05132015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05132015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05132015&amp;lang=eng#food</a><br/><br/></li>
<li><strong>Spiceco, Inc. is recalling several seasonings containing Sweet Hungarian Paprika, due to undeclared allergens</strong><br/>Please see the FDA Enforcement Report, Week of May 13, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05132015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05132015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05132015&amp;lang=eng#food</a><br/><br/></li>
</ul>
<hr/>
<h2>May 11, 2015</h2>
<ul>
<li><strong>Sabra Dipping Company, LLC is recalling several Hummus products, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of May 6, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Hope Foods LLC, dba Hope Hummus, is recalling Organic Hummus Hope Kale Pesto Spread Good Things, Net Wt. 8 oz. (227g), due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2076-2015&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2076-2015&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2076-2015&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Navajo Agricultural Products Industry, dba Flour Milling, is recalling Navajo Pride Bleached All Purpose Flour in 50 lb., 25 lb., and 5 lb. cloth bags, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2090-2015&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2090-2015&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2090-2015&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Red River Foods Inc. is recalling Style 2 South Africa Macadamia Nuts, due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2141-2015&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2141-2015&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2141-2015&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>A2Z Industries LLC is recalling Vital Labs Halo-V Dietary Supplement, 80 Capsules, due to product containing anabolic steroid.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-2041-2015&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2041-2015&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-2041-2015&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Cuisine Innovations LLC, dba Bon Appetizers LLC, is recalling Guiltless Gourmet Southwestern Veggie Burger (2.5oz.) 48 pieces, Southwestern Veggie Burger 4 (oz.) 36 count, Chef's Line Black Bean Burger (4.25 oz.) 36 count, and Black Bean Burger (4.5 oz.) 40 pieces, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of May 6, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Inventure Foods is recalling Rader Farms Fresh Start Smoothie Blend (48 oz.), Rader Farms Fresh Start Sunrise Refresh Fusion (35 oz.), and Rader Farms Fresh Start Daily Power Fusion (35 oz.), due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of May 6, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Con Yeager Spice Co. is recalling Cumin and several cumin containing Spice Mixes, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of May 6, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=05062015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=05062015&amp;lang=eng</a><br/><br/></li>
<li><strong>Poco Dolce Confections is recalling Almond, Aztec Chile, Burnt Caramel, Almond Coconut, Ginger, and Sesame Toffee individually wrapped Tiles, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm445558.htm" href="http://www.fda.gov/Safety/Recalls/ucm445558.htm">http://www.fda.gov/Safety/Recalls/ucm445558.htm</a><br/><br/></li>
<li><strong>Ohanyan’s Bastirma &amp; Soujouk Co. is recalling Soujouk Dried Beef Sausage Hot &amp; Spicy (1 lb.), and Soujouk Dried Beef Sausage Mild (1 lb.), due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-072-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-072-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-072-2015-release</a><br/><br/></li>
</ul>


<hr/>
<h2>Food Alert Archives for Previous Months</h2>
<ul>
<li><a title="Archived Food Alerts" href="/foods/alerts/archives/">Archived Food Alerts</a></li>
</ul>

<hr/>
<h2>Links for Information on National Food Recall:</h2>
<ul>
<li><a title="http://www.fda.gov/Safety/Recalls/default.htm" href="http://www.fda.gov/Safety/Recalls/default.htm">FDA Recall site (non-meat items)</a></li>
<li><a title="http://www.fsis.usda.gov/Fsis_recalls/" href="http://www.fsis.usda.gov/Fsis_recalls/">USDA Recall site (meats and foods containing meat)</a></li>
<li><a title="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg" href="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg">Basic recall information for consumers</a></li>
</ul>


<?php include '/home/codio/workspace/includes/footer.html' ?>	