<?php
	$title= "Food Alerts and Recalls Affecting Texas - Food Manufacturers and Wholesalers" ;
	include '/home/codio/workspace/includes/header.html';
    include '/home/codio/workspace/includes/menus/foods_menu.html'; 
?>

<h2>Email Updates</h2>
<p>Sign up to receive email updates about important changes regarding food alerts and recalls. This feature will serve as a tool to increase communication with license holders regarding new information added to the website.</p>
<p><a title="sign up for email updates" href="https://public.govdelivery.com/accounts/TXHHSC/subscriber/new?topic_id=TXHHSC_XXXXXXX"><img alt="sign up for email updates" src="https://www.dshs.state.tx.us/uploadedImages/Common/button-govdelsq.gif"/></a><br/><br/></p>

<hr/>
<p><strong>Sources for recall information:</strong></p>
<ul>
	<li><a title="USDA Current Recalls and Alerts" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/current-recalls-and-alerts">USDA Current Recalls and Alerts</a></li>
	<li><a title="FDA Recalls, Market Withdrawals, &amp; Safety Alerts" href="http://www.fda.gov/Safety/Recalls/default.htm">FDA Recalls, Market Withdrawals, &amp; Safety Alerts</a></li>
	<li><a title="FDA Enforcement Reports" href="http://www.fda.gov/Safety/Recalls/EnforcementReports/default.htm">FDA Enforcement Reports</a></li>
</ul>

<hr/>
<h2>April 15, 2015</h2>
<ul>
	<li><strong>Interbake Foods LLC is recalling Mrs. Fields White Chunk Macadamia Cookies 2.1 oz., due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1870-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1870-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1870-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Cheryl’s is recalling Cheryl's Buttercream Frosted Cut-Out Bunny Head Cookies Net Wt. 1.5oz (43g), due to mislabeling.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1805-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1805-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1805-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Maternal Science Inc. is recalling Healthy Mama Boost it Up Mango with Ginger Caffeine Free Protein with Energy Drink 12 fl. oz., Healthy Mama Boost it Up Pom Cherry Caffeine Free Protein with Energy Drink 12 fl. oz., and Healthy Mama Boost It Up Mighty Mango Caffeine Free Protein with Energy Drink 12 fl. oz., due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>White Wave Foods, Inc. is recalling Organic Horizon Sandwich Crackers Cheddar 7.5 oz., due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1869-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1869-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1869-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>ProSupps USA LLC is recalling Mr. Hyde Intense Energy Pre Workout 8.0 oz. (228 grams), due to containing more yohimbine hcl than declared on the label.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1783-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1783-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1783-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Michael Foods, Inc. is recalling Natural Shaped Fried Egg (patties) 1.75 oz., sold under brand names Pappetti's Table Ready and Glenview Farms, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1875-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1875-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1875-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>See's Candies Inc. is recalling See's Candies Classic Red Heart with Assorted Chocolates (8 oz., 227 g), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1788-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1788-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1788-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Creative Foodworks, Inc. is recalling several different salsas, sold under several different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>American Spice &amp; Seasoning, Inc. is recalling Adkins Barbecue Spice (Net Wt. 25 lbs.).<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1794-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1794-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1794-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Brinkhoff &amp; Monoson Inc. is recalling Dark Chili Powder, Archer Farms Cumin, and HT Traders Blue Cheese Jalapeno Spicy &amp; Unique Seasoning, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Gilster-Mary Lee Corp. is recalling Market Pantry Honey &amp; Oat Mixers ready-to-eat dry cereal 18 oz. (510 g), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1806-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1806-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1806-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Zenobia Company LLC is recalling My Spice Sage Ground Cumin, packaged in 1 oz., 4 oz., 4.9 oz., 16 oz., and 50 lb. sizes, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1803-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1803-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1803-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Bidart Bros. is recalling Granny Smith Apples, "Granny's Best" or "Big B, and Gala Apples "Big B"; all sold in 40-45 lb. cases, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of April 8, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04082015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04082015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Tai Foong U.S.A., Inc is recalling Northern Chef Lightly Coated Cod Fingers 10 oz. (284 g), due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1807-2015&amp;amp;w=04082015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1807-2015&amp;w=04082015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1807-2015&amp;w=04082015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Beech-Nut Nutrition is recalling Stage 2 Beech-Nut Classics Sweet Potato &amp; Chicken, packaged in 4 oz. glass jars, due to possible contamination with broken glass.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-061-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-061-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-061-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>April 13, 2015</h2>
<ul>
	<li><strong>Texas Pecan Company Inc. is recalling several nut products and gift tins, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm442042.htm" href="http://www.fda.gov/Safety/Recalls/ucm442042.htm">http://www.fda.gov/Safety/Recalls/ucm442042.htm</a><br/><br/></li>
	<li><strong>Sabra Dipping Co., LLC is recalling Sabra Classic Hummus 10 oz., Sabra Classic Hummus 30 oz., Sabra Classic Hummus without Garnish 32oz., Sabra Classic Hummus 17oz Six Pack, and Hummus Dual Pack Classic/Garlic 23.5oz, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441863.htm" href="http://www.fda.gov/Safety/Recalls/ucm441863.htm">http://www.fda.gov/Safety/Recalls/ucm441863.htm</a><br/><br/></li>
	<li><strong>World Wide Gourmet Foods is recalling Central Market Teriyaki Salmon Jerky, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441838.htm" href="http://www.fda.gov/Safety/Recalls/ucm441838.htm">http://www.fda.gov/Safety/Recalls/ucm441838.htm</a><br/><br/></li>
	<li><strong>Blue Bell Creameries is recalling several ice cream and sherbet products sold in pint, quart, and half gallon sizes, due to possible Listeria monocytogenes contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441620.htm" href="http://www.fda.gov/Safety/Recalls/ucm441620.htm">http://www.fda.gov/Safety/Recalls/ucm441620.htm</a><br/><br/></li>
	<li><strong>Texas Star Nut and Food Co., Inc. is recalling Nature's Eats Mustang Island Macadamia Sunrise 14 oz., Nature's Eats Natural Macadamia Nuts 6 oz., and Central Market Natural Macadamia Nuts 6 oz., due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm441686.htm" href="http://www.fda.gov/Safety/Recalls/ucm441686.htm">http://www.fda.gov/Safety/Recalls/ucm441686.htm</a><br/><br/></li>
</ul>

<hr/>
<h2>April 7, 2015</h2>
<ul>
	<li><strong>Agridient, Inc. is recalling Agridient Vital Wheat Gluten, packaged in a 50 lb. paper sack, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1618-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1618-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1618-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>El Popocatepetl Ind., Inc. is recalling Sundried Tomato flavored Tortilla Wraps 8 in., Spinach Pesto flavored Tortilla Wraps 8 in., and Chipotle flavored Tortilla Wraps 8 in., due to undeclared allergens and undeclared Yellow No. 5.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Mars Food US is recalling several varieties of Uncle Ben’s Ready Rice, due to possible metal fragment contamination.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder, packaged in Zip-Lock-type plastic bags, due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1580-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1580-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1580-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Unilever United States, Inc. is recalling Breyers No Sugar Added Salted Caramel Swirl 1.5-quart (1.41L), packaged in paperboard tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1584-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1584-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1584-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Whole Foods Market is recalling Chocolate Cake for Two packaged in clear plastic containers, due to undeclared allergens. <br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1585-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1585-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1585-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Sunfood Corporation is recalling Organic Sacha Inchi Powder, 8oz., due to possible Staphylococcus contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1586-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1586-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1586-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Hines Nut Co. is recalling Walnuts Halves &amp; Pieces net wt. 16 oz., due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1601-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1601-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1601-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Aloha is recalling Aloha Vanilla Premium Protein Powder and Aloha Chocolate Premium Protein Powder, sold under several different labels, due to possible Staphylococcus contamination.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Reo Spice &amp; Seasoning, Inc. is recalling several Seasonings, Spices, and Chili Blends, sold under Reo Bear, Vitek’s, Reo Ranch, Jmad’s, and Bon Ton brand names, due to undeclared allergens.</strong><br/>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>The Hain Celestial Group is recalling Taj Ethnic Bombay Curry Simmer Sauce 16 oz., Taj Ethnic Gourmet Calcutta Masala Simmer Sauce 16 oz., and Taj Ethnic Gourmet Punjab Saag Spinach Sauce 16 oz., due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Dursett Amigos, Ltd. is recalling Taco Kits, Taco Sauces, and Salsas, sold under Laura Lynn, Parade, HyVee, Brookshire, Roundy’s, and Rico’s brands, and HEB Bean &amp; Cheese Dip, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of April 1, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=04012015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=04012015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>FGF Brands is recalling US Foods brand Mini Naan, eight naan packaged in coated paper printed board and transparent wrap, net wt. 12.6 oz (360 g), due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1617-2015&amp;amp;w=04012015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1617-2015&amp;w=04012015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1617-2015&amp;w=04012015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Hope Foods is recalling Kale Pesto Hummus, packaged in 8 oz. plastic tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm440887.htm" href="http://www.fda.gov/Safety/Recalls/ucm440887.htm">http://www.fda.gov/Safety/Recalls/ucm440887.htm</a><br/><br/></li>
	<li><strong>Whole Foods Market is recalling Bran Muffin six packs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm440729.htm" href="http://www.fda.gov/Safety/Recalls/ucm440729.htm">http://www.fda.gov/Safety/Recalls/ucm440729.htm</a><br/><br/></li>
	<li><strong>Lebanese Butcher Slaughter, Inc. is recalling Beef Cuts in unlabeled plastic bags, and Lamb or Goat Cuts in unlabeled plastic bags, due to misbranding and processing without the benefit of full inspection.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-055-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-055-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-055-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 25, 2015</h2>
<ul>
	<li><strong>Benson's Old Home Kitchens Bakery Division is recalling The Bakery Baked with Pride - Sock It to Me Crème Cake, Net Wt. 32oz (2lb) 907g, packed in a rigid clear plastic dome, sold in Walmart, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1416-2015&amp;amp;w=03252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1416-2015&amp;w=03252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1416-2015&amp;w=03252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Goya Foods, Inc. is recalling Kirby Black Beans Creole Seasoning (29 oz.) and Goya Black Bean Soup (29 oz.), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Twin City Bagel, Inc. is recalling several bagel products sold under different brand names, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Korean Food Co. is recalling Go Hyang Mak Kimchi, packaged in 32 oz. and half gallon cases, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1429-2015&amp;amp;w=03252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1429-2015&amp;w=03252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1429-2015&amp;w=03252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Chris A. Papas &amp; Son Co. is recalling several flavors of Marshmallow Eggs and Cream Eggs, due to undeclared Yellow #5.</strong><br/>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Aron Streit Inc. is recalling Streit’s Kids Dark Chocolate Coins, packaged in 24 ct. 15 g. mesh bags, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1428-2015&amp;amp;w=03252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1428-2015&amp;w=03252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1428-2015&amp;w=03252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Snoqualmie Gourmet Ice Cream is recalling several flavors of Snoqualmie brand ice cream products, packaged in 2.5 gallon clear flexible plastic bags, 3 gallon plastic tubs, 1.5 gallon plastic tubs, 1 gallon plastic trays, and 16 oz. paper cartons, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Superior Foods, Inc. is recalling Simply Balanced Organic Chopped Spinach (10 oz.) steam-in bag, sold in Target stores, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439761.htm" href="http://www.fda.gov/Safety/Recalls/ucm439761.htm">http://www.fda.gov/Safety/Recalls/ucm439761.htm</a><br/><br/></li>
	<li><strong>La Terra Fina is recalling Spinach Artichoke &amp; Parmesan Dip made with Greek Yogurt (31oz. tub) and Chunky Spinach Artichoke &amp; Parmesan Dip (31oz. tub), due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439940.htm" href="http://www.fda.gov/Safety/Recalls/ucm439940.htm">http://www.fda.gov/Safety/Recalls/ucm439940.htm</a><br/><br/></li>
	<li><strong>Carmel Food Group is recalling Rising Moon Organics Garlic &amp; Veggie Ravioli (6/8 oz.), Rising Moon Organics Spinach Florentine Ravioli (6/8 oz.), and Rising Moon Organics Spinach &amp; Cheese Ravioli (6/8 oz.), due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439539.htm" href="http://www.fda.gov/Safety/Recalls/ucm439539.htm">http://www.fda.gov/Safety/Recalls/ucm439539.htm</a><br/><br/></li>
	<li><strong>Blue Bell Ice Cream is recalling 3 oz. institutional/food service ice cream cups in chocolate, strawberry and vanilla flavors with tab lids, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439533.htm" href="http://www.fda.gov/Safety/Recalls/ucm439533.htm">http://www.fda.gov/Safety/Recalls/ucm439533.htm</a><br/><br/></li>
	<li><strong>Amy’s Kitchen, Inc. is recalling several different prepared pastas and entrees due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439397.htm" href="http://www.fda.gov/Safety/Recalls/ucm439397.htm">http://www.fda.gov/Safety/Recalls/ucm439397.htm</a><br/><br/></li>
	<li><strong>Texas Star Nut and Food Co. Inc.is recalling Nature’s Eats Natural Macadamia Nuts, due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439283.htm" href="http://www.fda.gov/Safety/Recalls/ucm439283.htm">http://www.fda.gov/Safety/Recalls/ucm439283.htm</a><br/><br/></li>
	<li><strong>Nutiva is recalling O'Coconut Classic and O'Coconut Hemp &amp; Chia due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm439285.htm" href="http://www.fda.gov/Safety/Recalls/ucm439285.htm">http://www.fda.gov/Safety/Recalls/ucm439285.htm</a><br/><br/></li>
	<li><strong>Aurora Products, Inc. is recalling Natural Walnuts, Mixed Nuts, and Trail Mixes containing walnuts, in various packaging and sizes, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm440314.htm" href="http://www.fda.gov/Safety/Recalls/ucm440314.htm">http://www.fda.gov/Safety/Recalls/ucm440314.htm</a><br/><br/></li>
	<li><strong>StoneRidge Wholesale Division, LLC is recalling StoneRidge Roasted Garlic Pork Tenderloin packaged in 1-2 lb. vacuum sealed packages, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-048-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-048-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-048-2015-release</a><br/><br/></li>
	<li><strong>Viz Cattle is recalling Flap Meat packaged in 30 lb. cardboard boxes, due to misbranding.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-052-2015" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-052-2015">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-052-2015</a><br/><br/></li>
</ul>

<hr/>
<h2>March 19, 2015</h2>
<ul>
	<li><strong>Soyko International, Inc. is recalling Byglands Non-GMO Soybeans for Sprouting, in 25KG bags and 1MT tote bags, due to possible Listeria monocytogenes contamination.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1413-2015&amp;w=03182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1413-2015&amp;w=03182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Korean Food Co. is recalling Soybean Sprouts, packaged in 1 lb. and 2 lb. bags, due to possible Listeria monocytogenes contamination.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1406-2015&amp;w=03182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1406-2015&amp;w=03182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Julian Bakery, Inc. is recalling Paleo Protein Bar Chocolate Brownie (2.1 oz.), and Paleo Protein Bar Cookies N' Crème (2.1 oz.), due to undeclared allergens.<br /> </strong>Please see the FDA Enforcement Report, Week of March 18, 2015 for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Ungar's Food Products, Inc. is recalling Dr. Praeger's Sensible Foods Bombay Curry Veggie Burgers (11 oz.), due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1405-2015&amp;w=03182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1405-2015&amp;w=03182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>E. Martin &amp; Sons Co., Inc. is recalling Ground Cumin, and Chili Powder, due to undeclared allergens.<br /> </strong>Please see the FDA Enforcement Report, Week of March 18, 2015 for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03182015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Trader Joe’s Company is recalling Raw Walnuts, packaged in clear plastic bags in 16 oz. and 12 oz. sizes, due to possible Salmonella contamination</strong>.<br /> Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438472.htm">http://www.fda.gov/Safety/Recalls/ucm438472.htm</a><br/><br/></li>
	<li><strong>Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder, packaged in clear plastic bags in size ranges of 0.25 pound to 0.30 pound, due to possible Salmonella contamination. <br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438857.htm">http://www.fda.gov/Safety/Recalls/ucm438857.htm</a><br/><br/></li>
	<li><strong>Kraft Foods Group is recalling Original flavor of Kraft Macaroni &amp; Cheese Dinner packaged in , 7.25 oz. box,3-pack box 7.25 oz. boxes, 4-pack shrink-wrap of 7.25 oz. boxes, and 5-pack shrink-wrap of 7.25 oz. boxes, due to the possibility that some boxes may contain small pieces of metal.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438700.htm">http://www.fda.gov/Safety/Recalls/ucm438700.htm</a><br/><br/></li>
	<li><strong>Frontier Co-op is recalling several of its products manufactured with organic garlic powder that were sold under its Frontier, Simply Organic brands, and Whole Foods Market brand, due to possible Salmonella contamination.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438360.htm">http://www.fda.gov/Safety/Recalls/ucm438360.htm</a><br/><br/></li>
	<li><strong>Product Removal/Foodborne Illness Outbreak Investigation Advisory: Five patients who were treated in a single hospital in Kansas were infected with one of four rare strains of Listeria monocytogenes. Three of these strains were found in samples of Blue Bell Creameries single serving Chocolate Chip Country Cookie Sandwich, the Great Divide Bar ice cream products, and single-serving ice cream product Scoops. Several Blue Bell Creameries products have been removed from the market.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438626.htm">http://www.fda.gov/Safety/Recalls/ucm438626.htm</a><br/><br/></li>
	<li><strong>Bear Creek Smokehouse is recalling Beasley’s Smokehouse Chopped Barbeque Beef with Sauce (1 lb.), and Bear Creek Smokehouse Chopped Beef Brisket (1 lb. and 5 lb.), due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-046-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-046-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 16, 2015</h2>
<ul>
	<li><strong>MegaMex Foods, LLC is recalling Herdez Chilpotle Peppers, 7oz., due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1379-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1379-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>H-E-B Corpus Christi Operations is recalling H-E-B Homestyle White Corn Tortillas 12ct. and 30 ct., due to corn stalk fragments in tortillas.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1378-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1378-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Morris J. Golombeck, Inc. is recalling Ground Cumin Seed (50 lbs. net wt.), due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1377-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1377-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Jardine Foods Inc. is recalling several seasonings, sauces, and chili kits, sold under brand names “Jardines’s”, “D.L. Jardine’s”, and “Shotgun Willie’s, due to  undeclared allergens.<br /> </strong>Please see the FDA Enforcement Report, Week of March 11, 2015 for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03112015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Hi-Tech Pharmacal Co., Inc. is recalling Ferrous Sulfate Elixir (220 mg/5ml), due to out-of-specification result for pH observed during stability testing.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1380-2015&amp;w=03112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1380-2015&amp;w=03112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Badia Spices, Inc. is recalling Badia Ground Cumin in 2 oz., 7 oz. and 16 oz. packages, due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438042.htm">http://www.fda.gov/Safety/Recalls/ucm438042.htm</a><br/><br/></li>
	<li><strong>Trader Joe’s Company is recalling Trader Joe’s Cinnamon Almonds, packaged 16 oz. clear packages, due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm438079.htm">http://www.fda.gov/Safety/Recalls/ucm438079.htm</a><br/><br/></li>
	<li><strong>UltraZx, Labs, L.L.C is recalling UltraZx weight loss supplements due to undeclared ingredients.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fda.gov/Safety/Recalls/ucm437517.htm">http://www.fda.gov/Safety/Recalls/ucm437517.htm</a><br/><br/></li>
	<li><strong>Gourmet Kitchen, Inc. is recalling several beef products, sold under brand names “Gourmet Kitchen”, “Gourmet Foods”, MacKenzie Limited”, and “Impromtu Petitie”, due to  undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-045-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-045-2015-release</a><br/><br/></li>
	<li><strong>Bon Appetizers, LLC is recalling Cuisine Innovations Chicken Empanada, Cuisine Innovations Chicken Quesadilla Cornucopia (Chicken and Cheese Filling in Flour Tortilla), Ridgecrest Chicken Quesadilla Cornucopia (Chicken and Cheese Filling in Flour Tortilla),and Culinary Secrets Quesadilla Cornucopia, all packaged in various weight bulk packages, due to undeclared allergens.<br /> </strong>Please see the following website for more details:<br /> <a href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-042-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-042-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 9, 2015</h2>
<ul>
	<li><strong>Washington Harvest Wapato is recalling The World's Finest Mixed Fruit containing Red Delicious Apples, Granny Smith Apples and Navel Oranges, packed in poly bags 6/4 lb. bags per case, and Fast &amp; Fresh Grab Mixed Apples And/or Oranges containing Fuji Apples, Granny Smith Apples and Oranges, packed in poly bags 10/4 lb. bags per case or 8/5lb. mesh bags per case, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Kabobs Inc. is recalling Frozen Shrimp Empanada 100 count, Frozen Vegetable Empanada 100 count, and Frozen Yucatan Style Roasted Corn &amp; Black Bean Tart, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Gulf Coast Blenders, Inc. is recalling several spices and seasonings sold under different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Schwan Food Company is recalling Holiday Foods Hors D'Oeuvre Vegetable Samosa Triangle, 60 1.5 oz., and Holiday Foods Hors D'Oeuvre Vegetable Samosa Potsticker, 100 0.7 oz pieces , both for institutional use only, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Harvest Food Group, Inc. is recalling Tommy's Superfoods&nbsp; Seasoned Santa Fe Rice packed in 10 oz. (284 g) plastic film bags and Tastee Western Rice packaged in 40 lb. corrugated boxes with blue poly liners, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1302-2015&amp;amp;w=03042015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1302-2015&amp;w=03042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1302-2015&amp;w=03042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Sugar Daddy LTD is recalling Caramel Apples labeled as Merbs Candies, Double Dipped individually wrapped in plastic, and Caramel and Pecan Apple labeled as Merbs Candies, Bionic Apple packaged in plastic wrappers, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Adams Extract &amp; Spice LLC is recalling several spices and seasonings sold under different brands, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of March 4, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=03042015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=03042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Relish Foods Inc. is recalling Pacific Fusion Frozen Tuna Steak Wild Caught net wt. 15 lb. (240 oz.) 6.80 kg, due to elevated levels of histamine.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-0801-2015&amp;amp;w=03042015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0801-2015&amp;w=03042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0801-2015&amp;w=03042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Maternal Science, Inc. is recalling healthy mama® Boost It Up! Mighty Mango with Ginger&nbsp; 12 fl oz. packaged in a bottle and healthy mama® Boost It Up! Mighty Mango 12 fl oz. packaged in a bottle, due to undeclared allergens.</strong><br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm436491.htm" href="http://www.fda.gov/Safety/Recalls/ucm436491.htm">http://www.fda.gov/Safety/Recalls/ucm436491.htm</a><br/><br/></li>
	<li><strong>Rio Tex Wholesale Meats is recalling Hausman Foods Brand Cooked Beef Taco Filling Seasoned Cooked Beef Barbacoa, Fully Cooked Barbacoa, and Beef Carne Guisada packaged in 20-lb. boxes containing four 5-lb. packages, and Rio-Tex-Meats Barbacoa packaged in 15-lb. and 45-lb. boxes containing three 5-lb. or 15-lb. packages, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-041-2015-release</a><br/><br/></li>
	<li><strong>Campos Foods, LLC is recalling H-E-B Fully Cooked Thick N’ Tasty Cheese Burgers Natural Smoke Flavor Added net wt. 15-oz. (425g) bag containing four 3.75-oz. burgers and net wt. 30-oz. (1.87lbs) (850g) bag containing eight 3.75-oz. burgers, and H-E-B Fully Cooked Thick N’ Tasty&nbsp; Bacon Cheese Burgers Natural Smoke Flavor Added net wt. 30-oz. (1.87lbs) (850g) bag containing eight 3.75-oz. burgers, misbranding and undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-038-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>March 2, 2015</h2>
<ul>
	<li><strong>Hamchorom Inc. is recalling Haitai Tayo Crackers (140 g) 24 boxes/carton, in box colors: blue, yellow, and red, and Haitai Gyeran Crackers (70 g) 20 boxes/carton, in yellow box with "Angry Birds" logo, due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 25, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02252015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02252015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Probar LLC is recalling Frosted Peanut Butter BASE Protein Bar, 2.46 oz., film wrapped bar packaged in 12 wrapped units per sleeve/carton, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1224-2015&amp;amp;w=02252015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1224-2015&amp;w=02252015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Talenti® Gelato &amp; Sorbetto is recalling Talenti® Gelato &amp; Sorbetto Sea Salt Caramel Gelato packaged in one pint (473 mL) clear plastic jars, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm436020.htm" href="http://www.fda.gov/Safety/Recalls/ucm436020.htm">http://www.fda.gov/Safety/Recalls/ucm436020.htm</a><br/><br/></li>
	<li><strong>Fairway “Like No Other Market” is recalling Fairway brand Raw Hazelnuts (Filberts), packaged in clear, plastic cello bags of varying weights, each weighing less than one pound, due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435547.htm" href="http://www.fda.gov/Safety/Recalls/ucm435547.htm">http://www.fda.gov/Safety/Recalls/ucm435547.htm</a><br/><br/></li>
	<li><strong>Oscar’s Hickory House Inc. is recalling Oscar’s Adirondack Mountain Smokehouse Beef Jerky in 4 oz. and 8 oz. cryovac packages, due to a processing deviation.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-037-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>February 24, 2015</h2>
<ul>
	<li><strong>Freeland Foods Inc. is recalling Go Raw 100% Organic Sunflower Seeds; Net Wt. 1 lb. (454 g), due to possible Salmonella contamination.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1196-2015&amp;amp;w=02182015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1196-2015&amp;w=02182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1196-2015&amp;w=02182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>HVL, LLC is recalling Melatonin Control- Released Tablets, 60 tablets, in plastic bottles, due to mislabeling.</strong><br/>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-1202-2015&amp;amp;w=02182015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1202-2015&amp;w=02182015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-1202-2015&amp;w=02182015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Kellogg USA Inc. is recalling MorningStar Farms Spicy Black Bean Burger and MorningStar Farms Chipotle Black Bean Burger, due to undeclared allergens.</strong><br/>Please see the FDA Enforcement Report, Week of February 18, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02182015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Full Tilt Ice Cream is recalling several flavors of ice cream packaged in 16 oz. paper containers, and 1.5 gallon and 3 gallon plastic tubs, due to possible Listeria monocytogenes contamination.<br/></strong>Please see the FDA Enforcement Report, Week of February 18, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02182015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02182015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>El Popocatepetl Ind., Inc. is recalling El Popocatepetl’s 8 in. Chipotle, Spinach Pesto, and Sun Dried Tomato Wraps, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435190.htm" href="http://www.fda.gov/Safety/Recalls/ucm435190.htm">http://www.fda.gov/Safety/Recalls/ucm435190.htm</a><br/><br/></li>
	<li><strong>WhiteWave Foods is recalling Horizon Cheddar Sandwich Crackers (7.5 oz.), due to undeclared allergens. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435172.htm" href="http://www.fda.gov/Safety/Recalls/ucm435172.htm">http://www.fda.gov/Safety/Recalls/ucm435172.htm</a><br/><br/></li>
	<li><strong>Con Yeager Spice Company is recalling multiple sized packages under multiple brand names of ground cumin and multiple seasoning blends (containing ground cumin) due to undeclared allergens.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435171.htm" href="http://www.fda.gov/Safety/Recalls/ucm435171.htm">http://www.fda.gov/Safety/Recalls/ucm435171.htm</a><br/><br/></li>
	<li><strong>Old Home Kitchens is recalling Sock It To Me Crème Cake under the “Bakery baked with pride" label, packaged in plastic domes, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm435170.htm" href="http://www.fda.gov/Safety/Recalls/ucm435170.htm">http://www.fda.gov/Safety/Recalls/ucm435170.htm</a><br/><br/></li>
	<li><strong>Goya Foods, Inc. is recalling Kirby Black Beans Creole Seasoning (29 oz.) and Goya Black Bean Soup (29 oz.), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434542.htm" href="http://www.fda.gov/Safety/Recalls/ucm434542.htm">http://www.fda.gov/Safety/Recalls/ucm434542.htm</a><br/><br/></li>
	<li><strong>ESS Food is recalling Pini Polona Pork Belly Boneless (40 lb.) packaged in boxes containing 4-5 pieces, due to not being presented at the U.S. point of entry for inspection.</strong> <br/>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-035-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>February 18, 2015</h2>
<ul>
	<li><strong>High Road Craft Ice Cream, Inc. is recalling High Road Craft Ice Cream &amp; Sorbet, Limoncello Sorbet packed in 4.9L (1.3 gallon) tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;amp;recall_number=F-0967-2015&amp;amp;w=02112015&amp;amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0967-2015&amp;w=02112015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0967-2015&amp;w=02112015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Zilks Foods is recalling several flavors of Zilks brand Hummus (8 oz.), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Gemini Food Corporation Inc. is recalling Description&nbsp; Dried Bean Curd Satay Flavor (150g), Dried Bean Curd Anka Flavor (150g), Dried Bean Curd Chili Flavor (150g), Dried Bean Curd Spicy Flavor (150g), and Dried Bean Curd Garlic Flavor (150g), to due possible dimethyl yellow contamination.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Reily Foods Co. is recalling Carroll Shelby’s Original Texas Brand Chili Kit (4 oz.)( 113 g), Carroll Shelby’s Original Texas Brand White Chicken Chili kit (3 oz.) (85 g), Wick Fowler’s Famous Texas Style 2-Alarm Chilli Kit (3.6525 oz.) (102 g), and Wick Fowler’s Famous Texas Style False Alarm Mild&nbsp; Chilli Kit (3.03 oz.) (86 g), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Riba Foods Inc. is recalling Arriba! Chili Con Queso-Hot (16 oz.), Salpica Salsa Con Queso (11.5 oz. &amp;16 oz.), Salpica Ballpark Nacho (8 oz.), Salpica Black Bean Nacho (8 oz.), Crate &amp; Barrel&nbsp; Monterey Jack Queso Dip (11.5 oz.), and Salpica Jalapeno Jack Queso Dip (16 oz.), due to undeclared allergens.<br/></strong>Please see the FDA Enforcement Report, Week of February 11, 2015 for more details:<br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;amp;w=02112015&amp;amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02112015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Unilever United States, Inc. is recalling Breyers® No Sugar Added Salted Caramel Swirl packaged in 1.5-quart (1.41L) paperboard tubs, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434540.htm" href="http://www.fda.gov/Safety/Recalls/ucm434540.htm">http://www.fda.gov/Safety/Recalls/ucm434540.htm</a><br/><br/></li>
	<li><strong>Whole Foods Market is recalling Chocolate Cake for Two packaged in clear plastic containers, due to undeclared allergens. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434430.htm" href="http://www.fda.gov/Safety/Recalls/ucm434430.htm">http://www.fda.gov/Safety/Recalls/ucm434430.htm</a><br/><br/></li>
	<li><strong>Vitamin Cottage Natural Food Markets, Inc. is recalling Natural Grocers brand Organic Garlic Powder packaged in clear plastic bags (0.25 lb. – 0.30lb.), due to possible Salmonella contamination. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434254.htm" href="http://www.fda.gov/Safety/Recalls/ucm434254.htm">http://www.fda.gov/Safety/Recalls/ucm434254.htm</a><br/><br/></li>
	<li><strong>Michigan Brand, Inc. is recalling Michigan Brand Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and The Jerky Outlet Teriyaki Hunter Sausage in 6 oz. and 14 oz. packages, and 40 count boxes, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-032-2015-release</a><br/><br/></li>
	<li><strong>Ruiz Foods is recalling Egg Sausage and Cheese Wrapped in a Flour Tortilla packaged in 4.5-lb. cases containing 3 trays with 8 pieces, due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-033-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>February 12, 2015</h2>
<ul>
	<li><strong>Sunfood is recalling Organic Sacha Inchi Powder, packaged in&nbsp; 8 oz. white bags, due to possible Staphylococcus enterotoxin contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm434009.htm" href="http://www.fda.gov/Safety/Recalls/ucm434009.htm">http://www.fda.gov/Safety/Recalls/ucm434009.htm</a><br/><br/></li>
	<li><strong>Hines Nut Company is recalling Hines Nut Brand Walnut Halves and Pieces (12 or 16 oz.) due to possible Salmonella contamination.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433797.htm" href="http://www.fda.gov/Safety/Recalls/ucm433797.htm">http://www.fda.gov/Safety/Recalls/ucm433797.htm</a><br/><br/></li>
	<li><strong>Detox Transforms Health and Nutrition is recalling EDGE Amplified Weight Release, iNDiGO, AMPD Gold Bee Pollen, BtRim Max, and iNSANE Bee Pollen, all packaged in white bottles with 60 capsules, due to undeclared drug ingredients.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433513.htm" href="http://www.fda.gov/Safety/Recalls/ucm433513.htm">http://www.fda.gov/Safety/Recalls/ucm433513.htm</a><br/><br/></li>
	<li><strong>Korean Food Co. is recalling Go-Hang Soybean Sprouts in 1 lb. and &nbsp;2 lb. plastic bags, and 10 lb. black plastic bags, due to possible Listeria monocytogenes contamination. <br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433403.htm" href="http://www.fda.gov/Safety/Recalls/ucm433403.htm">http://www.fda.gov/Safety/Recalls/ucm433403.htm</a><br/><br/></li>
	<li><strong>Pepperidge Farm is recalling Cinnamon Raisin Bagels (21 oz. and 17oz.), Plain Mini Bagels (17 oz.), Everything Bagels (21 oz.), Plain Bagels (21 oz.) Brown Sugar/Cinnamon Mini Bagels (17 oz.), and 100% Whole Wheat Mini Bagels (17 oz.), due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433775.htm" href="http://www.fda.gov/Safety/Recalls/ucm433775.htm">http://www.fda.gov/Safety/Recalls/ucm433775.htm</a><br/><br/></li>
	<li><strong>See’s Company is recalling Classic Red Hearts with Assorted Chocolates 8 oz., due to undeclared allergens.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fda.gov/Safety/Recalls/ucm433408.htm" href="http://www.fda.gov/Safety/Recalls/ucm433408.htm">http://www.fda.gov/Safety/Recalls/ucm433408.htm</a><br/><br/></li>
	<li><strong>Sunrise Poultry Processors is recalling Sunrise Poultry Brand Chicken Thighs in 40 lb. bulk cases, Chicken Thighs Boneless in 25 lb. cases, Boneless Chicken Breast in 2.5lb. cases, and Chicken Whole Fryer in 2.5 lb., 4 lb., and 3.25-3.75 lb. cases, due to not being presented at the U.S. point of entry for inspection.<br/></strong>Please see the following website for more details:<br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-029-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>February 6, 2015 </h2>
<ul>
	<li><strong>Eillien's Candies, Inc. is recalling Walnut Pieces in several sizes, under the following brand names: Eillien’s, Blain’s Farm and Fleet, Mill’s Fleet Farm, Piggly Wiggly, Rural King, and Trig’s, due to possible Salmonella contamination. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0933-2015&amp;w=02042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>The Harvard Drug Group, LLC is recalling Thera Tablets with Beta Carotene Dietary Supplement, due to mislabeling. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0925-2015&amp;w=02042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>John B. Sanfilippo &amp; Son Inc. is recalling Fisher Brand Chopped Walnuts, and Pecan Cookie Pieces , both packaged in 8 oz. (226 g) plastic bags, due to possible Salmonella contamination. <br/></strong>Please see the FDA Enforcement Report, Week of February 4, 2015 for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=02042015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>Zachary Confections, Inc. is recalling Market Pantry Brand Dark Chocolate Covered Almonds (9 oz.), due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0937-2015&amp;w=02042015&amp;lang=eng</a><br/><br/></li>
	<li><strong>The Spice Mill is recalling Ground Cumin (2.75 oz.) and Cajun Seasoning (4 oz.), due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432761.htm" href="http://www.fda.gov/Safety/Recalls/ucm432761.htm">http://www.fda.gov/Safety/Recalls/ucm432761.htm</a><br/><br/></li>
	<li><strong>Krehbiel’s Specialty Meats, Inc. is recalling Fresh Beer Bratwurst Made With Tallgrass Brewery Oasis Beer in 16 oz. vacuum sealed packages, due to misbranding. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/rnr-028-2015</a><br/><br/></li>
</ul>

<hr/>
<h2>February 3, 2015 </h2>
<ul>
	<li><strong>Quest Nutrition, LLC is recalling QuestBar Protein Bar Chocolate Chip Cookie Dough Flavor net wt. 2.12 OZ (60 g) and QuestBar Protein Bar Double Chocolate Chunk Flavor net wt. 2.12 OZ (60 g), due to the possibility of plastic pieces introduced into the products by an ingredients supplier. <br/></strong>Please see the FDA Enforcement Report, Week of January 28, 2015 for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=Expand+Index&amp;w=01282015&amp;lang=eng#food</a><br/><br/></li>
	<li><strong>American Roland Food Corp. is recalling Roland brand Bruschetta, Italian-Style Appetizer (12 oz.) (340g), packaged in a glass jar, due to glass fragment found in product. <br/></strong>Please see the following website for more details: <br/><a title="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng" href="http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng">http://www.accessdata.fda.gov/scripts/enforcement/enforce_rpt-Product-Tabs.cfm?action=select&amp;recall_number=F-0923-2015&amp;w=01282015&amp;lang=eng</a><br/><br/></li>
	<li><strong>Hamchorom, Inc. is recalling HAITAI Tayo Crackers (140 g) and HAITAI Gyeran Crackers (70 g), due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432560.htm" href="http://www.fda.gov/Safety/Recalls/ucm432560.htm">http://www.fda.gov/Safety/Recalls/ucm432560.htm</a><br/><br/></li>
	<li><strong>Project Healthy Living, Inc. is recalling all packages of Premium Protein powder in chocolate and vanilla blends in both 14-serving sized steel tins and single-serving sized pouches, due to possible Staphylococcus enterotoxins contamination. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432558.htm" href="http://www.fda.gov/Safety/Recalls/ucm432558.htm">http://www.fda.gov/Safety/Recalls/ucm432558.htm</a><br/><br/></li>
	<li><strong>Freeland Foods, Inc. is recalling Go Raw Organic Sunflower Seed, due to possible Salmonella contamination. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fda.gov/Safety/Recalls/ucm432417.htm" href="http://www.fda.gov/Safety/Recalls/ucm432417.htm">http://www.fda.gov/Safety/Recalls/ucm432417.htm</a><br/><br/></li>
	<li><strong>Morrison Meat Packers is recalling “El Toro Cooked Pork and Water Product” and “Vida Latina Cooked Pork and Water Product”, of various weights, due to undeclared allergens. <br/></strong>Please see the following website for more details: <br/><a title="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release" href="http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release">http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive/archive/2015/recall-027-2015-release</a><br/><br/></li>
</ul>

<hr/>
<h2>Food Alert Archives for Previous Months</h2>
<ul>
	<li><a title="Archived Food Alerts" href="/foods/alerts/archives/">Archived Food Alerts</a><br/><br/></li>
</ul>

<hr/>
<h2>Links for Information on National Food Recall:</h2>
<ul>
	<li><a title="http://www.fda.gov/Safety/Recalls/default.htm" href="http://www.fda.gov/Safety/Recalls/default.htm">FDA Recall site (non-meat items)</a><br/><br/></li>
	<li><a title="http://www.fsis.usda.gov/Fsis_recalls/" href="http://www.fsis.usda.gov/Fsis_recalls/">USDA Recall site (meats and foods containing meat)</a><br/><br/></li>
	<li><a title="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg" href="http://fightbac.org/campaigns/recall-basics?gclid=CImzo-KDrqcCFRRg2godZV2JAg">Basic recall information for consumers</a><br/><br/></li>
	<li><a title="http://www.foodsafety.gov/keep/recalls/" href="http://www.foodsafety.gov/keep/recalls/">Many links to other agencies (also e-mail updates available)</a><br/><br/></li>
</ul>


<?php include '/home/codio/workspace/includes/footer.html' ?>	